using Npgsql;

namespace ServiceBooking.TestKit;

/// <summary>
/// Creates and tears down the disposable databases of one test run against a
/// <see cref="TestServerLease"/> — the template + per-slot scheme from ARCHITECTURE_CYCLE8.md §68,
/// and the ONLY place in the repository allowed to run DROP DATABASE (§69.3). Every drop goes through
/// <see cref="TestDatabaseNaming.EnsureOwnedByThisRun"/> first.
/// </summary>
public sealed class TestDatabaseLease
{
    private const string TemplateSlot = "template";
    private const string NoTemplateEnvironmentVariable = "SERVICEBOOKING_TEST_NO_TEMPLATE";

    private readonly TestServerLease _server;
    private readonly List<string> _createdDatabases = [];

    public TestDatabaseLease(TestServerLease server)
    {
        _server = server;
    }

    /// <summary>Database name for a given slot ("api", "legal", "dispatch", ...), per the naming
    /// scheme in ARCHITECTURE_CYCLE8.md §66.1.</summary>
    public string DatabaseNameFor(string slot) => $"sbtest_{TestRunKey.Current}_{slot}";

    /// <summary>Full Npgsql connection string for a slot's database, with the pool limits from §75
    /// applied. Does not create anything — call <see cref="EnsureSlotsAsync"/> first.</summary>
    public string ConnectionStringFor(string slot)
    {
        var builder = new NpgsqlConnectionStringBuilder(_server.MaintenanceConnectionString)
        {
            Database = DatabaseNameFor(slot),
        };
        return $"{builder.ConnectionString};{TestInfrastructure.PoolLimitTail}";
    }

    /// <summary>
    /// Creates the template database, migrates it once via <paramref name="migrateTemplate"/>, then
    /// creates one database per slot as a copy of the template (§68). Idempotent per slot within a
    /// lease instance — calling twice for the same slot is a no-op.
    /// </summary>
    public async Task EnsureSlotsAsync(IReadOnlyCollection<string> slots, Func<string, Task> migrateTemplate, CancellationToken cancellationToken = default)
    {
        var noTemplate = Environment.GetEnvironmentVariable(NoTemplateEnvironmentVariable) == "1";

        await using var connection = new NpgsqlConnection(_server.MaintenanceConnectionString);
        await connection.OpenAsync(cancellationToken);

        if (!noTemplate)
        {
            var templateName = DatabaseNameFor(TemplateSlot);
            await CreateDatabaseAsync(connection, templateName, template: null, cancellationToken);
            _createdDatabases.Add(templateName);

            await migrateTemplate(ConnectionStringFor(TemplateSlot));

            // Postgres refuses CREATE DATABASE ... TEMPLATE while other sessions are connected to the
            // template — the migration connection must be fully closed first (§68, step 2). Clearing
            // the pool for that exact connection string releases any pooled Npgsql connections too.
            await using (var templatePoolProbe = new NpgsqlConnection(ConnectionStringFor(TemplateSlot)))
            {
                NpgsqlConnection.ClearPool(templatePoolProbe);
            }

            foreach (var slot in slots)
            {
                var name = DatabaseNameFor(slot);
                await CreateDatabaseAsync(connection, name, template: templateName, cancellationToken);
                _createdDatabases.Add(name);
            }
        }
        else
        {
            foreach (var slot in slots)
            {
                var name = DatabaseNameFor(slot);
                await CreateDatabaseAsync(connection, name, template: null, cancellationToken);
                _createdDatabases.Add(name);
                await migrateTemplate(ConnectionStringFor(slot));
            }
        }
    }

    private static async Task CreateDatabaseAsync(NpgsqlConnection connection, string name, string? template, CancellationToken cancellationToken)
    {
        // Defence in depth: even though these names are generated by this class, every CREATE DATABASE
        // also goes through the same disposability check that guards DROP DATABASE.
        TestDatabaseNaming.EnsureDisposable(name);

        var sql = template is null
            ? $"CREATE DATABASE \"{name}\""
            : $"CREATE DATABASE \"{name}\" TEMPLATE \"{template}\"";

        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    /// <summary>
    /// Drops every database this lease created, guarded by <see cref="TestDatabaseNaming.EnsureOwnedByThisRun"/>
    /// on each one (§69.3, §70.1). Only used in <see cref="TestServerMode.External"/> mode — in
    /// container mode, disposing the container throws the databases away for free.
    /// </summary>
    public async Task DropAllAsync(CancellationToken cancellationToken = default)
    {
        if (_createdDatabases.Count == 0)
            return;

        await using var connection = new NpgsqlConnection(_server.MaintenanceConnectionString);
        await connection.OpenAsync(cancellationToken);

        // Drop leaf databases before the template they were copied from.
        foreach (var name in _createdDatabases.Where(n => !n.EndsWith($"_{TemplateSlot}", StringComparison.Ordinal)))
            await DropAsync(connection, name, cancellationToken);

        foreach (var name in _createdDatabases.Where(n => n.EndsWith($"_{TemplateSlot}", StringComparison.Ordinal)))
            await DropAsync(connection, name, cancellationToken);

        _createdDatabases.Clear();
    }

    public static async Task DropAsync(NpgsqlConnection connection, string databaseName, CancellationToken cancellationToken = default)
    {
        TestDatabaseNaming.EnsureOwnedByThisRun(databaseName);

        await using var command = new NpgsqlCommand($"DROP DATABASE IF EXISTS \"{databaseName}\" WITH (FORCE)", connection);
        await command.ExecuteNonQueryAsync(cancellationToken);
    }
}
