using Npgsql;

namespace ServiceBooking.TestKit;

/// <summary>
/// Creates and tears down the disposable databases of one test run against a
/// <see cref="TestServerLease"/> — the template + per-slot scheme from ARCHITECTURE_CYCLE8.md §68,
/// and the ONLY place in the repository allowed to run DROP DATABASE (§69.3). Every drop goes through
/// <see cref="TestDatabaseNaming.EnsureOwnedByThisRun"/> first.
/// </summary>
public sealed class TestDatabaseLease
{
    private const string TemplateSlot = "template";
    private const string NoTemplateEnvironmentVariable = "SERVICEBOOKING_TEST_NO_TEMPLATE";

    private readonly TestServerLease _server;
    private readonly List<string> _createdDatabases = [];

    public TestDatabaseLease(TestServerLease server)
    {
        _server = server;
    }

    /// <summary>Database name for a given slot ("api", "legal", "dispatch", ...), per the naming
    /// scheme in ARCHITECTURE_CYCLE8.md §66.1.</summary>
    public string DatabaseNameFor(string slot) => $"sbtest_{TestRunKey.Current}_{slot}";

    /// <summary>Full Npgsql connection string for a slot's database, with the pool limits from §75
    /// applied. Does not create anything — call <see cref="EnsureSlotsAsync"/> first.</summary>
    public string ConnectionStringFor(string slot)
    {
        var builder = new NpgsqlConnectionStringBuilder(_server.MaintenanceConnectionString)
        {
            Database = DatabaseNameFor(slot),
            MaxPoolSize = TestInfrastructure.PoolMaxSize,
            ConnectionIdleLifetime = TestInfrastructure.PoolConnectionIdleLifetimeSeconds,
            Timeout = TestInfrastructure.PoolTimeoutSeconds,
        };
        return builder.ConnectionString;
    }

    /// <summary>
    /// Creates the template database, migrates it once via <paramref name="migrateTemplate"/>, then
    /// creates one database per slot as a copy of the template (§68). Idempotent per slot within a
    /// lease instance — calling twice for the same slot is a no-op.
    /// </summary>
    public async Task EnsureSlotsAsync(IReadOnlyCollection<string> slots, Func<string, Task> migrateTemplate, CancellationToken cancellationToken = default)
    {
        var noTemplate = Environment.GetEnvironmentVariable(NoTemplateEnvironmentVariable) == "1";

        await using var connection = new NpgsqlConnection(_server.MaintenanceConnectionString);
        await connection.OpenAsync(cancellationToken);

        if (!noTemplate)
        {
            var templateName = DatabaseNameFor(TemplateSlot);
            await CreateDatabaseAsync(connection, templateName, template: null, cancellationToken);
            _createdDatabases.Add(templateName);

            await migrateTemplate(ConnectionStringFor(TemplateSlot));

            // Postgres refuses CREATE DATABASE ... TEMPLATE while other sessions are connected to the
            // template — the migration connection must be fully closed first (§68, step 2). Clearing
            // the pool for that exact connection string releases any pooled Npgsql connections too.
            await using (var templatePoolProbe = new NpgsqlConnection(ConnectionStringFor(TemplateSlot)))
            {
                NpgsqlConnection.ClearPool(templatePoolProbe);
            }

            foreach (var slot in slots)
            {
                var name = DatabaseNameFor(slot);
                await CreateDatabaseAsync(connection, name, template: templateName, cancellationToken);
                _createdDatabases.Add(name);
            }
        }
        else
        {
            foreach (var slot in slots)
            {
                var name = DatabaseNameFor(slot);
                await CreateDatabaseAsync(connection, name, template: null, cancellationToken);
                _createdDatabases.Add(name);
                await migrateTemplate(ConnectionStringFor(slot));
            }
        }
    }

    private async Task CreateDatabaseAsync(NpgsqlConnection connection, string name, string? template, CancellationToken cancellationToken)
    {
        // Defence in depth: even though these names are generated by this class, every CREATE DATABASE
        // also goes through the same disposability check that guards DROP DATABASE.
        TestDatabaseNaming.EnsureDisposable(name);

        await using (var existsCommand = new NpgsqlCommand("select 1 from pg_database where datname = @name", connection))
        {
            existsCommand.Parameters.AddWithValue("name", name);
            if (await existsCommand.ExecuteScalarAsync(cancellationToken) is not null)
            {
                // Idempotent only within THIS lease instance (EnsureSlotsAsync calling CreateDatabaseAsync
                // twice for the same slot) — already-created by a previous call inside _createdDatabases.
                // A database that exists but was never created by THIS lease belongs to some other
                // process/run that happens to share a run key (review finding N2: two processes started
                // with the same SERVICEBOOKING_TEST_RUN_KEY used to silently "adopt" each other's
                // databases here, and then DropAllAsync would drop the other process's live database out
                // from under it on teardown). Refuse instead of adopting.
                if (_createdDatabases.Contains(name))
                    return;

                throw new TestSafetyException(
                    $"[sb-test] Отказ: база \"{name}\" уже существует, но не создавалась этим прогоном.\n" +
                    $"  Похоже, что SERVICEBOOKING_TEST_RUN_KEY=\"{TestRunKey.Current}\" совпадает с ключом другого " +
                    "одновременно выполняющегося прогона (например, двух job'ов одного CI workflow).\n" +
                    "  Что сделать: задайте уникальный SERVICEBOOKING_TEST_RUN_KEY для каждого одновременного прогона, " +
                    "или не задавайте его вовсе — тогда ключ будет случайным. Ничего не создано и не удалено.");
            }
        }

        var sql = template is null
            ? $"CREATE DATABASE \"{name}\""
            : $"CREATE DATABASE \"{name}\" TEMPLATE \"{template}\"";

        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync(cancellationToken);

        // §70.3 п.3: metadata is written at creation time so the sweeper can later compute an age for
        // this database without guessing. Without this, every server-mode database stays "undetermined"
        // forever (age unknown => never eligible for deletion), which defeats the sweeper entirely.
        var metadata = new ResourceLabels.DatabaseMetadata(
            RunKey: TestRunKey.Current,
            Host: Environment.MachineName,
            Pid: Environment.ProcessId,
            StartedAtUtc: DateTimeOffset.UtcNow,
            Workdir: TestInfrastructure.WorkingCopyRoot);

        var commentJson = ResourceLabels.ToComment(metadata).Replace("'", "''");
        await using var commentCommand = new NpgsqlCommand($"COMMENT ON DATABASE \"{name}\" IS '{commentJson}'", connection);
        await commentCommand.ExecuteNonQueryAsync(cancellationToken);
    }

    /// <summary>
    /// Drops every database this lease created, guarded by <see cref="TestDatabaseNaming.EnsureOwnedByThisRun"/>
    /// on each one (§69.3, §70.1). Only used in <see cref="TestServerMode.External"/> mode — in
    /// container mode, disposing the container throws the databases away for free.
    /// </summary>
    public async Task DropAllAsync(CancellationToken cancellationToken = default)
    {
        if (_createdDatabases.Count == 0)
            return;

        await using var connection = new NpgsqlConnection(_server.MaintenanceConnectionString);
        await connection.OpenAsync(cancellationToken);

        // Drop leaf databases before the template they were copied from.
        foreach (var name in _createdDatabases.Where(n => !n.EndsWith($"_{TemplateSlot}", StringComparison.Ordinal)))
            await DropAsync(connection, name, cancellationToken);

        foreach (var name in _createdDatabases.Where(n => n.EndsWith($"_{TemplateSlot}", StringComparison.Ordinal)))
            await DropAsync(connection, name, cancellationToken);

        _createdDatabases.Clear();
    }

    /// <summary>Drops a database belonging to <em>this</em> run (the run whose in-process
    /// <see cref="TestRunKey.Current"/> matches the run-key segment of the name). Used by test teardown,
    /// never by the sweeper — see <see cref="DropLeakedAsync"/> for the cross-process case.</summary>
    public static async Task DropAsync(NpgsqlConnection connection, string databaseName, CancellationToken cancellationToken = default)
    {
        TestDatabaseNaming.EnsureOwnedByThisRun(databaseName);
        await DropUncheckedAsync(connection, databaseName, cancellationToken);
    }

    /// <summary>
    /// Drops a database left behind by a DIFFERENT run. This is the only place in the repository allowed
    /// to drop a database whose run-key does not match <see cref="TestRunKey.Current"/> — the sweeper
    /// (<see cref="Sweeper"/>) is, by definition, a separate process cleaning up after other processes, so
    /// <see cref="TestDatabaseNaming.EnsureOwnedByThisRun"/> can never pass for it (see review finding
    /// blocker #1: sweep --apply could not delete anything). Safety here comes from two things instead:
    /// the caller (Sweeper) verifies <see cref="TestDatabaseNaming.IsDisposable"/> AND applies its own dead/
    /// alive/undetermined classification before calling this, and this method re-asserts the name is at
    /// least formally disposable so nothing outside the sbtest_&lt;key&gt;_&lt;slot&gt; namespace can ever
    /// reach DROP DATABASE.
    /// </summary>
    public static async Task DropLeakedAsync(NpgsqlConnection connection, string databaseName, CancellationToken cancellationToken = default)
    {
        TestDatabaseNaming.EnsureDisposable(databaseName);
        await DropUncheckedAsync(connection, databaseName, cancellationToken);
    }

    private static async Task DropUncheckedAsync(NpgsqlConnection connection, string databaseName, CancellationToken cancellationToken)
    {
        await using var command = new NpgsqlCommand($"DROP DATABASE IF EXISTS \"{databaseName}\" WITH (FORCE)", connection);
        await command.ExecuteNonQueryAsync(cancellationToken);
    }
}
