namespace ServiceBooking.Core.Entities;

/// <summary>
/// ARCHITECTURE_CYCLE24.md §448.2, §456 — a browser that asked to hear about ONE order (web-push to a customer without an
/// account). Created only by the order's secret token. <see cref="Id"/> is generated by the application before insert: it is part of
/// the AAD the keys are encrypted against (<c>"order-push-subscription:{Id}"</c>). The keys are never returned by any DTO.
/// </summary>
public class OrderPushSubscription
{
    public Guid Id { get; set; }
    public Guid OrderId { get; set; }
    public Order Order { get; set; } = null!;

    public string Endpoint { get; set; } = string.Empty;
    public string P256dhCiphertext { get; set; } = string.Empty;
    public string AuthCiphertext { get; set; } = string.Empty;
    public string? KeyId { get; set; }

    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
    public DateTime? LastSuccessAtUtc { get; set; }
    public int ConsecutiveFailures { get; set; }
}
