using ServiceBooking.Core.Enums;

namespace ServiceBooking.Core.Entities;

/// <summary>
/// One phone-ownership confirmation attempt (ARCHITECTURE_CYCLE12.md §142.1, Q1). The one-time secret a
/// person actually shares (the deep-link <c>payload</c>) is NEVER stored — only its SHA-256
/// (<see cref="PayloadHash"/>); the same is true of <see cref="StatusTokenHash"/>, the second half of the
/// poll key. A dump of this table gives an attacker nothing they could present back to either endpoint.
/// </summary>
public class PhoneVerificationSession
{
    /// <summary>Generated by the application (not the database) — this is the id both the poll endpoint
    /// URL and <c>PhoneVerificationRef</c> carry.</summary>
    public Guid Id { get; set; }

    /// <summary>SHA-256(payload) in lowercase hex. Unique — a payload can only ever back one session, so
    /// a collision (astronomically unlikely for 32 random bytes) fails loudly rather than silently
    /// reusing someone else's session.</summary>
    public string PayloadHash { get; set; } = string.Empty;

    /// <summary>SHA-256(statusToken) in lowercase hex. Polling requires the PAIR {sessionId, statusToken}
    /// — the id alone never proves anything, so the session is not enumerable.</summary>
    public string StatusTokenHash { get; set; } = string.Empty;

    public PhoneVerificationPurpose Purpose { get; set; }

    public PhoneVerificationMethod Method { get; set; }

    /// <summary>Canonicalized (<c>PhoneNormalizer.TryNormalizeRussian</c>) form of what the caller typed.
    /// Personal data belonging to someone who has not verified anything yet (R11) — this is exactly why
    /// the retention rule for this table (§151.1) has a one-day window, far shorter than the session's
    /// own 10-minute TTL would suggest is necessary; the extra margin is incident-review slack, not a
    /// working lifetime.</summary>
    public string CanonicalPhone { get; set; } = string.Empty;

    /// <summary>Set only for <see cref="PhoneVerificationPurpose.Profile"/>. The FK is Cascade at the
    /// database level, but that cascade never actually fires in practice — <c>ProfileController.DeleteAccount</c>
    /// leaves the account row behind as a tombstone rather than deleting it, so this table's own rows are
    /// removed EXPLICITLY by that same method (§151.2), the same convention <see cref="PushSubscription"/>
    /// already follows.</summary>
    public string? UserId { get; set; }
    public AppUser? User { get; set; }

    public PhoneVerificationStatus Status { get; set; } = PhoneVerificationStatus.Pending;

    public PhoneVerificationFailureReason? FailureReason { get; set; }

    /// <summary>Set only when <see cref="FailureReason"/> is <c>PhoneMismatch</c> — the MASKED (never
    /// raw) form of the number that was actually shared, so <c>GET /phone-verification/sessions/{id}</c>'s
    /// <c>message</c> can name both numbers (API_CONTRACT_CYCLE12.md §165's exact wording: "Вы
    /// поделились номером X, а на сайте введён Y"). Deliberately not the extra field the architecture
    /// doc's §142.1 table enumerates — added because the contract's own wording for this one reason
    /// needs a second number that <see cref="CanonicalPhone"/> alone cannot supply, and only the masked
    /// form is ever persisted, never the raw one.</summary>
    public string? MismatchedPhoneMasked { get; set; }

    /// <summary>HMAC-SHA256 of the MAX account id that opened this session's deep link
    /// (<c>ExternalAccountKey</c>, §142.3) — set the moment <c>bot_started</c> links the session. Never
    /// exposed in any DTO (§142.3's closing bullet).</summary>
    public string? ExternalAccountKey { get; set; }

    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;

    /// <summary>TTL cutoff — <c>PhoneVerification:SessionTtlMinutes</c> (default 10) after creation.
    /// <see cref="PhoneVerificationStatus.Pending"/>/<see cref="PhoneVerificationStatus.Linked"/> past
    /// this instant read back as "Expired" (computed, never stored — §145.2).</summary>
    public DateTime ExpiresAtUtc { get; set; }

    /// <summary>Set when <c>bot_started</c> links the session (moves it to
    /// <see cref="PhoneVerificationStatus.Linked"/>).</summary>
    public DateTime? LinkedAtUtc { get; set; }

    /// <summary>Set the moment the session reaches a terminal decision (Verified or Rejected).</summary>
    public DateTime? CompletedAtUtc { get; set; }

    /// <summary>Only meaningful for <see cref="PhoneVerificationPurpose.Registration"/>: the window
    /// (<c>CompletedAtUtc + PhoneVerification:VerifiedSessionUsableMinutes</c>, default 30) in which
    /// <c>POST /api/auth/register</c> may still present this session. Null until the session is Verified.</summary>
    public DateTime? ConsumableUntilUtc { get; set; }

    /// <summary>How many times a <c>contact</c> attachment was processed against this session —
    /// observability only, never gates anything (§142.1).</summary>
    public int AttemptCount { get; set; }
}
