namespace ServiceBooking.Core.Entities;

/// <summary>
/// One browser/device subscribed to receive Web Push notifications (ARCHITECTURE_CYCLE9.md §105.4,
/// US-123). <see cref="Id"/> is generated by the application BEFORE insert (not left to the database) —
/// it participates in the AAD string <see cref="Services.Notifications.SecretProtector"/> binds the
/// encrypted key material to, so the ciphertext columns cannot be created before the id they're bound to
/// is known.
///
/// Ключи подписки (<see cref="P256dhCiphertext"/>, <see cref="AuthCiphertext"/>) are never returned in
/// any DTO — not to the owner, not to the master themselves, not to a superadmin (§105.2).
/// </summary>
public class PushSubscription
{
    public Guid Id { get; set; }

    /// <summary>Owner of the subscription. Indexed — every read/write this cycle does goes "my
    /// subscriptions", never "all subscriptions".</summary>
    public string UserId { get; set; } = string.Empty;
    public AppUser User { get; set; } = null!;

    /// <summary>Push service delivery address. Unique — re-subscribing the same browser upserts the
    /// existing row (§105.5) instead of creating a duplicate.</summary>
    public string Endpoint { get; set; } = string.Empty;

    /// <summary>Client P-256 public key, encrypted at rest (<c>SecretProtector</c>, AAD
    /// <c>"push-subscription:{Id}"</c>).</summary>
    public string P256dhCiphertext { get; set; } = string.Empty;

    /// <summary>Client authentication secret, encrypted at rest the same way as
    /// <see cref="P256dhCiphertext"/>.</summary>
    public string AuthCiphertext { get; set; } = string.Empty;

    /// <summary>First 8 hex characters of the master key's fingerprint at encryption time — same
    /// convention as <c>NotificationChannel.ProviderSecretKeyId</c>, lets an operator eyeball-match a
    /// row's key against a rotation.</summary>
    public string? KeyId { get; set; }

    /// <summary>Human-readable device label ("Chrome на Windows") so a master understands what they're
    /// disabling on the devices list.</summary>
    public string DeviceLabel { get; set; } = string.Empty;

    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;

    /// <summary>Last time a push through this subscription was accepted by the push service (HTTP
    /// 2xx). Null means "never successfully delivered" — the retention rule (§105.11) treats that the
    /// same as "very old" rather than exempting it forever.</summary>
    public DateTime? LastSuccessAtUtc { get; set; }

    /// <summary>Diagnostics only — the send outcome (not this counter) decides retry/removal, per the
    /// classification table in §105.8.</summary>
    public int ConsecutiveFailures { get; set; }
}
