using ServiceBooking.Core.Enums;

namespace ServiceBooking.Core.Entities;

/// <summary>
/// ARCHITECTURE_CYCLE25.md §497.2 — a MAX chat bound to a staff account (one row per account, Q-25-3).
/// The chat id is never exposed in any DTO or export; only its ciphertext and an HMAC key are stored.
/// </summary>
public class StaffMaxLink
{
    /// <summary>Generated by the application before insert — part of the encryption AAD.</summary>
    public Guid Id { get; set; }

    public string UserId { get; set; } = string.Empty;
    public AppUser? User { get; set; }

    /// <summary>HMAC of the chat id (ExternalAccountKey.Compute with the "max-chat:" prefix). Not unique:
    /// one chat can be bound to several accounts.</summary>
    public string ChatKey { get; set; } = string.Empty;

    /// <summary>SecretProtector ciphertext of the chat id; null after the bot was stopped.</summary>
    public string? ChatIdCiphertext { get; set; }
    public string? KeyId { get; set; }

    public StaffMaxLinkStatus Status { get; set; } = StaffMaxLinkStatus.Active;

    public DateTime LinkedAtUtc { get; set; } = DateTime.UtcNow;
    public DateTime? StoppedAtUtc { get; set; }
    public DateTime? LastSuccessAtUtc { get; set; }
    public int ConsecutiveFailures { get; set; }
}
