using FluentAssertions;
using ServiceBooking.API.Services;

namespace ServiceBooking.UnitTests;

/// <summary>API_CONTRACT_CYCLE5.md §50.1, ПЛ5 — formal checksum only, no ЕГРЮЛ/ЕГРИП call.</summary>
public class InnValidatorTests
{
    // Sberbank's real, public 10-digit ИНН — a widely-published, independently-verifiable test vector.
    [Fact]
    public void IsValid_RealTenDigitInn_ReturnsTrue()
    {
        InnValidator.IsValid("7707083893").Should().BeTrue();
    }

    [Fact]
    public void IsValid_TenDigitInn_WrongCheckDigit_ReturnsFalse()
    {
        InnValidator.IsValid("7707083894").Should().BeFalse();
    }

    // A twelve-digit ИНН whose two check digits were computed independently against the published ФНС
    // coefficients (see the cycle report) — not generated by the code under test.
    [Fact]
    public void IsValid_RealTwelveDigitInn_ReturnsTrue()
    {
        InnValidator.IsValid("500100732259").Should().BeTrue();
    }

    [Fact]
    public void IsValid_TwelveDigitInn_WrongFirstCheckDigit_ReturnsFalse()
    {
        InnValidator.IsValid("500100732269").Should().BeFalse();
    }

    [Fact]
    public void IsValid_TwelveDigitInn_WrongSecondCheckDigit_ReturnsFalse()
    {
        InnValidator.IsValid("500100732250").Should().BeFalse();
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("123")]                // too short
    [InlineData("77070838931")]        // 11 digits — neither valid length
    [InlineData("77070838930000")]     // too long
    [InlineData("770708389a")]         // non-digit
    [InlineData("  7707083893")]       // whitespace, not a digit
    public void IsValid_MalformedInput_ReturnsFalse(string? inn)
    {
        InnValidator.IsValid(inn).Should().BeFalse();
    }
}
