import { api } from './client'
import type { BookingStatus, Paged } from '../types'
import type { ShowcaseFilter } from '../utils/showcaseFilter'

export interface AdminStats {
  /** Cycle 28 (API_CONTRACT_CYCLE28.md §594.3): the five counters below are WITHOUT showcase data. */
  totalCompanies: number
  totalUsers: number
  totalBookings: number
  completedBookings: number
  totalRevenue: number
  /** Cycle 28 — the showcase counted separately; absent on older servers. */
  showcaseCompanies?: number
  showcaseUsers?: number
  showcaseBookings?: number
}

export interface AdminUser {
  id: string
  phone: string
  email?: string | null
  firstName: string
  lastName: string
  avatarUrl?: string
  createdAt: string
  roles: string[]
  ownedCompanyCount: number
  planConfigId?: string
  planName: string
  paidUntil?: string
  subscriptionActive: boolean
  /** Cycle 28 (§594.2) — generated by the showcase generator; absent on older servers = false. */
  isShowcase?: boolean
}

export interface AdminCompany {
  id: string
  name: string
  slug: string
  /** Cycle 23 (API_CONTRACT_CYCLE23.md §408.6). */
  kind?: 'Services' | 'Orders' | 'Stays' | 'Baths'
  publicUrl?: string
  email?: string
  phone?: string
  isActive: boolean
  allowSelfBooking: boolean
  createdAt: string
  memberCount: number
  bookingCount: number
  ownerUserId: string
  ownerEmail: string
  planConfigId?: string
  planName: string
  paidUntil?: string
  subscriptionActive: boolean
  /** Cycle 28 (§594.2). */
  isShowcase?: boolean
  showcaseBookingOpen?: boolean
}

interface AdminBooking {
  id: string
  companyName: string
  serviceName: string
  masterName: string
  clientName: string
  clientPhone?: string
  date: string
  startTime: string
  endTime: string
  status: BookingStatus
  price: number
}

interface MasterReport {
  masterId: string
  masterName: string
  commissionPercent: number
  bookingsCount: number
  totalAmount: number
  masterEarnings: number
  companyEarnings: number
}

export const adminApi = {
  getStats: () => api.get<AdminStats>('/admin/stats').then((r) => r.data),
  // API_CONTRACT.md §11.2 (BREAKING) — array replaced by the Paged<T> envelope.
  getUsers: (search?: string, page = 1, pageSize = 20, showcase?: ShowcaseFilter) =>
    api.get<Paged<AdminUser>>('/admin/users', { params: { search, page, pageSize, showcase } }).then((r) => r.data),
  updateUserRoles: (id: string, roles: string[]) => api.put(`/admin/users/${id}/roles`, roles),
  getCompanies: (search?: string, page = 1, pageSize = 20, kind?: 'Services' | 'Orders' | 'Stays' | 'Baths', showcase?: ShowcaseFilter) =>
    api
      .get<Paged<AdminCompany>>('/admin/companies', { params: { search, page, pageSize, kind, showcase } })
      .then((r) => r.data),
  // updateSubscription removed — PUT /admin/owners/{id}/subscription is 410 Gone in cycle 7
  // (API_CONTRACT_CYCLE7.md §54). Replacement: adminBillingApi.assignSubscription (billing-accounts).
  updateCompany: (id: string, data: { name: string; isActive: boolean; allowSelfBooking: boolean }) =>
    api.put(`/admin/companies/${id}`, data),
  updateCompanyOwner: (id: string, newOwnerUserId: string) =>
    api.put(`/admin/companies/${id}/owner`, { newOwnerUserId }),
  getBookings: (params: { companyId?: string; from?: string; to?: string; status?: string }) =>
    api.get<AdminBooking[]>('/admin/bookings', { params }).then((r) => r.data),
  getMastersReport: (companyId: string, from: string, to: string) =>
    api.get<MasterReport[]>('/reports/masters', { params: { companyId, from, to } }).then((r) => r.data),
}
