/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/companies/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Публичная карточка компании (анонимный доступ)
         * @description Форма ответа прежняя (CompanyDto), цикл 15 добавляет три поля. Публичная страница компании
         *     НЕ получает ни одного нового запроса: ссылки в карты приходят здесь же.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Компания найдена */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompanyCycle15Fields"];
                    };
                };
                /** @description Компании нет (пустое тело) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Сохранение настроек компании — ЕДИНСТВЕННЫЙ путь записи ссылок и окна переноса
         * @description Доступ: владелец компании или SuperAdmin (как сегодня), [RequiresOwnerTerms] как сегодня.
         *     Ни POST /api/companies, ни PUT /api/admin/companies/{id} эти поля не принимают — путь
         *     записи намеренно один (ARCHITECTURE_CYCLE15.md §253.4).
         *
         *     Три состояния каждого поля ссылки:
         *       * поле отсутствует или null — значение не трогаем;
         *       * "" (или пробелы)          — ОЧИЩАЕМ поле (обратимая настройка);
         *       * непустая строка           — валидируем и сохраняем КАК ЕСТЬ, байт в байт.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCompanyCycle15Fields"];
                };
            };
            responses: {
                /** @description Сохранено; тело — полный CompanyDto с применёнными значениями */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompanyCycle15Fields"];
                    };
                };
                400: components["responses"]["PlainTextBadRequest"];
                /** @description Не аутентифицирован (пустое тело) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Нет прав на эту компанию (пустое тело) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Компании нет (пустое тело) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * «Мои визиты» — список записей клиента
         * @description Форма прежняя (массив BookingDto), цикл 15 добавляет три ВЫЧИСЛЯЕМЫХ поля. Они считаются
         *     ТОЛЬКО здесь; на /master, /{id} и в ответе POST /api/bookings приходят null — это значит
         *     «сервер не считал», а не «нельзя».
         */
        get: {
            parameters: {
                query?: {
                    status?: "upcoming" | "Pending" | "Confirmed" | "Cancelled" | "Completed" | "NoShow";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список записей клиента */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingCycle15Fields"][];
                    };
                };
                400: components["responses"]["PlainTextBadRequest"];
                /** @description Не аутентифицирован (пустое тело) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Сетка слотов; на ветке excludeBookingId теперь допускается клиент-владелец записи
         * @description Параметры и ответ НЕ меняются. Меняется правило доступа на ветке excludeBookingId:
         *       * персонал, который может управлять записью — как сегодня;
         *       * КЛИЕНТ — ВЛАДЕЛЕЦ ЭТОЙ ЗАПИСИ — 200 и ШТАТНАЯ сетка (график мастера, перерывы, шаг
         *         сетки, без собственного текущего интервала);
         *       * посторонний — 404 (было 403): код ответа не должен работать оракулом.
         *
         *     Для клиента manual и extendedHours ИГНОРИРУЮТСЯ сервером (он не персонал этой компании);
         *     интерфейс клиента их не передаёт вовсе.
         */
        get: {
            parameters: {
                query: {
                    companyId: string;
                    masterId: string;
                    serviceId?: string;
                    serviceIds?: string[];
                    date: string;
                    /** @description ПРОСЬБА, а не разрешение. Сервер чтит её только у персонала ЭТОЙ компании. */
                    manual?: boolean;
                    /** @description Работает только вместе с manual и только у персонала. Клиенту недоступно. */
                    extendedHours?: boolean;
                    /** @description Переносимая запись — её собственный интервал не блокирует сам себя. */
                    excludeBookingId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Сетка слотов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimeSlot"][];
                    };
                };
                400: components["responses"]["PlainTextBadRequest"];
                /** @description Не аутентифицирован (пустое тело) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /**
                 * @description Записи нет ИЛИ вызывающий не имеет к ней отношения. Пустое тело — эти два случая
                 *     намеренно неразличимы (ЛОМАЮЩЕЕ: раньше второй случай отвечал 403).
                 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Перенос записи — персоналом (как сегодня) или клиентом-владельцем (новое)
         * @description Маршрут, метод и ТЕЛО не меняются. Второй, «клиентской» ручки нет: полномочие вычисляет
         *     сервер из базы, а не из запроса, поэтому клиент физически не может попросить послабление
         *     персонала (любое свободное время без графика и сетки).
         *
         *     Полномочия:
         *       * Staff (назначенный мастер, владелец компании записи, SuperAdmin) — правила КАК СЕГОДНЯ;
         *       * ClientOwner (booking.clientId == вызывающий) — строгие клиентские правила;
         *       * все остальные — 404, пустое тело.
         *
         *     Клиентские правила проверяются сервером в этом порядке:
         *       1) запись существует и принадлежит вызывающему        -> 404
         *       2) статус Pending или Confirmed                       -> 400
         *       3) company.allowSelfBooking включена                  -> 403
         *       4) тариф компании разрешает онлайн-запись             -> 402
         *       5) до ТЕКУЩЕГО визита >= clientRescheduleMinHours     -> 400
         *       6) до НОВОГО времени  >= clientRescheduleMinHours     -> 400
         *       7) новая дата в пределах bookingHorizonDays           -> 400
         *       8) новое время есть в ШТАТНОЙ сетке мастера           -> 409
         *       9) не в прошлом и не через полночь                    -> 409
         *      10) слот не занят чужой записью (под advisory-lock)    -> 409
         *
         *     Переносятся ТОЛЬКО дата и время; endTime пересчитывает сервер. Мастер, услуги и компания
         *     не меняются. Гостевая запись (без clientId) клиентом не переносится — ответ 404.
         *
         *     Лимит: booking-reschedule, 30 запросов в час на пользователя.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RescheduleRequest"];
                };
            };
            responses: {
                /** @description Перенесено. Тела нет. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["PlainTextBadRequest"];
                /** @description Не аутентифицирован (пустое тело) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Онлайн-запись не входит в тариф компании (голая строка) */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /** @example Online booking requires a paid subscription. */
                        "text/plain": string;
                    };
                };
                /** @description У компании выключена онлайн-запись (пустое тело) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /**
                 * @description Записи нет ИЛИ вызывающий не имеет к ней отношения. Пустое тело — эти два случая
                 *     намеренно неразличимы (ЛОМАЮЩЕЕ: раньше второй случай отвечал 403).
                 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Время недоступно (вне графика, в прошлом или уже занято) — голая строка */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /** @example Time slot is no longer available */
                        "text/plain": string;
                    };
                };
                429: components["responses"]["PlainTextTooManyRequests"];
            };
        };
        trace?: never;
    };
    "/api/admin/plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Сохранение тарифа — семантика полей прежняя, добавлен один 409
         * @description Доступ: SuperAdmin. СЕМАНТИКА ПОЛЕЙ НЕ МЕНЯЕТСЯ — контракт фиксирует её, потому что
         *     дефект цикла был на фронте: форма слала isActive/isPublic/sortOrder константами при
         *     каждом сохранении.
         *
         *       * isPublic, sortOrder — nullable: прислали -> применить, null/отсутствует -> оставить как есть;
         *       * isActive           — не nullable, применяется всегда; деактивация тарифа с активными
         *                              подписчиками -> 409 (как сегодня); системный бесплатный тариф
         *                              деактивировать нельзя вовсе -> 409 (как сегодня);
         *       * isSystemFree       — в теле ОТСУТСТВУЕТ, меняется отдельным маршрутом .../system-free.
         *
         *     НОВОЕ: снятие системного бесплатного тарифа с витрины (isPublic true -> false при
         *     isSystemFree: true) -> 409. Только НА ПЕРЕХОДЕ: тариф, который уже скрыт (поставляемый
         *     сид именно такой), сохраняется как раньше.
         *
         *     «Устаревший тариф» = isActive:true + isPublic:false. Отдельного поля статуса нет и не будет.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminPlanInputCycle15"];
                };
            };
            responses: {
                /** @description Сохранено; тело — AdminPlanDto */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminPlanCycle15Fields"];
                    };
                };
                400: components["responses"]["PlainTextBadRequest"];
                /** @description Не аутентифицирован (пустое тело) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не SuperAdmin (пустое тело) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Тарифа нет (пустое тело) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /**
                 * @description Голая строка. Возможные причины: деактивация тарифа с активными подписчиками;
                 *     деактивация системного бесплатного тарифа; НОВОЕ — снятие системного бесплатного
                 *     тарифа с витрины.
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /** @example Системный бесплатный тариф нельзя убрать с витрины. */
                        "text/plain": string;
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/legal/texts/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Текст интерфейса; для BookingNotice меняется СОДЕРЖИМОЕ, не форма
         * @description Форма ответа не меняется. Для ключа BookingNotice меняется contentHtml (уходит мёртвое
         *     «Подробнее», литерал «Название компании» заменяется разметкой ВРЕМЕНИ ПОКАЗА) и version
         *     (поднимается; изменение редакционное — повторного согласия не требуется).
         *
         *     Разметка времени показа — ТРИ АТРИБУТА, единственное известное имя значения companyName:
         *       <span data-legal-value="companyName"></span>        — сюда подставляется ЭКРАНИРОВАННОЕ значение
         *       <span data-legal-when="companyName">…</span>        — остаётся, если значение известно
         *       <span data-legal-unless="companyName">…</span>      — остаётся, если значение неизвестно
         *
         *     Фигурных скобок здесь нет и быть не должно: {{…}} — величины времени ПУБЛИКАЦИИ, любой
         *     оставшийся такой токен блокирует публикацию документа.
         *
         *     Подстановку делает фронт ПРИ РЕНДЕРЕ, экранируя & < > " '. Подставленный текст в кеш
         *     useLegalText не кладётся — иначе два салона подряд в одной сессии получили бы название
         *     друг друга.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example BookingNotice */
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Текст найден (кешируется 5 минут — Cache-Control: public, max-age=300) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LegalUiText"];
                    };
                };
                /** @description Ключа нет (пустое тело) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Правовые документы временно недоступны (голая строка) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Ссылка на Яндекс Карты, которую владелец вставил из адресной строки. Сохраняется БАЙТ В
         *     БАЙТ: путь и query не разбираются и не нормализуются. Только https. Хост: yandex.<tld>
         *     или *.yandex.<tld>, где <tld> из закрытого списка (ru, com, com.tr, by, kz, uz, az,
         *     com.ge, ee, lv, lt, md, fr, com.am, tm, tj, kg). null = поле не заполнено -> переход не
         *     показывается вообще. "" в ЗАПРОСЕ = очистить поле.
         * @example https://yandex.ru/maps/org/syrovarnya/11766054863/?ll=83.795110%2C53.330510&z=17
         */
        MapLinkYandex: string | null;
        /**
         * @description То же для 2ГИС. Хост: 2gis.ru или *.2gis.ru. Сокращатели (clck.ru, go.2gis.com) не
         *     принимаются: под сокращённой ссылкой может оказаться что угодно, а поле показывается
         *     всем посетителям публичной страницы.
         * @example https://2gis.ru/barnaul/firm/563478234628539/83.795014%2C53.330486?m=83.795954%2C53.330025%2F17.89
         */
        MapLinkTwoGis: string | null;
        /**
         * @description За сколько часов до начала визита клиент ещё может перенести запись сам. Настройка
         *     КОМПАНИИ, а не константа продукта. 0 = «до самого начала визита». Проверяется на сервере
         *     по ОБОИМ концам правила (и текущее время визита, и новое). «Выключить перенос» — это не
         *     это поле, а company.allowSelfBooking.
         * @default 2
         */
        ClientRescheduleMinHours: number;
        /**
         * @description ТОЛЬКО поля, которые добавляет цикл 15. Остальная форма CompanyDto — прежняя
         *     (см. контракты циклов 4, 6, 7, 10, 13), поэтому additionalProperties: true.
         */
        CompanyCycle15Fields: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /**
             * @description Существующее поле. Цикл меняет только его ПОКАЗ: первый пункт контактов на карточке
             *     компании и ссылка tel: (цифры и +). Видимое написание номера не меняется.
             */
            phone?: string | null;
            yandexMapsUrl: components["schemas"]["MapLinkYandex"];
            twoGisUrl: components["schemas"]["MapLinkTwoGis"];
            clientRescheduleMinHours: components["schemas"]["ClientRescheduleMinHours"];
        } & {
            [key: string]: unknown;
        };
        /**
         * @description ТОЛЬКО поля, которые цикл 15 добавляет в UpdateCompanyDto. Остальные поля (name,
         *     description, address, phone, email, allowSelfBooking, requirePrepayment,
         *     showInPublicListing, cityId, timeZoneId, bookingHorizonDays) — как были.
         *     Семантика ссылок: отсутствует/null = не трогать, "" = очистить, строка = сохранить как есть.
         */
        UpdateCompanyCycle15Fields: {
            yandexMapsUrl?: components["schemas"]["MapLinkYandex"];
            twoGisUrl?: components["schemas"]["MapLinkTwoGis"];
            /** @description null/отсутствует = не трогать; вне [0,168] = 400. */
            clientRescheduleMinHours?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description ТОЛЬКО поля, которые добавляет цикл 15 в BookingDto. Считаются ИСКЛЮЧИТЕЛЬНО на
         *     GET /api/bookings/client; на остальных эндпоинтах приходят null («сервер не считал»).
         */
        BookingCycle15Fields: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            date: string;
            /** @example 14:00:00 */
            startTime: string;
            /** @enum {string} */
            status: "Pending" | "Confirmed" | "Completed" | "Cancelled" | "NoShow";
            /**
             * @description Можно ли ПРЯМО СЕЙЧАС перенести эту запись клиентом. Считает сервер тем же набором
             *     правил, который применит PATCH .../reschedule. Кнопка «Перенести» рисуется по этому
             *     флагу, а НЕ по вычислению времени в вёрстке. Подсказка интерфейсу, а не разрешение:
             *     сервер проверяет всё заново в момент PATCH.
             */
            clientRescheduleAllowed?: boolean | null;
            /** @description Окно переноса компании этой записи — чтобы объяснить пользователю, почему кнопки нет. */
            clientRescheduleMinHours?: number | null;
            /**
             * @description Горизонт записи компании. Окно переноса рисует ровно столько дат; заменяет зашитые
             *     в RescheduleModal 14 дней.
             */
            companyBookingHorizonDays?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description БЕЗ ИЗМЕНЕНИЙ по сравнению с сегодняшним RescheduleDto. Ни одного нового поля —
         *     additionalProperties: false здесь и есть гарантия того, что клиент не может попросить
         *     послабление персонала (manual/extendedHours в этом теле не существует).
         */
        RescheduleRequest: {
            /**
             * Format: date
             * @example 2026-10-02
             */
            date: string;
            /** @example 14:00:00 */
            startTime: string;
        };
        TimeSlot: {
            /** @example 14:00:00 */
            start: string;
            /** @example 15:00:00 */
            end: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Форма AdminPlanInput не меняется. Здесь описаны поля, вокруг которых крутится блок D, —
         *     чтобы контракт зафиксировал их СЕМАНТИКУ. isSystemFree в теле отсутствует намеренно.
         */
        AdminPlanInputCycle15: {
            name: string;
            /** Format: double */
            pricePerMonth: number;
            maxEmployees?: number | null;
            maxCompanies?: number | null;
            /**
             * @description Не nullable, применяется всегда. Форма админки обязана слать ТЕКУЩЕЕ значение тарифа,
             *     а не константу true: сегодня сохранение деактивированного тарифа молча его активирует.
             * @default true
             */
            isActive: boolean;
            /**
             * @description Прислали -> применить; null/отсутствует -> оставить как есть. Форма админки обязана
             *     слать то, что видит оператор: сегодня она шлёт константу true, из-за чего любое
             *     сохранение возвращает тариф на витрину.
             * @default false
             */
            isPublic: boolean | null;
            /**
             * @description Прислали -> применить; null/отсутствует -> оставить как есть. Сегодня форма шлёт
             *     константу 0 и сбрасывает порядок карточек на /pricing.
             */
            sortOrder?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** @description ТОЛЬКО поля AdminPlanDto, которые нужны блоку D. Новых полей цикл не добавляет. */
        AdminPlanCycle15Fields: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description false = «Архивный»: назначить нельзя никому. */
            isActive: boolean;
            /**
             * @description Читает РОВНО ОДНО место продукта — публичная витрина GET /api/pricing. Назначение
             *     подписки в админке фильтрует по isActive, поэтому скрытый тариф остаётся видимым
             *     администратору и продлеваемым.
             */
            isPublic: boolean;
            /** @description Системный бесплатный тариф; убрать его с витрины нельзя (409). */
            isSystemFree: boolean;
            sortOrder: number;
        } & {
            [key: string]: unknown;
        };
        /** @description Форма прежняя. Для BookingNotice меняется содержимое contentHtml и version. */
        LegalUiText: {
            /** @example BookingNotice */
            key: string;
            /** @example 2026-09-25 */
            version: string;
            isDraft: boolean;
            /**
             * @description HTML документа. В «Короткой строке» BookingNotice появляется разметка времени показа
             *     (data-legal-when / data-legal-value / data-legal-unless, имя значения companyName) и
             *     исчезает мёртвый <span>Подробнее</span>.
             * @example <h2>Короткая строка (видна всегда)</h2>
             *     <p>Записываясь, вы передаёте имя и номер телефона
             *     <span data-legal-when="companyName">компании «<span data-legal-value="companyName"></span>»</span><span
             *      data-legal-unless="companyName">компании, в которую вы записываетесь,</span>
             *     и {{НАИМЕНОВАНИЕ_ОПЕРАТОРА}} — это нужно, чтобы запись состоялась.
             *     <a href="/privacy">Как мы обращаемся с данными</a> · <a href="/terms">Условия</a></p>
             */
            contentHtml: string;
        };
    };
    responses: {
        /**
         * @description Нарушено правило. Тело — ГОЛАЯ СТРОКА для показа пользователю рядом с полем,
         *     которое её вызвало.
         */
        PlainTextBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Превышен лимит именованной политики; тело — голая строка */
        PlainTextTooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
