/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/companies/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Публичный каталог компаний (US-115)
         * @description АНОНИМНЫЙ. Заменяет для главной страницы GET /api/companies, который ОСТАЁТСЯ и НЕ МЕНЯЕТСЯ.
         *
         *     Фильтрация по городу, поиск по названию/адресу и ограничение объёма считаются НА СЕРВЕРЕ, в SQL.
         *     Скачивание всего списка с последующей фильтрацией в браузере считается регрессом (SPEC §5, §6).
         *
         *     Правила видимости НЕ МЕНЯЮТСЯ: компания попадает в выдачу при isActive И showInPublicListing
         *     И allowPublicListing действующего тарифа. Город видимости не добавляет и не отнимает.
         *     Компания без города (cityId = null) попадает ТОЛЬКО во «Все города».
         *
         *     Несуществующий cityId даёт ПУСТУЮ СТРАНИЦУ, а не 404: публичный каталог не подтверждает
         *     существование справочных записей.
         */
        get: operations["getPublicCompanies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification-channels/offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Что предлагается владельцу (расширено полем transports)
         * @description ИЗМЕНЕНО АДДИТИВНО: добавлен массив transports[].
         *
         *     ⚠️ riskText/riskVersion теперь берутся из документа ChannelRiskNotice (LegalDocumentProvider),
         *     а не из константы Services/NotificationRiskText.cs, которая УДАЛЯЕТСЯ (ARCHITECTURE_CYCLE9.md §104.8).
         *     Следствие: riskVersion изменит значение после выката, и владельцы принимают текст о рисках заново.
         */
        get: operations["getChannelOffer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification-channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Каналы владельца (в элементе появилось transport) */
        get: operations["listNotificationChannels"];
        put?: never;
        /**
         * Заявка на канал (US-119; добавлено необязательное transport)
         * @description АДДИТИВНО: поле transport необязательно, отсутствие означает "WhatsApp" — старый клиент
         *     продолжает работать без изменений.
         *
         *     409 означает «у аккаунта уже есть канал ЭТОГО транспорта в живом состоянии». Раньше это означало
         *     «уже есть канал вообще» — инвариант расширен транспортом (ARCHITECTURE_CYCLE9.md §104.3).
         */
        post: operations["requestNotificationChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification-channels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка канала (появилось transport) */
        get: operations["getNotificationChannel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification-channels/{id}/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Назначить компанию на канал
         * @description ИНВАРИАНТ ИЗМЕНИЛСЯ: компания может быть назначена максимум на ОДИН канал КАЖДОГО транспорта,
         *     а не на один канал вообще. Держится уникальным индексом (CompanyId, Transport), а не проверкой
         *     в контроллере. Подключение MAX не трогает и не отвязывает существующий WhatsApp-канал.
         */
        post: operations["assignCompanyToChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{companyId}/notification-settings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        /** Настройки уведомлений компании (добавлен режим доставки) */
        get: operations["getNotificationSettings"];
        /**
         * Сохранить настройки, включая режим доставки (US-125)
         * @description ⚠️ ЭТОТ МАРШРУТ БЫЛ И ОСТАЁТСЯ ТАРИФНО ГЕЙТЯЩИМСЯ (402 «Недоступно на вашем тарифе» /
         *     «Канал не оплачен»). Именно поэтому бесплатная настройка Web Push живёт в ОТДЕЛЬНОМ маршруте
         *     /companies/{companyId}/staff-push-settings (ARCHITECTURE_CYCLE9.md §105.4).
         *
         *     Режим применяется В МОМЕНТ ПОСТАНОВКИ В ОЧЕРЕДЬ: уже поставленные сообщения адресата не меняют.
         *     Отписка (NotificationOptOut) СИЛЬНЕЕ режима: отписавшийся номер не получает ничего ни в одном
         *     транспорте.
         */
        put: operations["updateNotificationSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{companyId}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Журнал доставки (добавлены поле transport и фильтр по нему)
         * @description В режиме AllChannels одно событие даёт НЕСКОЛЬКО строк — по одной на транспорт, с одинаковым
         *     bookingId и type. Владелец не должен решать, что клиента уведомили дважды по ошибке: экран
         *     группирует их по событию.
         */
        get: operations["getNotificationLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/notification-channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Админский список каналов (добавлены transport и фильтр по нему) */
        get: operations["adminListNotificationChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/provider-webhook/{transport}/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Вебхук статусов доставки, по транспорту (US-120)
         * @description АНОНИМНЫЙ, политика лимита notifications-webhook (600/мин на IP).
         *
         *     Существующий POST /api/notifications/provider-webhook/{token} ОСТАЁТСЯ и означает WhatsApp —
         *     он мог быть уже прописан в настройках экземпляра у провайдера.
         *
         *     Нераспознанный transport в пути → 404, а НЕ 400: маршрут не рассказывает, какие транспорты
         *     существуют. Нераспознанный формат тела НЕ роняет обработчик: 200 и одна строка лога Information.
         *
         *     Неверный/отсутствующий `{token}` → 401 (пустое тело, EmptyResult — НЕ ProblemDetails), тот же
         *     код и то же обоснование (API_CONTRACT_CYCLE4.md §19.2/33), что и у оригинального
         *     `POST /api/notifications/provider-webhook/{token}`: обработчик токена общий для обоих маршрутов.
         *     Редакция 1 этого документа объединяла «нераспознанный транспорт либо неверный токен» под одним
         *     404 — расхождение с реализацией и с цикла-4-прецедентом, исправлено здесь задним числом без
         *     изменения кода (см. отчёт backend-developer по проходу B, найдено schemathesis).
         *
         *     ⚠️ DEVOPS: этот маршрут содержит секрет в пути и ОБЯЗАН получить маскирование в access-логе nginx.
         */
        post: operations["providerWebhookByTransport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Конфигурация Web Push и состояние моих компаний (US-118)
         * @description Одним запросом отдаёт всё, что нужно фронту, чтобы решить: показывать ли тумблер подписки и что
         *     именно объяснить мастеру.
         *
         *     publicKey — ЕДИНСТВЕННЫЙ способ, которым VAPID-ключ попадает в браузер. Второй VITE_*-переменной
         *     не заводится, приватный ключ в клиентский бандл попасть не может.
         *
         *     enabled=false означает Notifications:StaffPush:Provider=logging — ШТАТНОЕ выключенное состояние
         *     (SPEC П13), а не сбой. Фронт объясняет это текстом и не предлагает подписку.
         *
         *     companies[].staffPushEnabled=false → разрешение у мастера НЕ ЗАПРАШИВАЕТСЯ ВОВСЕ (US-118).
         */
        get: operations["getPushConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Мои подписанные устройства (US-123)
         * @description Выборка ВСЕГДА по userId из токена — чужие подписки не видны ни при каких параметрах.
         *     ⚠️ Ключи подписки (p256dh, auth) не отдаются НИ В ОДНОМ DTO — ни мастеру, ни владельцу,
         *     ни суперадмину.
         */
        get: operations["listPushSubscriptions"];
        put?: never;
        /**
         * Подписать это устройство (US-123)
         * @description Владелец подписки берётся ИЗ ТОКЕНА — поля владельца в контракте нет вовсе, поэтому «создать
         *     чужую подписку» невозможно по форме запроса.
         *
         *     Поведение по endpoint:
         *       * новый endpoint                          → 201, создана;
         *       * тот же endpoint, тот же пользователь     → 200, обновлены ключи и метка, строка НЕ дублируется;
         *       * тот же endpoint, ДРУГОЙ пользователь     → 200, подписка ПЕРЕНАЗНАЧАЕТСЯ вызывающему.
         *         Это намеренно (ответ на Q16): общий компьютер в салоне — реальный сценарий, и «уведомления
         *         с именами клиентов приходят тому, кто зашёл до меня» недопустимо. 409 здесь был бы хуже.
         *
         *     Превышение потолка maxSubscriptionsPerUser не ошибка: подписка создаётся, а самая старая
         *     по createdAtUtc удаляется молча.
         *
         *     Политика лимита: push-subscribe, 20/час на пользователя.
         */
        post: operations["createPushSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscriptions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Отписать это устройство при выходе из аккаунта (US-123, Q16)
         * @description Идемпотентен: 204 даже если строки уже нет. Вызывается фронтом при logout ВМЕСТЕ с
         *     pushManager.getSubscription()?.unsubscribe() в браузере — «просто спрятали кнопку» приёмку
         *     не проходит.
         */
        delete: operations["deleteCurrentPushSubscription"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Отключить любое моё устройство (US-123)
         * @description Позволяет отключить устройство, с которого вы НЕ зашли, — сценарий «забыл выйти на компьютере
         *     в салоне». Чужая подписка даёт 404, а НЕ 403: существование чужой строки не подтверждается.
         */
        delete: operations["deletePushSubscription"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{companyId}/staff-push-settings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        /**
         * Уведомлять ли сотрудников о новых записях (US-117)
         * @description ⚠️ ТАРИФОМ НЕ ГЕЙТИТСЯ и канала у провайдера НЕ ТРЕБУЕТ (SPEC П6). 402 этот маршрут не отдаёт
         *     никогда — в отличие от /notification-settings, который сегодня отвечает 402 всем владельцам,
         *     потому что AllowNotificationChannel выключен у всех тарифов.
         *
         *     По умолчанию true — включая компании, созданные до цикла, и компании без строки настроек.
         *     Backfill не требуется (колонка с DB-дефолтом + правило «нет строки = дефолты»).
         */
        get: operations["getStaffPushSettings"];
        /**
         * Включить или выключить уведомления сотрудникам (US-117)
         * @description Доступно владельцу компании и суперадмину; мастеру — 403 (явный Forbid, а не пустое значение).
         *
         *     Выключение ГАСИТ ДОСТАВКУ, НО НЕ УДАЛЯЕТ подписки мастеров. Включили обратно — уведомления
         *     возобновились без перелогина и без повторной подписки.
         */
        put: operations["updateStaffPushSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description APPEND-ONLY. Участвует в данных и в уникальном индексе (CompanyId, Transport).
         *     Новый член добавляется ТОЛЬКО в конец.
         * @enum {string}
         */
        NotificationTransport: "WhatsApp" | "Max";
        /**
         * @description PriorityChannel — сообщение уходит ТОЛЬКО в приоритетный транспорт; если он не в рабочем
         *     состоянии, отправки НЕТ (фолбэка в цикле нет, SPEC §3).
         *     AllChannels — по одной отправке на каждый подключённый и живой транспорт.
         *     Дефолт — PriorityChannel с priorityTransport=WhatsApp: поведение существующих компаний
         *     не меняется вообще, backfill не нужен.
         * @enum {string}
         */
        NotificationDeliveryMode: "PriorityChannel" | "AllChannels";
        /** @enum {string} */
        NotificationStatus: "Pending" | "Sent" | "Delivered" | "Failed" | "Expired" | "Skipped" | "Cancelled";
        /** @enum {string} */
        NotificationType: "BookingConfirmed" | "Reminder" | "BookingCancelled" | "BookingRescheduled" | "StaffBookingCreated" | "StaffBookingCancelled";
        /**
         * @description APPEND-ONLY. Машиночитаемый код; РУССКИЙ ТЕКСТ СОБИРАЕТ СЕРВЕР (NotificationTexts) и отдаёт
         *     отдельным полем reasonText. Фронт текст не сочиняет и не собирает из кусочков.
         * @enum {string}
         */
        NotificationReason: "Delivered" | "RecipientHasNoWhatsApp" | "RejectedByProvider" | "RetriesExhausted" | "VisitAlreadyStarted" | "RecipientOptedOut" | "NotOnPaidPlan" | "NoUsableChannel" | "TypeDisabledByCompany" | "BelowMinimumLeadTime" | "BookingOrAssignmentCancelled" | "RecipientNotInMax" | "PriorityChannelUnavailable" | "PushSubscriptionGone" | "PushAuthRejected" | "PushPayloadTooLarge" | "PushTtlExhausted" | "StaffPushDisabledByCompany" | "MasterNoLongerInCompany";
        /** @enum {string} */
        ChannelState: "NotConnected" | "Connecting" | "Connected" | "Disconnected" | "Blocked" | "DisabledByOwner" | "NeedsReconnect" | "Replaced";
        /** @enum {string} */
        LegalEntityForm: "Ip" | "Company" | "SelfEmployed";
        PagedCompanyDto: {
            items: components["schemas"]["CompanyDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            total: number;
            hasNext: boolean;
        };
        PagedNotificationLogItemDto: {
            items: components["schemas"]["NotificationLogItemDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            total: number;
            hasNext: boolean;
        };
        PagedAdminChannelDto: {
            items: components["schemas"]["AdminChannelDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            total: number;
            hasNext: boolean;
        };
        /**
         * @description ТОТ ЖЕ DTO, что отдаёт GET /api/companies, собранный тем же маппером. Второго DTO и второго
         *     маппера цикл 9 не заводит.
         *
         *     В публичном вызове employeeCount = 0, а accountSeatsUsed / accountSeatsLimit / canAddEmployee = null:
         *     публичный каталог НЕ считает использование аккаунта (это стоило бы лишних запросов на самом
         *     горячем анонимном списке сайта).
         */
        CompanyDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string | null;
            logoUrl?: string | null;
            address?: string | null;
            phone?: string | null;
            email?: string | null;
            allowSelfBooking: boolean;
            requirePrepayment: boolean;
            onlineBookingEnabled: boolean;
            allowAnalytics: boolean;
            allowMailing: boolean;
            showInPublicListing: boolean;
            publicListingEnabled: boolean;
            prepaymentEnabled: boolean;
            planAllowsOnlineBooking: boolean;
            planAllowsOnlinePayment: boolean;
            planAllowsPublicListing: boolean;
            /** Format: int32 */
            maxEmployees?: number | null;
            /** Format: int32 */
            employeeCount?: number;
            /** Format: int32 */
            accountSeatsUsed?: number | null;
            /** Format: int32 */
            accountSeatsLimit?: number | null;
            canAddEmployee?: boolean | null;
            /** Format: double */
            averageRating?: number | null;
            /** Format: int32 */
            reviewCount: number;
            /** Format: int32 */
            cityId?: number | null;
            cityName?: string | null;
            cityRegion?: string | null;
            timeZoneId: string;
            timeZoneIsManual: boolean;
            /** Format: int32 */
            utcOffsetMinutes: number;
            /** Format: int32 */
            bookingHorizonDays: number;
        };
        ChannelOfferDto: {
            /**
             * Format: double
             * @description null означает «опция не предлагается», а НЕ «бесплатно».
             */
            pricePerMonth?: number | null;
            allowedByPlan: boolean;
            /** @description ⚠️ Берётся из документа ChannelRiskNotice, а не из удаляемой константы NotificationRiskText. */
            riskText: string;
            /** @description ⚠️ Значение изменится после выката — владельцы принимают текст о рисках заново. */
            riskVersion: string;
            transports: components["schemas"]["TransportOfferDto"][];
        };
        TransportOfferDto: {
            transport: components["schemas"]["NotificationTransport"];
            /** @example MAX */
            displayName: string;
            available: boolean;
            /**
             * @description Ограничение провайдера, которое пользователь обязан узнать ДО привязки, а не после.
             *     Для MAX: «Для авторизации по QR нужно отключить пароль входа в мессенджере.»
             *     Текст собирает СЕРВЕР; фронт его печатает и не сочиняет.
             * @example Для авторизации по QR в MAX нужно отключить пароль входа в мессенджере.
             */
            connectionNotice?: string | null;
        };
        ChannelRequestInput: {
            /**
             * @description 🆕 Необязательное. Отсутствует → WhatsApp (аддитивность для старых клиентов).
             * @default WhatsApp
             */
            transport: components["schemas"]["NotificationTransport"];
            legalEntityForm: components["schemas"]["LegalEntityForm"];
            /** @description Проверяется только формальной контрольной суммой; против ЕГРЮЛ/ЕГРИП не сверяется. */
            inn: string;
            /**
             * @description D9 — приложение к TermsOwner (ARCHITECTURE_CYCLE5.md §43.2), поэтому версия сверяется против
             *     ЭТОГО документа, а не отдельного акцепта риска. Приём риска остаётся отдельным шагом —
             *     POST /notification-channels/{id}/accept-risk, ПОСЛЕ создания заявки, не в этом теле.
             */
            offerAccepted?: {
                version?: string | null;
            };
        };
        ChannelDto: {
            /** Format: uuid */
            id: string;
            /** @description 🆕 добавлено циклом 9, аддитивно. */
            transport: components["schemas"]["NotificationTransport"];
            state: components["schemas"]["ChannelState"];
            /** @description Русская формулировка, собранная СЕРВЕРОМ (ChannelPresentation). Фронт её печатает. */
            stateText: string;
            phoneMasked?: string | null;
            paymentState: components["schemas"]["ChannelPaymentStatus"];
            /**
             * Format: date-time
             * @description Устарело (ARCHITECTURE_CYCLE7.md §47.3): всегда null.
             */
            paidFrom?: string | null;
            /** Format: date-time */
            paidUntil?: string | null;
            /** Format: date-time */
            requestedAt?: string | null;
            /** Format: date-time */
            connectedAt?: string | null;
            /** Format: date-time */
            riskAcceptedAt?: string | null;
            /** Format: date-time */
            idleSince?: string | null;
            /** Format: date-time */
            idleDeadline?: string | null;
            /** Format: uuid */
            replacedByChannelId?: string | null;
            companies: {
                /** Format: uuid */
                companyId: string;
                companyName: string;
                isActive: boolean;
            }[];
            canConnect: boolean;
            canReplace: boolean;
            /** @enum {string} */
            fundingState: "Funded" | "Unfunded" | "NotPaid";
            fundingText: string;
            inn?: string | null;
            legalEntityForm?: (string & components["schemas"]["LegalEntityForm"]) | null;
        };
        /** @enum {string} */
        ChannelPaymentStatus: "Paid" | "NotPaid" | "Suspended";
        AdminChannelDto: {
            /** Format: uuid */
            id: string;
            /** @description 🆕 добавлено циклом 9; по нему же работает query-фильтр ?transport=. */
            transport: components["schemas"]["NotificationTransport"];
            state: components["schemas"]["ChannelState"];
            paymentState: components["schemas"]["ChannelPaymentStatus"];
            ownerName: string;
            ownerPhoneMasked?: string | null;
            /** Format: date-time */
            paidFrom?: string | null;
            /** Format: date-time */
            paidUntil?: string | null;
            /** Format: int32 */
            companyCount: number;
            /** Format: date-time */
            idleSince?: string | null;
            /** Format: date-time */
            requestedAt?: string | null;
            isSuspendedByAdmin: boolean;
            inn?: string | null;
            legalEntityForm?: (string & components["schemas"]["LegalEntityForm"]) | null;
        };
        NotificationSettingsDto: {
            enabledTypes: components["schemas"]["NotificationType"][];
            /** Format: int32 */
            reminderLeadMinutes: number;
            /** Format: int32 */
            minLeadMinutes: number;
            planAllowsChannel: boolean;
            /**
             * @description Канал ПРИОРИТЕТНОГО транспорта (priorityTransport), если он у компании подключён — этому
             *     полю (и effectiveEnabled/blockedReason рядом) больше 1 транспорта не нужно, оно осталось из
             *     цикла 4 для экранов, которые ещё не научились работать со списком транспортов.
             */
            channel: components["schemas"]["SettingsChannelDto"];
            effectiveEnabled: boolean;
            blockedReason?: string | null;
            /** @description 🆕 */
            deliveryMode: components["schemas"]["NotificationDeliveryMode"];
            /** @description 🆕 Имеет смысл только при deliveryMode=PriorityChannel. */
            priorityTransport: components["schemas"]["NotificationTransport"];
            /** @description 🆕 ТОЛЬКО ДЛЯ ЧТЕНИЯ — что реально подключено и живо. Если элемент один, режим ни на что не влияет, и экран обязан это объяснить. */
            connectedTransports: components["schemas"]["NotificationTransport"][];
            /**
             * @description 🆕 ТОЛЬКО ДЛЯ ЧТЕНИЯ. false → в кабинете владельца показывается плашка «приоритетный канал
             *     не работает: выберите другой или включите отправку во все». Автоподмены транспорта НЕТ.
             */
            priorityChannelHealthy: boolean;
        };
        SettingsChannelDto: {
            assigned: boolean;
            /** Format: uuid */
            channelId?: string | null;
            state?: (string & components["schemas"]["ChannelState"]) | null;
            stateText?: string | null;
            paymentState?: (string & components["schemas"]["ChannelPaymentStatus"]) | null;
            /** Format: date-time */
            paidUntil?: string | null;
        };
        UpdateNotificationSettingsInput: {
            enabledTypes: components["schemas"]["NotificationType"][];
            /** Format: int32 */
            reminderLeadMinutes: number;
            /** Format: int32 */
            minLeadMinutes: number;
            /** @description 🆕 Не прислали — не меняем. */
            deliveryMode?: components["schemas"]["NotificationDeliveryMode"];
            /** @description 🆕 Не прислали — не меняем. Значение вне connectedTransports → 400. */
            priorityTransport?: components["schemas"]["NotificationTransport"];
        };
        NotificationLogItemDto: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            type: components["schemas"]["NotificationType"];
            /** @description Русский текст, собранный СЕРВЕРОМ (NotificationTexts). */
            typeText: string;
            recipientName?: string | null;
            recipientPhoneMasked: string;
            status: components["schemas"]["NotificationStatus"];
            /**
             * @description Русский текст статуса/причины, собранный СЕРВЕРОМ (NotificationTexts.StatusText) — фронт его
             *     печатает, не собирает из отдельных полей status/reason.
             */
            statusText: string;
            /**
             * Format: uuid
             * @description В режиме AllChannels одно событие даёт несколько строк с ОДИНАКОВЫМ bookingId и type,
             *     различающихся transport. Экран группирует их по событию, чтобы владелец не решил,
             *     что клиента уведомили дважды по ошибке.
             */
            bookingId?: string | null;
            /** Format: date-time */
            visitStart: string;
            /** Format: date-time */
            sentAt?: string | null;
            /** Format: uuid */
            channelId?: string | null;
            /** @description 🆕 добавлено циклом 9; по нему же работает query-фильтр ?transport=. */
            transport: components["schemas"]["NotificationTransport"];
            /** @description ARCHITECTURE_CYCLE5.md §49.3 — текст затёрт правилом хранения. */
            contentRedacted: boolean;
        };
        PushConfigDto: {
            /**
             * @description false = Notifications:StaffPush:Provider=logging — ШТАТНОЕ выключенное состояние подсистемы
             *     (SPEC П13), а не сбой. Фронт объясняет это текстом и не предлагает подписку.
             */
            enabled: boolean;
            /**
             * @description VAPID public key, base64url. ЕДИНСТВЕННЫЙ способ, которым ключ попадает в браузер —
             *     второй VITE_*-переменной не заводится, приватный ключ в бандл попасть не может.
             *     null, когда enabled=false.
             */
            publicKey?: string | null;
            /**
             * Format: int32
             * @description Потолок подписок; при превышении самая старая вытесняется молча.
             * @example 10
             */
            maxSubscriptionsPerUser: number;
            /** @description Компании, где вызывающий — персонал. */
            companies: {
                /** Format: uuid */
                companyId: string;
                companyName: string;
                /** @description false → разрешение у мастера НЕ ЗАПРАШИВАЕТСЯ ВОВСЕ (US-118). */
                staffPushEnabled: boolean;
            }[];
        };
        PushSubscriptionListDto: {
            items: components["schemas"]["PushSubscriptionDto"][];
        };
        /**
         * @description ⚠️ Ключи подписки (p256dh, auth) НЕ ОТДАЮТСЯ НИ В ОДНОМ DTO — ни мастеру, ни владельцу,
         *     ни суперадмину. additionalProperties:false закрепляет это машинно.
         */
        PushSubscriptionDto: {
            /** Format: uuid */
            id: string;
            /**
             * @description Чтобы мастер понимал, что именно он отключает.
             * @example Chrome на Windows
             */
            deviceLabel: string;
            /** Format: date-time */
            createdAtUtc: string;
            /**
             * Format: date-time
             * @description По нему работает правило срока хранения (180 дней без успешной доставки).
             */
            lastSuccessAtUtc?: string | null;
            /** @description Считает СЕРВЕР, сравнивая с currentEndpoint из query. Без параметра — всегда false. */
            isCurrent: boolean;
        };
        /**
         * @description Поля владельца здесь НЕТ ВОВСЕ — владелец берётся из токена, поэтому «создать чужую подписку»
         *     невозможно по форме запроса (US-123).
         */
        CreatePushSubscriptionInput: {
            /**
             * Format: uri
             * @example https://fcm.googleapis.com/fcm/send/dQw4w9WgXcQ
             */
            endpoint: string;
            keys: {
                p256dh: string;
                auth: string;
            };
            deviceLabel?: string | null;
        };
        StaffPushSettingsDto: {
            /**
             * @description По умолчанию true — включая компании, созданные до цикла, и компании без строки настроек.
             *     Выключение ГАСИТ ДОСТАВКУ, НО НЕ УДАЛЯЕТ подписки мастеров.
             * @default true
             */
            staffPushEnabled: boolean;
        };
        /**
         * @description ⚠️ ЭТО НЕ HTTP-ОТВЕТ. Тело push-сообщения, зашифрованное по RFC 8291 и разбираемое
         *     service worker'ом (frontend/public/sw.js). Описано здесь, чтобы фронт и бэкенд сошлись
         *     по форме и здесь тоже.
         *
         *     ТЕЛЕФОНА КЛИЕНТА ЗДЕСЬ НЕТ и быть не должно (SPEC П8): уведомление рисует операционная система,
         *     в том числе на личном телефоне мастера и на заблокированном экране.
         *
         *     Заголовки запроса к push-сервису: TTL = min(3600, секунд до начала визита), Urgency: high,
         *     Topic: b-<bookingId>.
         */
        PushPayload: {
            /** @example Новая запись */
            title: string;
            /**
             * @description Услуга · дата и время · имя клиента. Без телефона.
             * @example Стрижка · 24.09 в 14:00 · Анна Петрова
             */
            body: string;
            /**
             * @description Схлопывает повторы по одному визиту.
             * @example b-3f1c2e44-0000-0000-0000-000000000000
             */
            tag: string;
            /**
             * @description ОТНОСИТЕЛЬНЫЙ путь; service worker сам добавляет origin. Абсолютный URL открыл бы дорогу
             *     к открытию произвольного адреса. Ведёт на экран записей мастера (маршрут `/my-bookings`).
             * @example /my-bookings?booking=3f1c2e44-0000-0000-0000-000000000000
             */
            url: string;
        };
    };
    responses: {
        /** @description Не аутентифицирован. Тело ПУСТОЕ. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Нет прав. Тело ПУСТОЕ. */
        ForbiddenEmpty: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Не найдено (или не принадлежит вызывающему). Тело пустое. */
        NotFoundEmpty: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Голая строка по-русски (text/plain), не ProblemDetails. */
        BadRequestText: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Голая строка по-русски (text/plain). */
        ConflictText: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /**
         * @description «Упёрлись в тариф». Голая строка по-русски.
         *     ⚠️ НИ ОДИН маршрут Web Push этого кода не возвращает.
         */
        PaymentRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Превышен именованный лимит. Тело пишет OnRejected. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /**
         * @description 451 Unavailable For Legal Reasons — требуется принять новую редакцию документов.
         *     Фронт обрабатывает отдельно; разлогинивать пользователя нельзя.
         */
        LegalGate: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        CompanyId: string;
        ChannelId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPublicCompanies: {
        parameters: {
            query?: {
                /**
                 * @description Не передан или пуст → «Все города». Нечисловое значение (например, cityId=abc) — 400
                 *     (автоматическая проверка модели [ApiController], тело — голая строка по правилам этого
                 *     файла, НЕ ProblemDetails): это ошибка формата запроса, а не значение фильтра, и отличается
                 *     от «несуществующий, но числовой cityId», который отдаёт пустую страницу, а не 400.
                 *
                 *     `minimum: 1` не отвергается 400-м: cityId=0 и отрицательные значения — числа, поэтому
                 *     проходят проверку модели и трактуются как «несуществующий, но числовой cityId» — пустая
                 *     страница, тем же приёмом, каким pageSize и search клампятся/поглощаются, а не отвергаются.
                 */
                cityId?: number;
                /**
                 * @description Подстрока по названию ИЛИ адресу, регистронезависимо. Комбинируется с cityId через «и».
                 *     Длиннее 200 символов — НЕ отвергается 400-м: обрезается сервером до 200 символов перед
                 *     поиском, тем же приёмом, каким pageSize клампится, а не отвергается.
                 *     Ограничение намеренно НЕ выражено через maxLength: этим ключевым словом строгий
                 *     потребитель схемы отверг бы запрос, который сервер принимает и обслуживает.
                 */
                search?: string;
                page?: number;
                /** @description Клампится к [1,100], а не отвергается 400-м. */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница каталога. Порядок — по name, затем по id (устойчивый). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedCompanyDto"];
                };
            };
            400: components["responses"]["BadRequestText"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getChannelOffer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Предложение. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelOfferDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            451: components["responses"]["LegalGate"];
        };
    };
    listNotificationChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Список каналов, ЗАВЁРНУТЫЙ в объект — не голый массив.
             *     Реализация отдаёт ChannelListDto ({ channels: [...] }), и фронт читает именно её;
             *     схема раньше объявляла массив, что расходилось с обеими сторонами.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        channels: components["schemas"]["ChannelDto"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            451: components["responses"]["LegalGate"];
        };
    };
    requestNotificationChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelRequestInput"];
            };
        };
        responses: {
            /** @description Заявка принята. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelDto"];
                };
            };
            400: components["responses"]["BadRequestText"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            409: components["responses"]["ConflictText"];
            451: components["responses"]["LegalGate"];
        };
    };
    getNotificationChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Канал. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFoundEmpty"];
            451: components["responses"]["LegalGate"];
        };
    };
    assignCompanyToChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    companyId: string;
                };
            };
        };
        responses: {
            /** @description Назначено. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelDto"];
                };
            };
            400: components["responses"]["BadRequestText"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["ForbiddenEmpty"];
            404: components["responses"]["NotFoundEmpty"];
            /** @description Компания уже назначена на другой канал ТОГО ЖЕ транспорта. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            451: components["responses"]["LegalGate"];
        };
    };
    getNotificationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Настройки. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettingsDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["ForbiddenEmpty"];
            404: components["responses"]["NotFoundEmpty"];
            451: components["responses"]["LegalGate"];
        };
    };
    updateNotificationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotificationSettingsInput"];
            };
        };
        responses: {
            /** @description Сохранено. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettingsDto"];
                };
            };
            /**
             * @description Голая строка по-русски. Причины цикла 9: priorityTransport не входит в connectedTransports;
             *     нераспознанное значение deliveryMode/priorityTransport. Прежние причины без изменений.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["ForbiddenEmpty"];
            404: components["responses"]["NotFoundEmpty"];
            451: components["responses"]["LegalGate"];
        };
    };
    getNotificationLog: {
        parameters: {
            query?: {
                transport?: components["schemas"]["NotificationTransport"];
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                companyId: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница журнала. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedNotificationLogItemDto"];
                };
            };
            /**
             * @description Нераспознанное значение `?transport=` — автоматическая проверка модели `[ApiController]`,
             *     голая строка по-русски (та же форма, что и у остальных 400 в этом документе).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["ForbiddenEmpty"];
            /** @description Компании с таким companyId нет. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            451: components["responses"]["LegalGate"];
        };
    };
    adminListNotificationChannels: {
        parameters: {
            query?: {
                transport?: components["schemas"]["NotificationTransport"];
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница списка. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedAdminChannelDto"];
                };
            };
            /**
             * @description Нераспознанное значение `?transport=` — автоматическая проверка модели `[ApiController]`,
             *     голая строка по-русски (та же форма, что и у остальных 400 в этом документе).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["ForbiddenEmpty"];
        };
    };
    providerWebhookByTransport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Регистронезависимо. */
                transport: "whatsapp" | "max";
                token: string;
            };
            cookie?: never;
        };
        /** @description Форма зависит от провайдера и транспорта; сервер разбирает её своим парсером. */
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Принято (в том числе если формат не распознан). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Неверный или отсутствующий токен. Тело ПУСТОЕ (EmptyResult, не ProblemDetails). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нераспознанный `{transport}` в пути (не `whatsapp`/`max`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getPushConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Конфигурация. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushConfigDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            451: components["responses"]["LegalGate"];
        };
    };
    listPushSubscriptions: {
        parameters: {
            query?: {
                /** @description Endpoint устройства, с которого пришёл запрос — сервер помечает его isCurrent. Без параметра isCurrent всегда false. */
                currentEndpoint?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список устройств. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscriptionListDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            451: components["responses"]["LegalGate"];
        };
    };
    createPushSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePushSubscriptionInput"];
            };
        };
        responses: {
            /** @description Существующая подписка обновлена либо переназначена вызывающему. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscriptionDto"];
                };
            };
            /** @description Подписка создана. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscriptionDto"];
                };
            };
            /** @description Пустой или слишком длинный endpoint, не-URL, пустые ключи. Голая строка по-русски. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Подсистема выключена на платформе (GET /push/config → enabled=false). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            429: components["responses"]["TooManyRequests"];
            451: components["responses"]["LegalGate"];
        };
    };
    deleteCurrentPushSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    endpoint: string;
                };
            };
        };
        responses: {
            /** @description Подписки этого устройства у вызывающего больше нет. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequestText"];
            401: components["responses"]["Unauthorized"];
            451: components["responses"]["LegalGate"];
        };
    };
    deletePushSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалена. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFoundEmpty"];
            451: components["responses"]["LegalGate"];
        };
    };
    getStaffPushSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Настройка. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffPushSettingsDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["ForbiddenEmpty"];
            404: components["responses"]["NotFoundEmpty"];
            451: components["responses"]["LegalGate"];
        };
    };
    updateStaffPushSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffPushSettingsDto"];
            };
        };
        responses: {
            /** @description Сохранено. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffPushSettingsDto"];
                };
            };
            400: components["responses"]["BadRequestText"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["ForbiddenEmpty"];
            404: components["responses"]["NotFoundEmpty"];
            451: components["responses"]["LegalGate"];
        };
    };
}
