/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/companies/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Компании, где вызывающий — владелец (кабинет ezbook читает отсюда настройки салона)
         * @description Без изменений. Без параметра kind — только салоны (Services), только активные, только членство CompanyOwner.
         *     Вкладка «Настройки» находит салон по id в этом списке (ключ кеша ['my-companies']).
         */
        get: operations["getMyCompaniesCycle32"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id компании (салона или магазина). */
                id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Частичное обновление компании — профиль ИЛИ правила записи, никогда вместе
         * @description Без изменений на сервере. Отсутствующее поле (или null для plain-полей) не меняется. Любой 400 — до сохранения:
         *     ничего из тела не записывается. Порядок 400 (первый отказ выигрывает): горизонт → Яндекс → 2ГИС → окно переноса
         *     → «Город не найден» → «Неизвестный часовой пояс». Для магазина — ещё правила цикла 26 (409 при смене пояса с
         *     заказами, 400 при ручном поясе). Права: 404 для несуществующего id, 403 для чужой компании.
         */
        put: operations["updateCompanyCycle32"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}/address": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id компании (салона или магазина). */
                id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Адрес компании — второй шаг сохранения профиля, только после успешного PUT профиля
         * @description Без изменений (цикл 19). Кабинет шлёт { address } после подтверждения PublicAddressNotice
         *     (POST /api/companies/address/notice — API_CONTRACT_CYCLE19.md, без изменений). Политика частоты address-verify.
         */
        put: operations["saveCompanyAddressCycle32"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}/logo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id компании (салона или магазина). */
                id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Логотип — сразу при выборе файла, отдельно от кнопки «Сохранить»
         * @description Без изменений (порядок проверок — API_CONTRACT_CYCLE29.md). Политика частоты uploads.
         */
        post: operations["uploadCompanyLogoCycle32"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        CompanyKind: "Services" | "Orders";
        /**
         * @description Тело, которое шлёт общий блок «Профиль компании» (CompanyProfileCard) — салон и магазин.
         *     name, description, phone, email — всегда (значения формы; name и description обрезаны по краям).
         *     cityId — только если город сменили. timeZoneId — только салон и только если меняли ручной пояс.
         *     yandexMapsUrl / twoGisUrl — только изменённые; очищенная ссылка уходит как "".
         *     Адреса, полей правил и showInPublicListing здесь нет и быть не может.
         */
        CompanyProfileUpdateInput: {
            name: string;
            description: string;
            /**
             * @description Нетронутое поле — сохранённое значение как есть (любой формат, в том числе с «доб.»); изменённое — канонические
             *     11 цифр 7XXXXXXXXXX (маска PhoneInput); пустое поле — "". Сервер не нормализует.
             */
            phone: string;
            email: string;
            cityId?: number;
            /** @description Только салон. IANA-пояс — ручной пояс; null — сбросить к поясу города. Магазин ключ не шлёт. */
            timeZoneId?: string | null;
            /** @description "" — удалить ссылку. */
            yandexMapsUrl?: string;
            /** @description "" — удалить ссылку. */
            twoGisUrl?: string;
        };
        /**
         * @description Тело карточки «Правила записи» (только салон). bookingHorizonDays — всегда (0 — «по умолчанию, 90 дней»).
         *     clientRescheduleMinHours — только если поле не пустое. allowSelfBooking / requirePrepayment — только если флаг не
         *     заблокирован тарифом (planAllowsOnlineBooking / planAllowsOnlinePayment).
         */
        BookingRulesUpdateInput: {
            bookingHorizonDays: number;
            clientRescheduleMinHours?: number;
            allowSelfBooking?: boolean;
            requirePrepayment?: boolean;
        };
        SaveCompanyAddressInput: {
            /** @description Пишется байт в байт; "" — очистить. */
            address: string;
            /** @description Принимается и игнорируется (цикл 19). Кабинет не шлёт. */
            verify?: boolean | null;
        };
        MultipartImageUpload: {
            /**
             * Format: binary
             * @description JPEG, PNG или WEBP, до 5 МБ.
             */
            file: string;
        };
        /**
         * @description Подмножество CompanyDto, которое читает вкладка «Настройки» салона (полная форма — API_DOCUMENTATION.md).
         *     Та же форма у GET /api/companies/my (элемент массива), PUT /api/companies/{id}, POST …/logo и в поле company
         *     ответа PUT …/address. Кабинет ответы PUT не читает: после успеха перечитывает ['my-companies'].
         *     utcOffsetMinutes — смещение ДЕЙСТВУЮЩЕГО пояса (в том числе ручного), не пояса города. Пояса самого города
         *     при ручном поясе в DTO нет (ARCHITECTURE_CYCLE32.md §32.3).
         */
        CompanySettingsDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string | null;
            logoUrl?: string | null;
            address?: string | null;
            /** @description Как сохранено, байт в байт. */
            phone?: string | null;
            email?: string | null;
            allowSelfBooking: boolean;
            requirePrepayment: boolean;
            onlineBookingEnabled: boolean;
            showInPublicListing: boolean;
            planAllowsOnlineBooking: boolean;
            planAllowsOnlinePayment: boolean;
            cityId?: number | null;
            cityName?: string | null;
            cityRegion?: string | null;
            timeZoneId: string;
            timeZoneIsManual: boolean;
            utcOffsetMinutes: number;
            /** @description Уже нормализовано: 0 в БД → 90. */
            bookingHorizonDays: number;
            clientRescheduleMinHours: number;
            yandexMapsUrl?: string | null;
            twoGisUrl?: string | null;
            kind: components["schemas"]["CompanyKind"];
            publicUrl: string;
        } & {
            [key: string]: unknown;
        };
        CompanySettingsList: components["schemas"]["CompanySettingsDto"][];
        CompanyAddressUpdateResultDto: {
            company: components["schemas"]["CompanySettingsDto"];
        };
    };
    responses: {
        /** @description Осознанный отказ — голая строка по-русски. Тексты, по которым фронт выбирает поле, — API_CONTRACT_CYCLE32.md §32.26. */
        PlainTextError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description 409 маршрута /api/companies/* — голая строка по-русски (у салона на PUT профиля не бывает). */
        PlainTextConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Нет или недействителен токен. Тело пустое. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Не владелец и не SuperAdmin. Тело пустое. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Компании нет. Тело пустое. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Тело больше RequestSizeLimit (5 МБ). Тело пустое. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Требуется принять новую редакцию правовых документов владельца. */
        LegalGate: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Превышен лимит частоты — голая строка. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
    };
    parameters: {
        /** @description Id компании (салона или магазина). */
        CompanyId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMyCompaniesCycle32: {
        parameters: {
            query?: {
                /** @description Services (по умолчанию) или Orders. Кабинет ezbook не шлёт. */
                kind?: components["schemas"]["CompanyKind"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список компаний (CompanyDto). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySettingsList"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    updateCompanyCycle32: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id компании (салона или магазина). */
                id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyProfileUpdateInput"] | components["schemas"]["BookingRulesUpdateInput"];
            };
        };
        responses: {
            /** @description Компания после сохранения (CompanyDto). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySettingsDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["PlainTextConflict"];
            451: components["responses"]["LegalGate"];
        };
    };
    saveCompanyAddressCycle32: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id компании (салона или магазина). */
                id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveCompanyAddressInput"];
            };
        };
        responses: {
            /** @description Компания после сохранения. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyAddressUpdateResultDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    uploadCompanyLogoCycle32: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id компании (салона или магазина). */
                id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["MultipartImageUpload"];
            };
        };
        responses: {
            /** @description Логотип заменён; компания после сохранения (CompanyDto). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySettingsDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["TooManyRequests"];
            451: components["responses"]["LegalGate"];
        };
    };
}
