/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/legal/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Метаданные всего комплекта — пять документов и шесть текстов интерфейса
         * @description Публично. HTML не отдаётся — только метаданные, достаточные для футера, формы регистрации и
         *     сравнения версий. Для `PdnConsent` здесь же едет `purposes`: форма согласия строится из
         *     ответа, а не из захардкоженного массива на фронте.
         *
         *     Цикл 11 меняет в этом ответе ТОЛЬКО значения (`version`, `effectiveFrom`, два `title`).
         *     Количество элементов, набор `type` и набор `key` остаются прежними.
         */
        get: operations["getLegalManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/legal/documents/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Метаданные и HTML одного документа
         * @description Публично, `Cache-Control: public, max-age=300`. Неизвестный тип → 404, а не 500.
         *
         *     Страница документа доступна **без входа** — человек обязан иметь возможность прочитать то,
         *     что ему предлагают принять, до регистрации.
         */
        get: operations["getLegalDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/legal/texts/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Один текст интерфейса
         * @description Публично. Версионируется и хешируется как документ, но **гейт 451 не задействует**: claim'а
         *     под него нет, в `consent-status` он не появляется. Цикл 11 этого разделения не отменяет.
         */
        get: operations["getLegalText"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/legal/consent-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Что именно требуется от текущего пользователя
         * @description Требует авторизации, но входит в allow-list гейта 451 — иначе заблокированный вызывающий
         *     никогда не узнал бы, чем он заблокирован. Считается из claim'ов токена и снимка в памяти,
         *     **без запроса в БД**. Документы с `gate: None` в ответ не попадают.
         */
        get: operations["getConsentStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/legal/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Принять одну или несколько редакций
         * @description Принимается любое подмножество `{Privacy, TermsClient, TermsOwner}`. Версии сверяются с
         *     текущим снимком: 409, если оператор успел заменить текст ещё раз, пока человек читал.
         *     В ответ приходит **новый токен** — claim'ы версий зашиты в него при выпуске.
         *
         *     Цикл 11 здесь не меняет ничего, но именно этот путь получает всю нагрузку в момент
         *     публикации: замена комплекта — материальное изменение, и все существующие пользователи
         *     пройдут через него (`SPEC.md` цикла 11, риск R1, принят заказчиком).
         */
        post: operations["acceptLegal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/legal/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Что мешает публикации правового комплекта
         * @description **Новый эндпоинт цикла 11 (US-11-07).** Только чтение, ничего не меняет, безопасен на боевой
         *     машине. Отдаёт тот же JSON, что печатает `legal status --json`, плюс блок `impact`
         *     (сколько людей получат требование повторного акцепта) — у CLI его нет, потому что у CLI нет
         *     базы.
         *
         *     Внесён в allow-list гейта 451: суперадмин, которому самому прилетел 451 из-за смены
         *     редакции, обязан иметь возможность посмотреть, что происходит.
         *
         *     Поле `disclaimer` обязательно и непусто **всегда**, включая `ready: true`: «проверено
         *     механически» не равно «проверено юристом».
         */
        get: operations["getLegalReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/platform-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Платформенные настройки
         * @description Цикл 11 добавляет одно поле — `pricingPublicBlockedReason`. Добавление nullable-поля не
         *     является ломающим изменением: фронт, собранный до цикла, его просто не увидит.
         */
        get: operations["getPlatformSettings"];
        /**
         * Изменить платформенные настройки
         * @description **Новое поведение цикла 11 (US-11-04).** Попытка ВКЛЮЧИТЬ публичные цены — переход
         *     `pricingPublicEnabled` из `false` в `true` — пока оферта черновая, отклоняется с **409** и
         *     внятным объяснением, а не проходит молча. До цикла 11 запрет держался записью в спеке цикла 7
         *     и памятью суперадмина (`CURRENT_STATE.md` §9 B8) — именно это цикл и лечит.
         *
         *     409 проверяется только на этом переходе, не на любом запросе с `pricingPublicEnabled: true`.
         *     Если рубильник уже включён и `PUT` присылает `true` повторно (обычная ситуация: фронтенд шлёт
         *     текущее состояние тумблера вместе с остальными полями формы) — значение не меняется, и запрос
         *     **не отклоняется**, даже если оферта к этому моменту стала черновой. Строгая трактовка «любой
         *     `true` при черновой оферте — 409» заблокировала бы суперадмину сохранение
         *     `channelIdleDays`/`channelPricePerMonth` в той же форме, где тумблер уже включён и его никто не
         *     трогает.
         *
         *     Отказ целостный: рубильник не меняется, строка в журнале изменений настроек не пишется,
         *     **остальные поля запроса тоже не применяются**. Частично применённого PUT не бывает.
         *
         *     Выключение (`false`) разрешено всегда — запрет односторонний.
         */
        put: operations["updatePlatformSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pricing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Публичный каталог тарифов
         * @description Анонимно. Форма ответа 200 и заголовки — как в цикле 7 (`API_CONTRACT_CYCLE7.md` §38),
         *     схема тела здесь намеренно не переписана: источник истины по её форме —
         *     `contracts/cycle7/openapi.yaml`.
         *
         *     **Цикл 11 расширяет условие 404.** Теперь пустой 404 означает любое из трёх: рубильник
         *     выключен; оферта в статусе черновика; снимок правовых документов недоступен. Различать их
         *     анонимному вызывающему нельзя — наружу не должно быть видно, существует ли каталог вообще.
         *     Фронт трактует 404 как «витрина выключена» и ошибки не показывает.
         *
         *     Не видно в форме ответа, но важно: из каталога исключаются опции, чьё правовое условие не
         *     выполнено (`ARCHITECTURE_CYCLE11.md` §102.10). Сегодня это ровно одна опция —
         *     `notifications.whatsapp`.
         */
        get: operations["getPublicPricing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification-channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Заявка на подключение платного канала — она же акцепт оферты
         * @description **В цикле 11 не меняется ни на байт, и это принципиально.** `offerAccepted.version` равна
         *     версии `TermsOwner`, потому что оферта D9 — Приложение № 1 к нему, а не шестой тип документа
         *     (решение принято циклом 5 и реализовано; `ARCHITECTURE_CYCLE11.md` §102.2).
         *
         *     Факт принятия оферты уже пишется в журнал согласий: `DocumentKey = "TermsOwner"`,
         *     `Purpose = ChannelOffer`, с версией и хешем документа. Критерий US-11-04 «факт принятия
         *     фиксируется в журнале» выполнен до начала цикла — цикл закрывает то, чего нет: текста оферты
         *     в том файле, который читает приложение.
         */
        post: operations["createChannelRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Закрытый набор из пяти значений. Расширение требует правки перечисления в коде и ломает порядок деплоя (манифест обязан обновиться раньше кода) — цикл 11 его не расширяет.
         * @enum {string}
         */
        LegalDocumentType: "Privacy" | "TermsClient" | "TermsOwner" | "PdnConsent" | "ChannelRiskNotice";
        /**
         * @description Закрытый набор из шести строк. Добавление седьмого — правка манифеста, а не миграция.
         * @enum {string}
         */
        LegalTextKey: "BookingNotice" | "TemplateAdWarning" | "UnsubscribePage" | "PhotoConsent" | "HealthDataConsent" | "GuardianConfirmation";
        /**
         * @description Кого и где блокирует материальное изменение. Отсутствующее/нераспознанное значение в манифесте трактуется как Global — опечатка оператора обязана закрывать, а не открывать.
         * @enum {string}
         */
        LegalGate: "Global" | "OwnerScope" | "None";
        /** @enum {string} */
        LegalChangeKind: "Material" | "Editorial";
        LegalPurpose: {
            /** @enum {string} */
            key: "ProviderDelivery" | "WorkPhotos" | "HealthData";
            title: string;
        };
        LegalDocumentMeta: {
            type: components["schemas"]["LegalDocumentType"];
            title: string;
            /** @description Суффикс `-draft` обязателен, пока isDraft=true, и запрещён, когда false. По итогам цикла 11 у всего комплекта ожидается `-draft` — это ожидаемый результат, а не недоделка. */
            version: string;
            /** Format: date */
            effectiveFrom: string;
            isDraft: boolean;
            changeKind: components["schemas"]["LegalChangeKind"];
            gate: components["schemas"]["LegalGate"];
            /** @description Маршрут SPA. Источник истины — contracts/cycle11/legal-routes.json. */
            url: string;
            /** @description Только у PdnConsent. Форма согласия строится из этого списка. */
            purposes?: components["schemas"]["LegalPurpose"][] | null;
        };
        LegalUiTextMeta: {
            key: components["schemas"]["LegalTextKey"];
            version: string;
            isDraft: boolean;
        };
        LegalManifest: {
            documents: components["schemas"]["LegalDocumentMeta"][];
            uiTexts: components["schemas"]["LegalUiTextMeta"][];
        };
        LegalDocument: components["schemas"]["LegalDocumentMeta"] & {
            /**
             * @description HTML-фрагмент без <html>/<body>, без таблиц (читается с телефона). Для TermsOwner
             *     обязан содержать якорь id="offer-channel" — на него ведёт редирект /offer-channel,
             *     и без якоря человек попадает на страницу без оферты, которую ему предлагают принять.
             */
            contentHtml: string;
        };
        LegalUiText: {
            key: components["schemas"]["LegalTextKey"];
            version: string;
            isDraft: boolean;
            contentHtml: string;
        };
        ConsentStatusDocument: {
            type: components["schemas"]["LegalDocumentType"];
            currentVersion: string;
            /** @description null означает «никогда не принимал». Для OwnerScope это нормальный случай (обычный клиент), а не расхождение. */
            acceptedVersion?: string | null;
            changeKind: components["schemas"]["LegalChangeKind"];
            gate: components["schemas"]["LegalGate"];
        };
        ConsentStatus: {
            /** @description Глобальная блокировка — полноэкранный гейт. */
            requiresAcceptance: boolean;
            /** @description Владельческий гейт — модальное окно на перечисленных действиях, а не блокировка входа. */
            ownerActionBlocked: boolean;
            /** @description Только редакционное изменение. Material всегда побеждает Editorial. */
            showBanner: boolean;
            /** @description Только документы с gate != None. */
            documents: components["schemas"]["ConsentStatusDocument"][];
        };
        AcceptLegalItem: {
            type: components["schemas"]["LegalDocumentType"];
            version: string;
        };
        AcceptLegalRequest: {
            /** @description Любое подмножество {Privacy, TermsClient, TermsOwner}. Документ с gate=None здесь не принимается — 400. */
            accept: components["schemas"]["AcceptLegalItem"][];
        };
        AcceptLegalResponse: {
            /** @description Новый JWT. Обязателен, а не оптимизация: claim'ы версий зашиты при выпуске, и без нового токена следующий же запрос снова получит 451. */
            token: string;
            /** Format: date-time */
            acceptedAt: string;
        };
        /**
         * @description Почему рубильник публичных цен нельзя включить прямо сейчас. Поле информационное: оно не
         *     запрещает отправить PUT, оно объясняет заранее, чем PUT закончится. Единственный источник
         *     запрета — ответ 409.
         * @enum {string}
         */
        PricingPublicBlockedReason: "OfferIsDraft" | "LegalUnavailable";
        AdminPlatformSettings: {
            /** @description Наследие цикла 4; каналом теперь управляет опция подписки цикла 7. */
            channelPricePerMonth?: number | null;
            channelIdleDays: number;
            /** @description По умолчанию false. Включение возможно только при опубликованной оферте. */
            pricingPublicEnabled: boolean;
            /** @description НОВОЕ в цикле 11. null — препятствий нет. В запросе PUT игнорируется (поле только для чтения по смыслу). */
            pricingPublicBlockedReason?: components["schemas"]["PricingPublicBlockedReason"] | null;
        };
        /** @description Тело 409 при попытке включить публичные цены с черновой офертой. */
        PricingSwitchRefusal: {
            reason: components["schemas"]["PricingPublicBlockedReason"];
            /** @description Готовая формулировка для показа оператору. Фронт показывает её как есть и не переписывает — формулировка правовая, а не UX-ная. */
            message: string;
            /** @description Документ, из-за которого отказ. При reason=OfferIsDraft всегда TermsOwner. */
            documentType?: components["schemas"]["LegalDocumentType"] | null;
            /** @description Текущая редакция этого документа — чтобы в логе админки было видно, о какой именно версии шла речь. */
            version?: string | null;
        };
        CreateChannelRequest: {
            /** @enum {string} */
            legalEntityForm: "Ip" | "Company" | "SelfEmployed";
            /** @description 10 или 12 цифр. Нужен для счёта; виден владельцу и суперадмину. */
            inn: string;
            /**
             * @description Акцепт оферты D9. `version` — версия **TermsOwner**, а не отдельного документа: оферта
             *     является Приложением № 1 к нему. Несовпадение с текущей редакцией → 409.
             */
            offerAccepted: {
                version: string;
            };
        };
        blocker: {
            /**
             * @description UnresolvedPlaceholders — в тексте остались {{…}}; MissingValues — файла значений нет или в нём не все 12 ключей; DraftDocuments — isDraft=true (ожидаемое состояние по итогам цикла 11, а не дефект); BrokenLinks/MissingAnchors — внутренняя ссылка или якорь ведут в никуда; ArtifactDrift — App_Data/legal разошёлся с legal-drafts; LegalUnavailable — снимок вообще не загрузился.
             * @enum {string}
             */
            kind: "UnresolvedPlaceholders" | "MissingValues" | "DraftDocuments" | "BrokenLinks" | "MissingAnchors" | "ArtifactDrift" | "LegalUnavailable";
            detail: string;
        };
        placeholderHit: {
            name: string;
            count: number;
        };
        document: {
            /** @enum {string} */
            type: "Privacy" | "TermsClient" | "TermsOwner" | "PdnConsent" | "ChannelRiskNotice";
            title: string;
            version: string;
            /** Format: date */
            effectiveFrom: string;
            isDraft: boolean;
            /** @enum {string} */
            changeKind: "Material" | "Editorial";
            /**
             * @description Global — 451 на всех защищённых вызовах; OwnerScope — только на перечисленных действиях владельца; None — не блокирует нигде.
             * @enum {string}
             */
            gate: "Global" | "OwnerScope" | "None";
            file: string;
            /** @description Маршрут SPA из contracts/cycle11/legal-routes.json. */
            url: string;
            /** @description SHA-256 отданного HTML в нижнем регистре — ровно то значение, которое попадёт в ConsentRecord.DocumentHash при акцепте. */
            contentHash: string;
            placeholders: components["schemas"]["placeholderHit"][];
        };
        uiText: {
            /** @enum {string} */
            key: "BookingNotice" | "TemplateAdWarning" | "UnsubscribePage" | "PhotoConsent" | "HealthDataConsent" | "GuardianConfirmation";
            version: string;
            isDraft: boolean;
            file: string;
            contentHash: string;
            placeholders: components["schemas"]["placeholderHit"][];
        };
        placeholderSummary: {
            name: string;
            /** @description Число вхождений во всём комплекте. */
            count: number;
            /**
             * @description Группировка дословно из LEGAL_REVIEW.md §13-бис — по ней заказчик собирает значения. Переформулировать нельзя: это тот же текст, который уходит заказчику письмом.
             * @enum {string}
             */
            source: "из реквизитов оператора" | "после уведомления РКН" | "решение заказчика" | "из манифеста";
            files: string[];
            /** @description Есть ли непустое значение в legal.values.json. Без --values всегда false: отсутствие файла значений — это отсутствие значений, а не неизвестность. */
            valuePresent: boolean;
            /** @description true для НОМЕР_УВЕДОМЛЕНИЯ_РКН и ДАТА_УВЕДОМЛЕНИЯ_РКН (contracts/cycle11/legal-values.schema.json — эти два ключа не входят в required этого файла). Отсутствие значения у optional=true плейсхолдера НЕ порождает блокер MissingValues и не мешает publish: соответствующий элемент документа при публикации будет исключён целиком. Эта строка — способ увидеть тот факт заранее, до публикации, а не узнать о нём постфактум по опубликованному тексту. */
            optional: boolean;
        };
        links: {
            checked: number;
            broken: {
                file: string;
                href: string;
            }[];
        };
        anchors: {
            /** @description Обязательные якоря (legal-routes.json → anchors), которых нет в отданном HTML. Сегодня здесь ожидаемо лежит offer-channel в terms-owner.html. */
            missing: {
                route: string;
                anchor: string;
            }[];
        };
        /** @description Расхождение между тем, что читает приложение, и эталоном. Закрывает риск R7 SPEC: оператор правит текст на машине, репозиторий этого не видит. */
        drift: {
            comparedWith: string;
            differentFiles: string[];
        };
        /** @description Только у GET /api/admin/legal/readiness — у CLI нет базы. Что произойдёт с людьми, если опубликовать прямо сейчас. */
        impact: {
            reAcceptanceRequired: {
                /** @enum {string} */
                documentType: "Privacy" | "TermsClient" | "TermsOwner";
                /** @enum {string} */
                gate: "Global" | "OwnerScope";
                users: number;
            }[];
            note: string;
        };
        /**
         * Отчёт готовности правового комплекта к публикации
         * @description ОДИН формат на двоих (API_CONTRACT_CYCLE11.md §116, §117): его печатает `legal status --json` и его же отдаёт GET /api/admin/legal/readiness. Разница ровно одна — блок `impact` есть только у эндпоинта (у CLI нет базы). Файл намеренно написан в подмножестве, валидном И как JSON Schema draft-07 (ajv), И как Schema Object OpenAPI 3.0: нет `$defs`, `const`, `type: [..., null]`. Ни одно поле не может быть null — отсутствие выражается отсутствием ключа.
         */
        "legal-status.schema": {
            /**
             * Format: date-time
             * @description Момент снятия отчёта. Отчёт — снимок, а не состояние: через минуту оператор может подложить другой файл.
             */
            generatedAtUtc: string;
            /** @description Каталог, по которому отчёт снят. У эндпоинта это фактический Legal:Root приложения — то есть ответ на вопрос «а что читает продукт ПРЯМО СЕЙЧАС», а не «что лежит в репозитории». */
            root: string;
            /** @description Можно ли публиковать. true не означает «можно публиковать без юриста» — см. disclaimer, он обязателен и при ready=true. */
            ready: boolean;
            /** @description Почему нельзя публиковать. Пусто тогда и только тогда, когда ready=true. */
            blockers: components["schemas"]["blocker"][];
            /** @description Пять версионируемых документов (LegalDocumentType). Набор закрыт, шестого типа нет — оферта D9 является приложением к TermsOwner. */
            documents: components["schemas"]["document"][];
            /** @description Шесть текстов интерфейса (LegalTextKey). Версионируются и хешируются наравне с документами, но не участвуют в гейте 451 — поэтому отдельным списком, а не вперемешку. */
            uiTexts: components["schemas"]["uiText"][];
            /** @description Сводка по всему комплекту: какие плейсхолдеры не закрыты, сколько их и откуда брать значение. */
            placeholders: components["schemas"]["placeholderSummary"][];
            links: components["schemas"]["links"];
            anchors: components["schemas"]["anchors"];
            drift?: components["schemas"]["drift"];
            impact?: components["schemas"]["impact"];
            /** @description ОБЯЗАТЕЛЕН и непуст всегда, включая ready=true. Дословно фиксирует границу проверки: механическая проверка ловит незаполненные плейсхолдеры, битые ссылки и неполный комплект, но НЕ ловит неверный по сути текст. Публикация требует и механического, и юридического подтверждения (SPEC цикла 11, риск R3). */
            disclaimer: string;
        };
    };
    responses: {
        /**
         * @description Снимок правовых документов не загружен. Тело — строка на русском. Это НЕ «нет документа»:
         *     загрузчик никогда не очищает прошлый удачный снимок, поэтому 503 здесь означает, что
         *     удачного снимка не было ни разу с момента старта.
         */
        LegalUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Ошибка; тело — строка на русском (не объект) */
        PlainTextError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLegalManifest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Комплект */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalManifest"];
                };
            };
            503: components["responses"]["LegalUnavailable"];
        };
    };
    getLegalDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Регистронезависимо. Набор закрыт пятью значениями; шестого типа в цикле 11 не появляется — оферта D9 является приложением к `TermsOwner`. */
                type: components["schemas"]["LegalDocumentType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Документ */
            200: {
                headers: {
                    /** @description public, max-age=300 */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalDocument"];
                };
            };
            /** @description Неизвестный тип документа */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["LegalUnavailable"];
        };
    };
    getLegalText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["schemas"]["LegalTextKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Текст */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalUiText"];
                };
            };
            /** @description Неизвестный ключ */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["LegalUnavailable"];
        };
    };
    getConsentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Статус */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentStatus"];
                };
            };
            /** @description Нет токена */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acceptLegal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptLegalRequest"];
            };
        };
        responses: {
            /** @description Принято, выдан новый токен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptLegalResponse"];
                };
            };
            400: components["responses"]["PlainTextError"];
            /** @description Нет токена */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["PlainTextError"];
            503: components["responses"]["LegalUnavailable"];
        };
    };
    getLegalReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Отчёт готовности */
            200: {
                headers: {
                    /** @description no-store — это диагностика, а не контент */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["legal-status.schema"];
                };
            };
            /** @description Нет токена */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не SuperAdmin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Снимок правовых документов не загружен. Тело — тот же отчёт с `ready: false` и блокером
             *     `LegalUnavailable`, а не пустота: «не могу ответить» здесь бесполезнее, чем «вот что
             *     сломано».
             */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["legal-status.schema"];
                };
            };
        };
    };
    getPlatformSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Настройки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPlatformSettings"];
                };
            };
            /** @description Нет токена */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не SuperAdmin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePlatformSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminPlatformSettings"];
            };
        };
        responses: {
            /** @description Применено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPlatformSettings"];
                };
            };
            /**
             * @description Валидация цикла 7: `channelIdleDays` вне 0…60 или отрицательная цена. Проверяется **до**
             *     правовой проверки.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Нет токена */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не SuperAdmin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Включение публичных цен отклонено по правовому условию */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingSwitchRefusal"];
                };
            };
        };
    };
    getPublicPricing: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Каталог */
            200: {
                headers: {
                    ETag?: string;
                    /** @description public, max-age=60 */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Не изменилось */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Витрина недоступна — выключена рубильником, либо оферта черновая, либо правовой снимок не загружен. Тело пустое всегда. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createChannelRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChannelRequest"];
            };
        };
        responses: {
            /** @description Заявка создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["PlainTextError"];
            /** @description Нет токена */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Тариф не позволяет подключение канала */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Вызывающий не владеет ни одной компанией */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Соглашение владельца обновилось ещё раз — принятая версия устарела */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Владельческий гейт — соглашение с компанией не принято */
            451: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["LegalUnavailable"];
        };
    };
}
