/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/phone-verification/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Состояние подсистемы подтверждения (US-12-08)
         * @description АНОНИМНЫЙ. Единственный источник ответа на вопрос «показывать ли кнопку» — один и тот же
         *     для формы регистрации, профиля и экрана смены номера (Q5). Образец — GET /push/config.
         *
         *     Действие «Подтвердить номер через MAX» показывается ТОЛЬКО при enabled && healthy.
         *     При enabled=false не показывается НИЧЕГО: ни кнопки, ни объяснения, ни пустого места.
         */
        get: operations["getPhoneVerificationConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/phone-verification/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Начать подтверждение — получить одноразовую ссылку и QR (US-12-01, US-12-02)
         * @description Анонимно (сценарий регистрации) ИЛИ с токеном (сценарий профиля, US-12-16). Механизм один
         *     и тот же; авторизованный вызов может не присылать phone — берётся текущий номер аккаунта.
         *
         *     Политика лимитов phone-verify-start: 10/час на пользователя, для анонимных — на IP (Q8, R10).
         *
         *     НИ ОДНОГО исходящего вызова к MAX в этом запросе не делается: бот узнаёт о сессии только
         *     когда пользователь сам его откроет по ссылке (О2 — бот не может написать первым).
         *
         *     statusToken отдаётся ЕДИНОЖДЫ; на сервере хранится только его SHA-256.
         */
        post: operations["startPhoneVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/phone-verification/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Опрос статуса сессии (Q12, П9 — результат без перезагрузки страницы)
         * @description Поллинг раз в pollIntervalSeconds, пока статус Pending|Linked и не истёк expiresAtUtc.
         *     Отдельной политикой лимитов НЕ покрыт намеренно (это штатный поллинг фронта).
         *
         *     404 отдаётся и на неизвестный sessionId, и на неподходящий statusToken — различать эти
         *     случаи контракт не позволяет намеренно (иначе эндпоинт станет оракулом существования сессий).
         */
        get: operations["getPhoneVerificationSession"];
        put?: never;
        post?: never;
        /**
         * Отменить сессию (US-12-05 — пользователь изменил номер в форме)
         * @description ВСЕГДА 204, идемпотентно. Сессия отменяется только при совпадении statusToken; несовпадение
         *     и несуществующий id дают тот же 204 — эндпоинт не отвечает на вопрос «такая сессия есть?».
         *
         *     Фронтенд обязан звать этот маршрут при изменении номера в форме. Сервер на это не
         *     полагается: при регистрации номер сессии сверяется независимо (R8).
         */
        delete: operations["cancelPhoneVerificationSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/phone-verification/max/webhook/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Вебхук бота MAX (US-12-09)
         * @description АНОНИМНЫЙ. Аутентификация — секрет последним сегментом пути; он маскируется в access-логе
         *     nginx (deploy/nginx/ezbook.conf) и в логах приложения. Требования площадки: HTTPS на 443,
         *     сертификат доверенного УЦ (О4).
         *
         *     200 отдаётся и на распознанный, и на НЕРАСПОЗНАННЫЙ апдейт, и при внутреннем исключении:
         *     площадка снимает подписку после 8 часов без успешного ответа (О4), поэтому любой не-2xx на
         *     неожиданный апдейт — способ уронить дорожку своими руками. Незнакомое уходит в лог.
         *
         *     404 — токен не совпал либо подсистема выключена (прецедент цикла 9: нераспознанное на
         *     вебхуке → 404, не 400).
         */
        post: operations["receiveMaxBotUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/phone-verification/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Наблюдаемость подсистемы для оператора платформы (US-12-13)
         * @description Только SuperAdmin. НИ ОДНОГО телефона, идентификатора MAX-аккаунта или payload'а в ответе
         *     нет и быть не может. Счётчики — агрегат по таблице сессий, отдельной таблицы счётчиков нет.
         */
        get: operations["getPhoneVerificationDiagnostics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Регистрация — аддитивное поле phoneVerification (US-12-01, US-12-07)
         * @description КОНТРАКТ ОБРАТНОСОВМЕСТИМ. phoneVerification необязателен; вызов без него ведёт себя ровно
         *     как до цикла (те же два обязательных акцепта, тот же лимит auth-register 5/час на IP,
         *     deploy/ci/smoke.sh не правится).
         *
         *     Порядок проверок — часть контракта: legal → телефон → (новое) годность сессии → создание
         *     аккаунта → (новое) запись отметки. Негодная сессия = 409 и аккаунт НЕ создаётся.
         *     Исчерпанный потолок Р5 на последнем шаге аккаунт НЕ ломает — он создаётся с
         *     phoneVerified:false (Р1).
         *
         *     ⚠️ У 409 на этом маршруте теперь ДВА смысла: устаревшие версии правовых документов (цикл 5)
         *     и негодное подтверждение (этот цикл). Различаются текстом.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/change-phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ⚠️ ЛОМАЮЩЕЕ: смена номера получает новый отказ 409 (US-12-17)
         * @description Новое поведение (Р3 + Р6):
         *       * номер не меняется → как сегодня;
         *       * на новом номере НЕТ гостевых записей → как сегодня, подтверждение не требуется (Р1);
         *       * ЕСТЬ гостевые записи и предъявлено годное подтверждение → 200;
         *       * ЕСТЬ гостевые записи, подтверждения нет → 409 «На этом номере уже есть записи…»;
         *       * то же при ВЫКЛЮЧЕННОЙ подсистеме → 409 «Сейчас сменить номер на этот нельзя…».
         *
         *     Новая политика лимитов phone-change (5/час на пользователя) — маршрут раньше не был покрыт
         *     никакой политикой. Каждая упёршаяся в гейт попытка журналируется (R14).
         *
         *     Успешная смена снимает отметку со старого номера в той же транзакции (US-12-11).
         *
         *     🔴 Формулировка результата: закрыт путь через смену номера; путь через регистрацию нового
         *     аккаунта на чужой номер остаётся открытым осознанно (SPEC §6.4, блок V1 в CURRENT_STATE §9).
         */
        post: operations["changePhone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Профиль — аддитивные поля phoneVerified / phoneVerifiedAtUtc (US-12-14) */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/masters/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список клиентов персонала — аддитивный признак phoneVerified (US-12-15)
         * @description Признак считается БЕЗ дополнительного запроса на строку: выборка уже делает Include(Client),
         *     флаг приезжает вместе с именем и телефоном (Q17).
         *
         *     🔴 Правила показа (R15): true → значок с ТЕКСТОВОЙ подписью; false → НИЧЕГО (ни цвета, ни
         *     иконки, ни слов «не подтверждён»); null (гость без аккаунта) → НИЧЕГО, это «неприменимо».
         *     Сортировки и фильтрации по признаку НЕТ. Это не гейт: ни одно действие персонала от признака
         *     не зависит.
         *
         *     Признака НЕТ в публичных/анонимных ответах (каталог компаний, карточка, виджет).
         */
        get: operations["getMasterClients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Выгрузка данных — аддитивная секция phoneVerification (US-12-12)
         * @description Цикл добавляет ОДНУ секцию. Идентификатор MAX-аккаунта (в том числе хешированный) и открытые
         *     сессии в выгрузку НЕ входят. Сопоставление гостевых сущностей по телефону НЕ меняется
         *     (решение Р6, SPEC §6.4). Лимит data-export 3/сутки — без изменений.
         */
        get: operations["exportProfileData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Способ подтверждения. Перечисление append-only; в цикле 12 реализован ровно один.
         * @enum {string}
         */
        PhoneVerificationMethod: "MaxBot";
        /**
         * @description Expired ВЫЧИСЛЯЕТСЯ (Pending/Linked с истёкшим expiresAtUtc), отдельно не хранится.
         * @enum {string}
         */
        PhoneVerificationStatus: "Pending" | "Linked" | "Verified" | "Rejected" | "Cancelled" | "Expired";
        /**
         * @description Машиночитаемая причина отказа. Русский текст собирает СЕРВЕР и отдаёт в поле message —
         *     фронт формулировок не сочиняет.
         * @enum {string}
         */
        PhoneVerificationFailureReason: "PayloadUnknown" | "PayloadExpired" | "PayloadAlreadyUsed" | "PayloadLinkedToAnotherAccount" | "SignatureMismatch" | "ContactNotOwnedBySender" | "NoPhoneInContact" | "PhoneMismatch" | "MaxAccountLimitReached" | "SessionCancelled" | "SubsystemDisabled";
        PhoneVerificationConfig: {
            /** @description Подсистема включена оператором (PhoneVerification:Provider = max-bot). */
            enabled: boolean;
            /**
             * @description Вебхук подписан. enabled && !healthy означает «включено, но сейчас не сработает» —
             *     кнопка в этом состоянии НЕ показывается.
             */
            healthy: boolean;
            /** @description Пустой массив, когда enabled=false. */
            methods: components["schemas"]["PhoneVerificationMethod"][];
            /** @example 600 */
            sessionTtlSeconds: number;
            /** @example 2 */
            pollIntervalSeconds: number;
        };
        StartPhoneVerificationRequest: {
            /**
             * @description Обязателен для анонимного вызова. Для авторизованного можно опустить — берётся текущий
             *     номер аккаунта. Принимается только российский формат (PhoneNormalizer.TryNormalizeRussian).
             * @example +7 (900) 000-00-01
             */
            phone?: string | null;
        };
        PhoneVerificationSessionCreated: {
            /** Format: uuid */
            sessionId: string;
            /** @description Выдаётся ЕДИНОЖДЫ. На сервере хранится только SHA-256. */
            statusToken: string;
            method: components["schemas"]["PhoneVerificationMethod"];
            /**
             * Format: uri
             * @description https://max.ru/<bot>?start=<payload>; payload одноразовый, ≤128 символов (О6).
             *     На десктопе показывается ТЕКСТОМ рядом с QR — обязательное требование доступности.
             * @example https://max.ru/ezbookbot?start=v1.Zm9vYmFyYmF6
             */
            deepLink: string;
            /**
             * @description Содержимое data:image/png;base64,… БЕЗ префикса. null допустим — тогда QR рисует клиент
             *     из deepLink. У изображения обязателен осмысленный текстовый эквивалент.
             */
            qrPngBase64?: string | null;
            /**
             * @description Телефон в маскированном виде (LogMasking.Phone). Немаскированного здесь нет.
             * @example +7 (900) ***-**-01
             */
            phoneMasked: string;
            /** Format: date-time */
            expiresAtUtc: string;
            /** @example 600 */
            ttlSeconds: number;
        };
        PhoneVerificationSessionStatus: {
            /** Format: uuid */
            sessionId: string;
            status: components["schemas"]["PhoneVerificationStatus"];
            failureReason?: components["schemas"]["PhoneVerificationFailureReason"] | null;
            /** @description Готовый русский текст причины; собирает сервер. */
            message?: string | null;
            phoneMasked: string;
            /** Format: date-time */
            expiresAtUtc: string;
            /** Format: date-time */
            verifiedAtUtc?: string | null;
        };
        /** @description Ссылка на завершённую сессию, предъявляемая при регистрации или смене номера. */
        PhoneVerificationRef: {
            /** Format: uuid */
            sessionId: string;
            statusToken: string;
        };
        /**
         * @description Минимальная форма апдейта MAX, на которую опирается разбор. Неизвестные поля игнорируются;
         *     нераспознанный апдейт даёт 200 (иначе площадка снимет подписку — О4).
         */
        MaxUpdate: {
            /**
             * @description Например bot_started или message_created.
             * @example bot_started
             */
            update_type?: string;
            /** Format: int64 */
            timestamp?: number;
            /** @description Одноразовый payload из deep link; приходит с bot_started (О6). */
            payload?: string | null;
            /** @description Отправитель апдейта. Его идентификатор сверяется с владельцем контакта (О5). */
            user?: {
                /** Format: int64 */
                user_id?: number;
            } | null;
            message?: {
                sender?: {
                    /** Format: int64 */
                    user_id?: number;
                };
                body?: {
                    attachments?: {
                        /** @example contact */
                        type?: string;
                        payload?: {
                            /** @description vCard; из неё извлекается номер (Q11). */
                            vcf_info?: string;
                            /**
                             * @description Сведения о владельце контакта. Его идентификатор ОБЯЗАН совпасть с
                             *     отправителем апдейта, иначе подтверждение отклоняется (US-12-04).
                             */
                            max_info?: {
                                /** Format: int64 */
                                user_id?: number;
                            } | null;
                            tam_info?: {
                                /** Format: int64 */
                                user_id?: number;
                            } | null;
                            /** @description HMAC-SHA256 от vcf_info; проверяется ОБЯЗАТЕЛЬНО (US-12-04). */
                            hash?: string;
                        };
                    }[];
                };
            } | null;
        } & {
            [key: string]: unknown;
        };
        PhoneVerificationDiagnostics: {
            enabled: boolean;
            /** @enum {string} */
            provider: "stub" | "max-bot";
            methods: components["schemas"]["PhoneVerificationMethod"][];
            webhookSubscribed: boolean;
            /** Format: date-time */
            lastSubscriptionAttemptAtUtc?: string | null;
            lastSubscriptionError?: string | null;
            last24h: {
                started: number;
                verified: number;
                rejected: number;
                /** @description Ключи — значения PhoneVerificationFailureReason. */
                rejectedByReason: {
                    [key: string]: number;
                };
            };
        };
        RegisterLegal: {
            privacyAcknowledgedVersion: string;
            termsAcceptedVersion: string;
        };
        RegisterRequest: {
            firstName: string;
            lastName: string;
            phone: string;
            password: string;
            email?: string | null;
            legal: components["schemas"]["RegisterLegal"];
            /**
             * @description НОВОЕ В ЦИКЛЕ 12, НЕОБЯЗАТЕЛЬНОЕ. Отсутствие поля = регистрация ровно как до цикла
             *     (Р1, US-12-07). Негодная сессия → 409, аккаунт не создаётся.
             */
            phoneVerification?: components["schemas"]["PhoneVerificationRef"] | null;
        };
        AuthResponse: {
            token: string;
            userId: string;
            phone: string;
            email?: string | null;
            firstName: string;
            lastName: string;
            roles: string[];
            /** @description НОВОЕ В ЦИКЛЕ 12. false у любого, кто не предъявил годное подтверждение. */
            phoneVerified: boolean;
        };
        /** @description Единственное намеренное исключение из «4xx — строка» (§4.1 CURRENT_STATE). */
        IdentityErrors: {
            code?: string;
            description?: string;
        }[];
        ChangePhoneRequest: {
            currentPassword: string;
            newPhone: string;
            /**
             * @description НОВОЕ В ЦИКЛЕ 12, НЕОБЯЗАТЕЛЬНОЕ. Требуется ТОЛЬКО когда на новом номере уже есть
             *     гостевые записи (US-12-17). В остальных случаях смена работает как сегодня (Р1).
             */
            verification?: components["schemas"]["PhoneVerificationRef"] | null;
        };
        /** @description Форма цикла 7, цикл 12 её не меняет. */
        ProfilePlan: {
            [key: string]: unknown;
        } | null;
        Profile: {
            id: string;
            phone: string;
            email?: string | null;
            firstName: string;
            lastName: string;
            avatarUrl?: string | null;
            roles: string[];
            plan?: components["schemas"]["ProfilePlan"];
            /** @description НОВОЕ В ЦИКЛЕ 12. */
            phoneVerified: boolean;
            /**
             * Format: date-time
             * @description НОВОЕ В ЦИКЛЕ 12; null, когда номер не подтверждён.
             */
            phoneVerifiedAtUtc?: string | null;
        };
        MasterClient: {
            clientId?: string | null;
            guestPhone?: string | null;
            name: string;
            phone?: string | null;
            email?: string | null;
            /** Format: date */
            lastVisitDate: string;
            totalVisits: number;
            notes: {
                [key: string]: unknown;
            }[];
            bookingSummaries: {
                [key: string]: unknown;
            }[];
            /**
             * @description НОВОЕ В ЦИКЛЕ 12. true — значок с текстовой подписью; false — НИЧЕГО не рисуется;
             *     null — гость без аккаунта, «неприменимо», тоже НИЧЕГО. Сортировки и фильтра по признаку
             *     нет; это не гейт (R15).
             */
            phoneVerified?: boolean | null;
        };
        PagedMasterClients: {
            items: components["schemas"]["MasterClient"][];
            page: number;
            pageSize: number;
            total: number;
            hasNext: boolean;
        };
        /**
         * @description Описан ТОЛЬКО тот срез выгрузки, который добавляет цикл 12. Остальные секции — контракты
         *     циклов 3 и 5, они не меняются.
         */
        ProfileExportPhoneVerificationSlice: {
            phoneVerification?: {
                phoneVerified: boolean;
                method?: components["schemas"]["PhoneVerificationMethod"] | null;
                /** Format: date-time */
                verifiedAtUtc?: string | null;
            };
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Осознанная ошибка — голая строка по-русски. */
        PlainTextBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Превышен лимит именованной политики. Голая строка по-русски. */
        PlainTextTooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
    };
    parameters: {
        SessionId: string;
        /**
         * @description Вторая половина ключа доступа к сессии; выдаётся один раз при создании. На сервере хранится
         *     только SHA-256 — сессия не перечислима по идентификатору.
         */
        StatusToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPhoneVerificationConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Состояние подсистемы. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneVerificationConfig"];
                };
            };
        };
    };
    startPhoneVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartPhoneVerificationRequest"];
            };
        };
        responses: {
            /** @description Сессия создана. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneVerificationSessionCreated"];
                };
            };
            400: components["responses"]["PlainTextBadRequest"];
            /** @description Прислан невалидный токен (анонимный вызов без токена — норма). Тело пустое. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Подсистема выключена или вебхук не подписан.
             *     Тело: «Подтверждение телефона сейчас недоступно.»
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            429: components["responses"]["PlainTextTooManyRequests"];
        };
    };
    getPhoneVerificationSession: {
        parameters: {
            query: {
                /**
                 * @description Вторая половина ключа доступа к сессии; выдаётся один раз при создании. На сервере хранится
                 *     только SHA-256 — сессия не перечислима по идентификатору.
                 */
                statusToken: components["parameters"]["StatusToken"];
            };
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Текущее состояние сессии. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneVerificationSessionStatus"];
                };
            };
            /** @description Сессия не найдена либо statusToken не подходит. Тело пустое. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelPhoneVerificationSession: {
        parameters: {
            query: {
                /**
                 * @description Вторая половина ключа доступа к сессии; выдаётся один раз при создании. На сервере хранится
                 *     только SHA-256 — сессия не перечислима по идентификатору.
                 */
                statusToken: components["parameters"]["StatusToken"];
            };
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Готово (в том числе если отменять было нечего). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    receiveMaxBotUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description PhoneVerification:Max:WebhookToken. ⚠️ Секрет; в логах маскируется. */
                token: string;
            };
            cookie?: never;
        };
        /**
         * @description Апдейт площадки MAX. Описана минимальная форма, на которую опирается разбор; неизвестные
         *     поля игнорируются.
         */
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaxUpdate"];
            };
        };
        responses: {
            /** @description Принято (в том числе «апдейт не распознан» и «внутренняя ошибка»). Тело пустое. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Токен не совпал либо подсистема выключена. Тело пустое. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["PlainTextTooManyRequests"];
        };
    };
    getPhoneVerificationDiagnostics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Состояние подсистемы и счётчики за сутки. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneVerificationDiagnostics"];
                };
            };
            /** @description Нет токена. Тело пустое. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не SuperAdmin. Тело пустое. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Аккаунт создан. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /**
             * @description Строка (text/plain) — правовые версии/телефон, ЛИБО массив ошибок Identity
             *     (application/json) — единственное намеренное исключение из «4xx — строка» (§4.1).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                    "application/json": components["schemas"]["IdentityErrors"];
                };
            };
            /**
             * @description Либо «Документы были обновлены ещё раз…» (цикл 5), либо «Подтверждение номера не
             *     подходит к этой регистрации…» / «Подтверждение телефона сейчас недоступно.» (цикл 12).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            429: components["responses"]["PlainTextTooManyRequests"];
            /** @description Правовые документы временно недоступны. text/plain. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    changePhone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePhoneRequest"];
            };
        };
        responses: {
            /** @description Номер изменён. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["PlainTextBadRequest"];
            /** @description Нет токена. Тело пустое. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Аккаунт не найден. Тело пустое. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description НОВОЕ В ЦИКЛЕ 12. Две формулировки:
             *     «На этом номере уже есть записи. Подтвердите его через MAX — тогда номер можно будет
             *     сменить.» и «Сейчас сменить номер на этот нельзя: подтверждение номера на платформе
             *     пока не работает.»
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            429: components["responses"]["PlainTextTooManyRequests"];
            /** @description Требуется принять новую редакцию документов. Тело — как у гейта цикла 5. */
            451: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Профиль. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Нет токена. Тело пустое. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Требуется принять новую редакцию документов. */
            451: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMasterClients: {
        parameters: {
            query: {
                companyId: string;
                search?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница клиентов. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedMasterClients"];
                };
            };
            /** @description Нет токена. Тело пустое. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Вызывающий не персонал этой компании. Тело пустое. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Требуется принять новую редакцию документов. */
            451: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exportProfileData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON-файл выгрузки (Content-Disposition: attachment). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileExportPhoneVerificationSlice"];
                };
            };
            /** @description Нет токена. Тело пустое. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["PlainTextTooManyRequests"];
        };
    };
}
