/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/companies/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Компании, где вызывающий — владелец (фильтр по типу, по умолчанию Services) */
        get: operations["getMyCompaniesCycle23"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/member": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Компании, где вызывающий — участник любой роли (фильтр по типу, по умолчанию Services) */
        get: operations["getMemberCompaniesCycle23"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/kinds-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сколько у меня компаний каждого типа и на каком сайте ими управлять */
        get: operations["getCompanyKindsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список компаний в админке — тип и фильтр по типу */
        get: operations["adminListCompaniesCycle23"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать магазин (компания типа Orders) */
        post: operations["createShop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Магазины, где я владелец или сотрудник */
        get: operations["listMyShops"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/slug-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверить адрес магазина или предложить его из названия */
        get: operations["checkShopSlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        /** Магазин для кабинета (владелец и сотрудник) */
        get: operations["getShop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Правила приёма заказов (только владелец) */
        put: operations["updateShopSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/seller": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Реквизиты продавца (только владелец) — [legal L2] */
        put: operations["updateShopSeller"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/slug": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Сменить адрес магазина (только владелец; старая ссылка и QR перестают работать) */
        put: operations["changeShopSlug"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/qr": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        /** QR-код ссылки на магазин (PNG для печати на A4) */
        get: operations["getShopQr"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        /** Категории магазина в порядке показа (владелец и сотрудник) */
        get: operations["listCategories"];
        put?: never;
        /** Создать категорию (только владелец) — встаёт последней */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/category-order": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Порядок категорий (только владелец) — полный список id */
        put: operations["reorderCategories"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                categoryId: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Переименовать или скрыть категорию (только владелец) */
        put: operations["updateCategory"];
        post?: never;
        /** Удалить пустую категорию (только владелец) */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/products": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        /**
         * Товары магазина для кабинета и экрана заказов (владелец и сотрудник)
         * @description Ограниченная коллекция (≤ Orders:MaxProductsPerShop), отдаётся целиком, без PagedResult — осознанное исключение (ARCHITECTURE_CYCLE23.md §393.4).
         */
        get: operations["listProducts"];
        put?: never;
        /** Завести товар (только владелец) — встаёт последним в своей категории */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/product-order": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Порядок товаров внутри одной категории (только владелец) */
        put: operations["reorderProducts"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Изменить товар целиком (только владелец); единица не меняется */
        put: operations["updateProduct"];
        post?: never;
        /** Удалить товар из каталога (только владелец); заказы с ним не меняются */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/products/{productId}/image": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить/заменить фото товара (только владелец) — существующий конвейер изображений */
        post: operations["uploadProductImage"];
        /** Убрать фото товара (только владелец) */
        delete: operations["deleteProductImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/products/{productId}/sold-out": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Отметить «закончилось» / вернуть (владелец и сотрудник) */
        put: operations["setProductSoldOut"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/products/{productId}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Задать остаток «на складе» (владелец и сотрудник); null — не учитывать */
        put: operations["setProductStock"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storefront/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Адрес магазина (contracts/cycle23/goods-routes.json → slugPattern). */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /** Страница магазина для покупателя (анонимно) */
        get: operations["getStorefront"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storefront/{slug}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Адрес магазина (contracts/cycle23/goods-routes.json → slugPattern). */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Проверить корзину — текущие цены, доступность, суммы (ничего не резервирует) */
        post: operations["quoteCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storefront/{slug}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Адрес магазина (contracts/cycle23/goods-routes.json → slugPattern). */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Оформить заказ (гость или вошедший — по настройке магазина) */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/public/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Неугадываемый токен заказа из ссылки /o/<token>. */
                token: components["parameters"]["OrderToken"];
            };
            cookie?: never;
        };
        /** Заказ по ссылке (анонимно; кто знает ссылку — видит заказ) */
        get: operations["getPublicOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/public/{token}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Неугадываемый токен заказа из ссылки /o/<token>. */
                token: components["parameters"]["OrderToken"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отменить заказ покупателем (если разрешено для этого заказа и статус New/Accepted) */
        post: operations["cancelPublicOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мои заказы — активные, затем завершённые за 30 дней (только заказы аккаунта, без гостевых) */
        get: operations["listMyOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/order-board": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        /** Экран заказов — три колонки и «Завершённые сегодня»; дешёвый пустой опрос по revision */
        get: operations["getOrderBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        /** Карточка заказа с журналом */
        get: operations["getStaffOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/orders/{orderId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Новый → Принят */
        post: operations["acceptOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/orders/{orderId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Новый → Отклонён (причина необязательна) */
        post: operations["rejectOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/orders/{orderId}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Принят → Готов к выдаче */
        post: operations["markOrderReady"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/orders/{orderId}/issue-quote": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Итог к оплате по фактическому весу — до подтверждения выдачи (ничего не меняет) */
        post: operations["quoteOrderIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/orders/{orderId}/issue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Готов к выдаче → Выдан (фактический вес весовых позиций, списание остатка) */
        post: operations["issueOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/orders/{orderId}/not-picked-up": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Готов к выдаче → Не забран (вручную) */
        post: operations["markOrderNotPickedUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Принят/Готов → Отменён магазином (причина необязательна) */
        post: operations["cancelOrderByShop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shops/{shopId}/orders/{orderId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Правка состава заказа магазином (Новый/Принят/Готов) */
        put: operations["editOrderItems"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Тип компании. Задаётся при создании и не меняется никогда. Services = 0 (все существующие), Orders = 1.
         * @enum {string}
         */
        CompanyKind: "Services" | "Orders";
        /**
         * @description Роль вызывающего в этом магазине. Staff — сотрудник (CompanyMember.Role = Master).
         * @enum {string}
         */
        ShopRole: "Owner" | "Staff" | "SuperAdmin";
        /**
         * @description Кто может заказать. Anyone — любой по имени и телефону (гость — с капчей); VerifiedPhoneOnly — только вошедший с подтверждённым через MAX номером.
         * @enum {string}
         */
        ShopCustomerMode: "Anyone" | "VerifiedPhoneOnly";
        /**
         * @description Manual — заказ создаётся в статусе New; Auto — сразу Accepted.
         * @enum {string}
         */
        OrderAcceptanceMode: "Manual" | "Auto";
        /**
         * @description Piece — цена за штуку, количество в штуках; Weight — цена за 1 кг, количество в граммах.
         * @enum {string}
         */
        ProductUnit: "Piece" | "Weight";
        /**
         * @description New, Accepted, Ready — активные; Issued, Rejected, CancelledByCustomer, CancelledByShop, NotPickedUp — конечные.
         * @enum {string}
         */
        OrderStatus: "New" | "Accepted" | "Ready" | "Issued" | "Rejected" | "CancelledByCustomer" | "CancelledByShop" | "NotPickedUp";
        /**
         * @description Действие персонала, доступное над заказом прямо сейчас (вычисляет сервер).
         * @enum {string}
         */
        OrderAction: "Accept" | "Reject" | "MarkReady" | "Issue" | "NotPickedUp" | "Cancel" | "Edit";
        /** @enum {string} */
        OrderEventKind: "Created" | "Accepted" | "Rejected" | "MarkedReady" | "Issued" | "NotPickedUp" | "CancelledByCustomer" | "CancelledByShop" | "Edited";
        /** @enum {string} */
        OrderActorKind: "Customer" | "Guest" | "Staff" | "SuperAdmin" | "System";
        /**
         * @description Почему позиция корзины не может быть заказана как есть.
         * @enum {string}
         */
        OrderProblemReason: "NotFound" | "Unpublished" | "SoldOut" | "CategoryHidden" | "InsufficientStock" | "BelowMinimum" | "InvalidQuantity" | "PriceChanged";
        /**
         * @description Почему заказ не создан (409 при оформлении).
         * @enum {string}
         */
        OrderRefusalCode: "ShopNotAcceptingOrders" | "LoginRequired" | "PhoneVerificationRequired" | "PhoneVerificationUnavailable" | "EmptyCart" | "TooManyLines" | "PriceChanged" | "ItemsUnavailable";
        /**
         * @description Почему действие над существующим заказом не применено (409).
         * @enum {string}
         */
        OrderConflictCode: "VersionMismatch" | "InvalidTransition" | "CancelNotAllowed" | "AlreadyReady" | "InsufficientStock" | "LastItemCannotBeRemoved" | "InvalidQuantity" | "ProductUnavailable";
        /** @enum {string} */
        CatalogConflictCode: "SlugTaken" | "SlugReserved" | "SlugInvalid" | "CategoryNotEmpty" | "UnitChangeNotAllowed" | "ProductLimitReached" | "CategoryLimitReached" | "PhoneVerificationUnavailable";
        CatalogConflictDto: {
            code: components["schemas"]["CatalogConflictCode"];
            /** @description Готовый русский текст. */
            message: string;
        };
        UuidList: {
            ids: string[];
        };
        /**
         * @description [legal L3] Пищевая информация о товаре. В цикле 1 — одно необязательное поле. Состав полей и их
         *     обязательность уточняются заключением legal-counsel ДОБАВЛЕНИЕМ полей внутрь этого объекта —
         *     форма запроса/ответа снаружи не меняется.
         */
        FoodInfoDto: {
            /** @description «Состав и аллергены», свободный текст. */
            compositionAndAllergens?: string | null;
        };
        /** @description Существующий CompanyDto + два добавочных поля цикла 23 (остальные поля — без изменений). */
        CompanyDtoCycle23: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            kind: components["schemas"]["CompanyKind"];
            /** @description Абсолютная ссылка на публичную страницу по типу компании — https://ezbook.ru/company/<slug> или https://goods.ezbook.ru/<slug>. */
            publicUrl: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Сколько компаний каждого типа у вызывающего (любая роль участника) и где ими управлять. */
        CompanyKindsSummaryDto: {
            services: components["schemas"]["CompanyKindSummaryItem"];
            orders: components["schemas"]["CompanyKindSummaryItem"];
        };
        CompanyKindSummaryItem: {
            count: number;
            /** @description Базовый адрес сайта этого типа: https://ezbook.ru или https://goods.ezbook.ru. */
            siteUrl: string;
        };
        AdminCompanyDtoCycle23: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            isActive: boolean;
            kind: components["schemas"]["CompanyKind"];
            publicUrl: string;
        } & {
            [key: string]: unknown;
        };
        AdminCompanyPage: {
            items: components["schemas"]["AdminCompanyDtoCycle23"][];
            page: number;
            pageSize: number;
            total: number;
            hasNext: boolean;
        };
        CreateShopInput: {
            name: string;
            /** @description Политика — goods-routes.json (slugPattern, reservedSlugs). */
            slug: string;
            /** @description Обязателен, как у салона. */
            cityId: number;
            /** @description Необязательная ручная зона; по умолчанию — зона города. */
            timeZoneId?: string | null;
            description?: string | null;
            /** @description Необязателен; перед сохранением фронт показывает предупреждение о публичности (как в ezbook). */
            address?: string | null;
            /** @description Телефон для покупателей. */
            phone?: string | null;
            email?: string | null;
            ownerTerms: {
                /** @description Версия соглашения с владельцем (TermsOwner), которую фронт показал. */
                version: string;
            };
        };
        CreateShopResponse: {
            shop: components["schemas"]["ShopManageDto"];
            /** @description Новый JWT с claim «lco» (как у POST /api/companies) — фронт обязан заменить им старый. */
            token: string;
        };
        SlugCheckDto: {
            /** @description Проверенный адрес (если передан slug) либо предложенный из названия (если передан только name). */
            slug: string;
            available: boolean;
            /** @description Почему недоступен — готовый текст; null, если доступен. */
            reason?: string | null;
            reasonCode?: components["schemas"]["CatalogConflictCode"] | null;
        };
        ShopListItemDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            logoUrl?: string | null;
            isActive: boolean;
            publicUrl: string;
            myRole: components["schemas"]["ShopRole"];
        };
        ShopSettingsDto: {
            customerMode: components["schemas"]["ShopCustomerMode"];
            acceptanceMode: components["schemas"]["OrderAcceptanceMode"];
            allowCustomerCancel: boolean;
            trackStock: boolean;
            /** Format: date-time */
            updatedAtUtc?: string | null;
        };
        ShopSettingsInput: {
            customerMode: components["schemas"]["ShopCustomerMode"];
            acceptanceMode: components["schemas"]["OrderAcceptanceMode"];
            allowCustomerCancel: boolean;
            trackStock: boolean;
        };
        /** @description [legal L2] Реквизиты продавца. В цикле 1 все поля необязательны; обязательность включается кодом (SellerInfoRequirements) по заключению legal-counsel. */
        SellerInfoInput: {
            /**
             * @description Существующее перечисление LegalEntityForm.
             * @enum {string|null}
             */
            legalForm?: "Ip" | "Company" | "SelfEmployed" | null;
            legalName?: string | null;
            /** @description Проверяется формально (InnValidator), как у заявки на канал. */
            inn?: string | null;
            ogrn?: string | null;
            legalAddress?: string | null;
        };
        SellerInfoDto: components["schemas"]["SellerInfoInput"] & {
            /** @description Все поля из requiredFields заполнены. В цикле 1 requiredFields пуст → всегда true. */
            isComplete: boolean;
            /** @description Имена обязательных полей по текущему правилу (camelCase). В цикле 1 — []. */
            requiredFields: string[];
        };
        /** @description [legal L2] Что показывается покупателю на витрине. null-поля не показываются. */
        PublicSellerInfoDto: {
            legalForm?: string | null;
            legalName?: string | null;
            inn?: string | null;
            ogrn?: string | null;
            legalAddress?: string | null;
        };
        ShopManageDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string | null;
            logoUrl?: string | null;
            address?: string | null;
            phone?: string | null;
            email?: string | null;
            cityId?: number | null;
            cityName?: string | null;
            timeZoneId: string;
            yandexMapsUrl?: string | null;
            twoGisUrl?: string | null;
            isActive: boolean;
            publicUrl: string;
            myRole: components["schemas"]["ShopRole"];
            settings: components["schemas"]["ShopSettingsDto"];
            seller: components["schemas"]["SellerInfoDto"];
            /** @description Итог ShopOrderingGate. В цикле 1 = isActive. */
            acceptingOrders: boolean;
            notAcceptingReason?: string | null;
            /** @description Включена ли подсистема подтверждения телефона (MAX). false → режим VerifiedPhoneOnly включить нельзя. */
            phoneVerificationAvailable: boolean;
            productCount?: number;
        };
        ShopSlugInput: {
            slug: string;
        };
        CategoryDto: {
            /** Format: uuid */
            id: string;
            name: string;
            position: number;
            isHidden: boolean;
            /** @description Неудалённых товаров в категории. */
            productCount: number;
        };
        CategoryInput: {
            name: string;
            /** @default false */
            isHidden: boolean;
        };
        /** @description Остаток товара в базовой единице (штуки или граммы). */
        StockDto: {
            /** @description null — остаток у товара не учитывается. */
            onHand: number | null;
            /** @description Сумма по активным заказам, созданным с резервом. */
            reserved: number;
            /** @description onHand − reserved (может быть < 0, если остаток правили вниз); null при onHand = null. */
            free: number | null;
        };
        ProductDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            categoryId?: string | null;
            name: string;
            description?: string | null;
            imageUrl?: string | null;
            thumbnailUrl?: string | null;
            unit: components["schemas"]["ProductUnit"];
            /** @description За штуку (Piece) или за 1 кг (Weight). */
            price: number;
            /** @description Только Piece: «300 г», «0,5 л». */
            portionText?: string | null;
            /** @description Только Weight. */
            weightStepGrams?: number | null;
            /** @description Piece — 1; Weight — минимальный вес в граммах. */
            minQuantity?: number;
            /** @description Piece — 99; Weight — 10000. */
            maxQuantity?: number;
            position: number;
            isPublished: boolean;
            isSoldOut: boolean;
            foodInfo: components["schemas"]["FoodInfoDto"];
            stock: components["schemas"]["StockDto"];
            /** @description Итог правила «доступный товар» SPEC §4 — то же значение, что увидит покупатель. */
            availableToCustomers: boolean;
        };
        ProductInput: {
            /** Format: uuid */
            categoryId?: string | null;
            name: string;
            description?: string | null;
            unit: components["schemas"]["ProductUnit"];
            /** @description Два знака после запятой; больше — 400. */
            price: number;
            /** @description Только Piece; у Weight — 400. */
            portionText?: string | null;
            /** @description Только Weight; по умолчанию 100. */
            weightStepGrams?: number | null;
            /** @description Только Weight; по умолчанию = шаг; кратно шагу. */
            minQuantityGrams?: number | null;
            isPublished: boolean;
            foodInfo?: components["schemas"]["FoodInfoDto"];
        };
        ProductOrderInput: {
            /**
             * Format: uuid
             * @description null — блок «Другое» (товары без категории).
             */
            categoryId?: string | null;
            productIds: string[];
        };
        SoldOutInput: {
            isSoldOut: boolean;
        };
        StockInput: {
            /** @description Штуки или граммы. null — перестать учитывать остаток у этого товара. */
            onHand: number | null;
        };
        StorefrontProductDto: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            imageUrl?: string | null;
            thumbnailUrl?: string | null;
            unit: components["schemas"]["ProductUnit"];
            price: number;
            portionText?: string | null;
            weightStepGrams?: number | null;
            minQuantity: number;
            maxQuantity: number;
            foodInfo: components["schemas"]["FoodInfoDto"];
            /** @description false — показывается серым с подписью «Закончилось», в корзину не добавляется. */
            available: boolean;
        };
        StorefrontCategoryDto: {
            /**
             * Format: uuid
             * @description null — последний блок «Другое» (товары без категории).
             */
            id?: string | null;
            name: string;
            products: components["schemas"]["StorefrontProductDto"][];
        };
        StorefrontDto: {
            slug: string;
            name: string;
            publicUrl: string;
            logoUrl?: string | null;
            description?: string | null;
            address?: string | null;
            cityName?: string | null;
            phone?: string | null;
            yandexMapsUrl?: string | null;
            twoGisUrl?: string | null;
            /** @description false — магазин заблокирован/деактивирован: «Магазин недоступен», каталог пуст. */
            isAvailable: boolean;
            acceptingOrders: boolean;
            /** @description Готовый текст «сейчас не принимает заказы …». */
            notAcceptingReason?: string | null;
            customerMode: components["schemas"]["ShopCustomerMode"];
            allowCustomerCancel: boolean;
            seller?: components["schemas"]["PublicSellerInfoDto"] | null;
            categories: components["schemas"]["StorefrontCategoryDto"][];
        };
        CartLineInput: {
            /** Format: uuid */
            productId: string;
            quantity: number;
        };
        QuoteInput: {
            items: components["schemas"]["CartLineInput"][];
        };
        OrderProblemDto: {
            /** Format: uuid */
            productId: string;
            /** @description Название товара (или «Товар больше не продаётся», если удалён). */
            name: string;
            reason: components["schemas"]["OrderProblemReason"];
            /** @description Готовый текст для покупателя. */
            message: string;
            /** @description Только PriceChanged. */
            currentUnitPrice?: number | null;
            /** @description Только InsufficientStock — сколько можно заказать сейчас. */
            availableQuantity?: number | null;
        };
        QuoteLineDto: {
            /** Format: uuid */
            productId: string;
            name: string;
            unit: components["schemas"]["ProductUnit"];
            unitPrice: number;
            portionText?: string | null;
            quantity: number;
            lineTotal: number;
            /** @description true у Weight: «≈», сумма уточнится при выдаче. */
            isApproximate: boolean;
            problem?: components["schemas"]["OrderProblemDto"] | null;
        };
        QuoteDto: {
            lines: components["schemas"]["QuoteLineDto"][];
            /** @description Сумма по строкам без проблем. */
            total: number;
            isApproximate: boolean;
            hasProblems: boolean;
            acceptingOrders: boolean;
            notAcceptingReason?: string | null;
        };
        OrderLineInput: {
            /** Format: uuid */
            productId: string;
            quantity: number;
            /** @description Цена, которую видел покупатель. Не совпала с текущей → 409 PriceChanged. */
            expectedUnitPrice: number;
        };
        CreateOrderInput: {
            /**
             * Format: uuid
             * @description Генерирует фронт на одну попытку оформления; повтор с тем же ключом возвращает уже созданный заказ.
             */
            idempotencyKey: string;
            items: components["schemas"]["OrderLineInput"][];
            customerName: string;
            /** @description Обязателен для гостя (российский формат). У вошедшего ИГНОРИРУЕТСЯ — заказ создаётся на номер аккаунта. */
            customerPhone?: string | null;
            comment?: string | null;
            /** @description Обязателен для гостя, когда капча включена (CaptchaService.IsEnforced). */
            captchaToken?: string | null;
        };
        OrderRefusalDto: {
            code: components["schemas"]["OrderRefusalCode"];
            message: string;
            problems?: components["schemas"]["OrderProblemDto"][] | null;
        };
        CreateOrderResponse: {
            order: components["schemas"]["PublicOrderDto"];
            /** @description Абсолютная ссылка https://goods.ezbook.ru/o/<token>. */
            orderUrl: string;
        };
        PublicOrderItemDto: {
            name: string;
            unit: components["schemas"]["ProductUnit"];
            unitPrice: number;
            portionText?: string | null;
            quantityOrdered: number;
            /** @description Фактический вес при выдаче (Weight); у Piece = quantityOrdered после выдачи. */
            quantityActual?: number | null;
            lineTotal: number;
            isApproximate: boolean;
        };
        OrderTimelineStepDto: {
            status: components["schemas"]["OrderStatus"];
            title: string;
            reached: boolean;
            /** Format: date-time */
            reachedAtUtc?: string | null;
        };
        OrderChangeLineDto: {
            name: string;
            /** @description «2 шт × 150 ₽»; null — позиция добавлена. */
            before?: string | null;
            /** @description null — позиция удалена. */
            after?: string | null;
            /** @description Готовая строка «было → стало». */
            text: string;
        };
        OrderShopChangeDto: {
            /** Format: date-time */
            occurredAtUtc: string;
            comment?: string | null;
            changes: components["schemas"]["OrderChangeLineDto"][];
            totalBefore: number;
            totalAfter: number;
        };
        OrderShopInfoDto: {
            name: string;
            slug: string;
            publicUrl: string;
            logoUrl?: string | null;
            address?: string | null;
            cityName?: string | null;
            phone?: string | null;
            yandexMapsUrl?: string | null;
            twoGisUrl?: string | null;
        };
        PublicOrderDto: {
            token: string;
            /** @description Короткий номер «№ 27» — сквозной по магазину в пределах суток магазина. */
            number: number;
            /**
             * Format: date
             * @description Дата заказа по часовому поясу магазина — показывается рядом с номером.
             */
            businessDate: string;
            /** Format: date-time */
            createdAtUtc: string;
            status: components["schemas"]["OrderStatus"];
            statusText: string;
            timeline: components["schemas"]["OrderTimelineStepDto"][];
            items: components["schemas"]["PublicOrderItemDto"][];
            /** @description До выдачи — предварительная сумма; после выдачи — к оплате. */
            total: number;
            totalIsApproximate: boolean;
            comment?: string | null;
            /** @description null — данные покупателя обезличены. */
            customerName: string | null;
            /** @description «+7 (9**) ***-**-67». */
            customerPhoneMasked: string | null;
            /** @description Причина отклонения/отмены магазином, если указана. */
            reason?: string | null;
            canCancel: boolean;
            shop: components["schemas"]["OrderShopInfoDto"];
            shopChanges: components["schemas"]["OrderShopChangeDto"][];
            version: number;
            /** @description true — показать подсказку «сохраните ссылку, другого способа вернуться к заказу нет». */
            isGuest: boolean;
        };
        MyOrderSummaryDto: {
            orderUrl: string;
            token: string;
            number: number;
            /** Format: date */
            businessDate: string;
            shopName: string;
            status: components["schemas"]["OrderStatus"];
            statusText: string;
            total: number;
            totalIsApproximate: boolean;
            /** Format: date-time */
            createdAtUtc: string;
            isActive: boolean;
        };
        StaffOrderItemDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            productId?: string | null;
            name: string;
            unit: components["schemas"]["ProductUnit"];
            unitPrice: number;
            portionText?: string | null;
            weightStepGrams?: number | null;
            quantityOrdered: number;
            quantityActual?: number | null;
            lineTotal: number;
            isApproximate: boolean;
        };
        StaffOrderCardDto: {
            /** Format: uuid */
            id: string;
            number: number;
            /** Format: date */
            businessDate: string;
            /** Format: date-time */
            createdAtUtc: string;
            status: components["schemas"]["OrderStatus"];
            statusText: string;
            customerName?: string | null;
            /** @description Полный номер в каноническом виде (для tel:). null — обезличен. */
            customerPhone?: string | null;
            customerKind: components["schemas"]["OrderActorKind"];
            customerPhoneVerified?: boolean;
            comment?: string | null;
            items: components["schemas"]["StaffOrderItemDto"][];
            total: number;
            totalIsApproximate: boolean;
            /** @description Метка «изменён» — магазин правил состав. */
            isModified: boolean;
            hasWeightItems: boolean;
            reason?: string | null;
            /** Format: date-time */
            completedAtUtc?: string | null;
            version: number;
            availableActions: components["schemas"]["OrderAction"][];
        };
        OrderEventDto: {
            kind: components["schemas"]["OrderEventKind"];
            /** Format: date-time */
            occurredAtUtc: string;
            actorKind: components["schemas"]["OrderActorKind"];
            /** @description Имя снимком (сотрудник) или «Покупатель»/«Гость». */
            actorName?: string | null;
            fromStatus?: components["schemas"]["OrderStatus"] | null;
            toStatus?: components["schemas"]["OrderStatus"] | null;
            reason?: string | null;
            comment?: string | null;
            changes?: components["schemas"]["OrderChangeLineDto"][] | null;
            totalBefore?: number | null;
            totalAfter?: number | null;
            /** @description Готовая строка журнала. */
            text: string;
        };
        StaffOrderDto: components["schemas"]["StaffOrderCardDto"] & {
            events: components["schemas"]["OrderEventDto"][];
        };
        OrderBoardDto: {
            /**
             * Format: int64
             * @description Счётчик изменений заказов магазина. Передаётся обратно в sinceRevision.
             */
            revision: number;
            /** @description false — с sinceRevision ничего не менялось; массивы ниже null (дешёвый пустой опрос). */
            changed: boolean;
            /** Format: date */
            businessDate: string;
            /**
             * Format: date-time
             * @description Для «N минут назад» без расхождения часов.
             */
            serverTimeUtc: string;
            newOrders?: components["schemas"]["StaffOrderCardDto"][] | null;
            accepted?: components["schemas"]["StaffOrderCardDto"][] | null;
            ready?: components["schemas"]["StaffOrderCardDto"][] | null;
            completedToday?: components["schemas"]["StaffOrderCardDto"][] | null;
        };
        VersionInput: {
            expectedVersion: number;
        };
        ReasonInput: {
            expectedVersion: number;
            /** @description Необязательна; покупатель её видит. */
            reason?: string | null;
        };
        ActualQuantityInput: {
            /** Format: uuid */
            itemId: string;
            /** @description Граммы для Weight. Для Piece не передаётся (выдаётся заказанное). */
            quantity: number;
        };
        IssueQuoteInput: {
            actualQuantities: components["schemas"]["ActualQuantityInput"][];
        };
        IssueInput: {
            expectedVersion: number;
            /** @description Ровно по одной записи на каждую Weight-позицию; пусто, если весовых нет. */
            actualQuantities: components["schemas"]["ActualQuantityInput"][];
        };
        IssueQuoteDto: {
            lines: components["schemas"]["StaffOrderItemDto"][];
            /** @description Итог к оплате — то же число, что будет сохранено при выдаче. */
            finalTotal: number;
        };
        /** @description Существующая позиция — itemId; новая (замена или добавление) — productId по текущей цене каталога. */
        EditOrderLineInput: {
            /** Format: uuid */
            itemId?: string | null;
            /** Format: uuid */
            productId?: string | null;
            quantity: number;
        };
        EditOrderInput: {
            expectedVersion: number;
            /** @description ПОЛНЫЙ желаемый состав. Позиции, которых нет в списке, удаляются. */
            items: components["schemas"]["EditOrderLineInput"][];
            commentForCustomer?: string | null;
        };
        OrderConflictDto: {
            code: components["schemas"]["OrderConflictCode"];
            message: string;
            /** @description Актуальное состояние заказа (для VersionMismatch и InvalidTransition у персонала). */
            order?: components["schemas"]["StaffOrderDto"] | null;
            /** @description Актуальное состояние для покупателя (отказ в отмене по ссылке). */
            publicOrder?: components["schemas"]["PublicOrderDto"] | null;
            problems?: components["schemas"]["OrderProblemDto"][] | null;
        };
    };
    responses: {
        /** @description Осознанный отказ — голая строка по-русски. */
        PlainTextError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Нет или недействителен токен. Тело пустое. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Нет прав (не сотрудник/не владелец этого магазина). Тело пустое. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Не найдено (в том числе компания другого типа там, где ищется магазин). Тело пустое. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Требуется принять новую редакцию правовых документов (глобальный или владельческий гейт). */
        LegalGate: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Превышен лимит частоты — голая строка по-русски. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Отказ в каталоге с машиночитаемым кодом. */
        CatalogConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CatalogConflictDto"];
            };
        };
        /** @description Действие над заказом не применено — код, текст и (для VersionMismatch) актуальный заказ. */
        OrderConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OrderConflictDto"];
            };
        };
    };
    parameters: {
        /** @description Id магазина (Company.Id компании типа Orders). */
        ShopId: string;
        ProductId: string;
        CategoryId: string;
        OrderId: string;
        /** @description Адрес магазина (contracts/cycle23/goods-routes.json → slugPattern). */
        Slug: string;
        /** @description Неугадываемый токен заказа из ссылки /o/<token>. */
        OrderToken: string;
        /**
         * @description Тип компаний в ответе. НЕ передан → Services (так ведёт себя фронт ezbook, который параметр
         *     не шлёт: магазины из его кабинета исчезают без правки кода). Фронт goods шлёт Orders.
         */
        KindQuery: components["schemas"]["CompanyKind"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMyCompaniesCycle23: {
        parameters: {
            query?: {
                /**
                 * @description Тип компаний в ответе. НЕ передан → Services (так ведёт себя фронт ezbook, который параметр
                 *     не шлёт: магазины из его кабинета исчезают без правки кода). Фронт goods шлёт Orders.
                 */
                kind?: components["parameters"]["KindQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список компаний одного типа. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDtoCycle23"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMemberCompaniesCycle23: {
        parameters: {
            query?: {
                /**
                 * @description Тип компаний в ответе. НЕ передан → Services (так ведёт себя фронт ezbook, который параметр
                 *     не шлёт: магазины из его кабинета исчезают без правки кода). Фронт goods шлёт Orders.
                 */
                kind?: components["parameters"]["KindQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список компаний одного типа. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDtoCycle23"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCompanyKindsSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Счётчики по типам и базовые адреса сайтов. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyKindsSummaryDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    adminListCompaniesCycle23: {
        parameters: {
            query?: {
                /** @description Не передан — все типы (поведение админки по умолчанию не меняется). */
                kind?: components["schemas"]["CompanyKind"];
                search?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница компаний. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCompanyPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createShop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShopInput"];
            };
        };
        responses: {
            /** @description Магазин создан; вызывающий — владелец. В ответе новый токен. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateShopResponse"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            /** @description Превышен лимит компаний биллинг-аккаунта (салоны и магазины считаются вместе) — текст BillingTexts.CompanyLimitReached. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            409: components["responses"]["CatalogConflict"];
            451: components["responses"]["LegalGate"];
            503: components["responses"]["PlainTextError"];
        };
    };
    listMyShops: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список (заблокированные тоже — с isActive false). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopListItemDto"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    checkShopSlug: {
        parameters: {
            query?: {
                slug?: string;
                /** @description Если slug не передан — предложить свободный адрес из названия (транслитерация). */
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Результат проверки/предложения. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlugCheckDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getShop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Магазин, настройки, реквизиты, роль вызывающего. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopManageDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateShopSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShopSettingsInput"];
            };
        };
        responses: {
            /** @description Магазин с новыми настройками. Действуют только на новые заказы. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopManageDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["CatalogConflict"];
            451: components["responses"]["LegalGate"];
        };
    };
    updateShopSeller: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SellerInfoInput"];
            };
        };
        responses: {
            /** @description Магазин с обновлёнными реквизитами. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopManageDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            451: components["responses"]["LegalGate"];
        };
    };
    changeShopSlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShopSlugInput"];
            };
        };
        responses: {
            /** @description Магазин с новым адресом и publicUrl. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopManageDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["CatalogConflict"];
            451: components["responses"]["LegalGate"];
        };
    };
    getShopQr: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PNG ~2000×2000 px, коррекция ошибок Q, ссылка = publicUrl. Content-Disposition: attachment; filename="<slug>-qr.png". */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Все категории, включая скрытые. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description Категория создана. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["CatalogConflict"];
            451: components["responses"]["LegalGate"];
        };
    };
    reorderCategories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UuidList"];
            };
        };
        responses: {
            /** @description Категории в новом порядке. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"][];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            451: components["responses"]["LegalGate"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                categoryId: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description Обновлённая категория. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            451: components["responses"]["LegalGate"];
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                categoryId: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалена. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["CatalogConflict"];
            451: components["responses"]["LegalGate"];
        };
    };
    listProducts: {
        parameters: {
            query?: {
                search?: string;
                /** @description uuid категории; литерал "none" — товары без категории. */
                categoryId?: string;
            };
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Неудалённые товары, по категории и позиции. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"][];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description Товар создан. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["CatalogConflict"];
            451: components["responses"]["LegalGate"];
        };
    };
    reorderProducts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductOrderInput"];
            };
        };
        responses: {
            /** @description Товары категории в новом порядке. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"][];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            451: components["responses"]["LegalGate"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description Обновлённый товар. Уже созданные заказы не меняются. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["CatalogConflict"];
            451: components["responses"]["LegalGate"];
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Товар удалён из каталога (мягко — строка остаётся для заказов). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            451: components["responses"]["LegalGate"];
        };
    };
    uploadProductImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Товар с новым imageUrl/thumbnailUrl. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Файл больше лимита. Тело пустое. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["TooManyRequests"];
            451: components["responses"]["LegalGate"];
        };
    };
    deleteProductImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Товар без фото. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            451: components["responses"]["LegalGate"];
        };
    };
    setProductSoldOut: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SoldOutInput"];
            };
        };
        responses: {
            /** @description Товар с новым isSoldOut. Действует сразу; заказы не меняются. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setProductStock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockInput"];
            };
        };
        responses: {
            /** @description Товар с новым остатком и пересчитанным free. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getStorefront: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Адрес магазина (contracts/cycle23/goods-routes.json → slugPattern). */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Магазин и каталог доступных к показу товаров. Заблокированный — isAvailable false, каталог пуст. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorefrontDto"];
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    quoteCart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Адрес магазина (contracts/cycle23/goods-routes.json → slugPattern). */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteInput"];
            };
        };
        responses: {
            /** @description Построчный расчёт; проблемные строки — с problem (ответ всегда 200). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Адрес магазина (contracts/cycle23/goods-routes.json → slugPattern). */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderInput"];
            };
        };
        responses: {
            /** @description Повтор с тем же idempotencyKey — возвращён ранее созданный заказ. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrderResponse"];
                };
            };
            /** @description Заказ создан. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrderResponse"];
                };
            };
            400: components["responses"]["PlainTextError"];
            404: components["responses"]["NotFound"];
            /** @description Заказ не создан — код, текст и проблемные позиции. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRefusalDto"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            451: components["responses"]["LegalGate"];
        };
    };
    getPublicOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Неугадываемый токен заказа из ссылки /o/<token>. */
                token: components["parameters"]["OrderToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказ глазами покупателя. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicOrderDto"];
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    cancelPublicOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Неугадываемый токен заказа из ссылки /o/<token>. */
                token: components["parameters"]["OrderToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказ в статусе CancelledByCustomer, резерв возвращён. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicOrderDto"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["OrderConflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listMyOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список, активные сверху. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyOrderSummaryDto"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getOrderBoard: {
        parameters: {
            query?: {
                /** @description revision из прошлого ответа. Совпал с текущим и businessDate тот же → changed false, массивы null. */
                sinceRevision?: number;
                /** @description businessDate из прошлого ответа — смена суток магазина считается изменением. */
                businessDate?: string;
            };
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Доска или «без изменений». */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderBoardDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getStaffOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказ и журнал событий. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOrderDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    acceptOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionInput"];
            };
        };
        responses: {
            /** @description Обновлённый заказ. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOrderDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["OrderConflict"];
        };
    };
    rejectOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonInput"];
            };
        };
        responses: {
            /** @description Обновлённый заказ. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOrderDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["OrderConflict"];
        };
    };
    markOrderReady: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionInput"];
            };
        };
        responses: {
            /** @description Обновлённый заказ. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOrderDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["OrderConflict"];
        };
    };
    quoteOrderIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueQuoteInput"];
            };
        };
        responses: {
            /** @description Строки с фактическими количествами и итог. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueQuoteDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["OrderConflict"];
        };
    };
    issueOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueInput"];
            };
        };
        responses: {
            /** @description Выданный заказ с итогом к оплате. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOrderDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["OrderConflict"];
        };
    };
    markOrderNotPickedUp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionInput"];
            };
        };
        responses: {
            /** @description Обновлённый заказ; резерв возвращён. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOrderDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["OrderConflict"];
        };
    };
    cancelOrderByShop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonInput"];
            };
        };
        responses: {
            /** @description Обновлённый заказ; резерв возвращён. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOrderDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["OrderConflict"];
        };
    };
    editOrderItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id магазина (Company.Id компании типа Orders). */
                shopId: components["parameters"]["ShopId"];
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditOrderInput"];
            };
        };
        responses: {
            /** @description Обновлённый заказ (isModified true, событие Edited в журнале). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOrderDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["OrderConflict"];
        };
    };
}
