/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bookings/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Статус каждого дня диапазона одним запросом
         * @description ИЗМЕНЁН в цикле 10: добавлен параметр `extendedHours`, в ответе — `staffMode` и
         *     `days[].scheduleState`.
         *
         *     Анонимный (лимит `availability`, 60/мин на IP). Таблица доверия — ровно та же, что у
         *     `GET /bookings/slots`, чтобы календарь и сетка времени не могли разойтись:
         *
         *       manual=true & extendedHours=true & персонал этой компании -> сутки целиком;
         *       manual=true & extendedHours=false & персонал этой компании -> окно 09:00–21:00;
         *       всё остальное (в т.ч. extendedHours без manual, и любой не-персонал) -> как сегодня.
         *
         *     Горизонт записи применяется только при `staffMode: false`.
         */
        get: operations["getAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * История изменений записи (только персоналу компании и суперадмину)
         * @description НОВЫЙ в цикле 10.
         *
         *     Доступ: персонал компании этой записи (Master/CompanyOwner в ней) или SuperAdmin.
         *     Всем остальным — 404 с пустым телом, ВКЛЮЧАЯ клиента, которому запись принадлежит:
         *     журнал клиенту не отдаётся ни в каком виде (решение П8), и код ответа не должен
         *     работать оракулом «существует ли запись с таким id».
         *
         *     В ответе НЕТ телефонов и почты — только идентичность автора, снимок имени и роль.
         */
        get: operations["getBookingHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Карточка записи (добавлено поле historyEventCount)
         * @description ИЗМЕНЁН в цикле 10 — ДОБАВОЧНОЕ поле `historyEventCount`. Остальная форма BookingDto
         *     не меняется и здесь не переописывается (см. API_DOCUMENTATION.md).
         *
         *     `historyEventCount` заполняется, только если вызывающий — персонал компании этой записи
         *     или SuperAdmin. В остальных случаях `null` (не «0» и не отсутствие поля).
         */
        get: operations["getBookingById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/master": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Записи персонала (добавлено поле historyEventCount)
         * @description ИЗМЕНЁН в цикле 10 — ДОБАВОЧНОЕ поле `historyEventCount` у каждого элемента, считается
         *     ОДНИМ группирующим запросом на всю страницу (не N+1). Сама история здесь НЕ отдаётся:
         *     она грузится отдельным вызовом только по разворачиванию карточки.
         */
        get: operations["getMasterBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{id}/masters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Мастера компании (добавлены includeHidden и providesServices)
         * @description ИЗМЕНЁН в цикле 10.
         *
         *     `includeHidden=true` учитывается ТОЛЬКО для персонала этой компании и SuperAdmin; для всех
         *     остальных молча игнорируется — публичная выдача не меняется ни на строку.
         *
         *     `providesServices` в ответе позволяет персоналу подписать, почему мастера не видно клиентам.
         *     При анонимном/клиентском вызове это поле всегда true.
         */
        get: operations["getCompanyMasters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Фотографии салона (анонимно)
         * @description НОВЫЙ. Публичный класс хранения, авторизации нет (решение П6).
         *     Порядок — по `position`, при равенстве — по времени создания. Пустой массив, если фото нет.
         */
        get: operations["getCompanyPhotos"];
        put?: never;
        /**
         * Загрузить фотографию салона
         * @description НОВЫЙ. Только владелец компании и SuperAdmin (мастер фото салона не меняет).
         *     Лимит запросов — политика `uploads`, размер тела — 5 МБ.
         *
         *     Тип файла определяется по СИГНАТУРЕ БАЙТ, не по имени и не по Content-Type.
         *     Метаданные (включая геолокацию) не сохраняются — изображение ре-энкодится.
         *     Квоту PhotoQuotaMb НЕ расходует и под photo-retention-cleanup НЕ подпадает (решение П5).
         *     Согласие на публикацию изображений при загрузке НЕ собирается (решение П7).
         *
         *     Новая фотография добавляется В КОНЕЦ (position = n) и обложкой не становится.
         *     Повторная загрузка того же файла возвращает 200 и уже существующую фотографию
         *     (дедупликация по хешу обработанных байт) — дубликат не создаётся, лимит не расходуется.
         */
        post: operations["uploadCompanyPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{id}/photos/{photoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить фотографию салона
         * @description НОВЫЙ. Только владелец компании и SuperAdmin.
         *     После удаления позиции оставшихся компактизируются в 0..n−1 в той же транзакции:
         *     если удалили обложку, обложкой становится следующая. Файл с диска удаляется после коммита.
         *
         *     404 — компании нет, фотографии нет, либо фотография принадлежит другой компании
         *     (существование чужой фотографии не подтверждается).
         */
        delete: operations["deleteCompanyPhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{id}/photos/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Задать порядок фотографий (первая — обложка)
         * @description НОВЫЙ. Только владелец компании и SuperAdmin.
         *
         *     `photoIds` — ПОЛНАЯ перестановка текущих фотографий компании: столько же элементов, те же
         *     идентификаторы, без повторов. Частичная перестановка отвергается намеренно: полный список
         *     делает операцию идемпотентной и снимает вопрос «что стало с теми, кого не упомянули».
         *     Первый в списке становится обложкой.
         */
        put: operations["reorderCompanyPhotos"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Публичная карточка компании (добавлены photos и обложка)
         * @description ИЗМЕНЁН в цикле 10 — ДОБАВОЧНЫЕ поля `photos`, `coverPhotoUrl`, `coverThumbnailUrl`.
         *     Остальная форма CompanyDto не меняется и здесь не переописывается.
         *
         *     Фотографии приезжают ВМЕСТЕ с компанией: публичная страница не делает отдельного запроса
         *     за галереей (требование производительности). `photos` заполняется именно здесь.
         */
        get: operations["getCompanyBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Публичный каталог (добавлена только обложка)
         * @description ИЗМЕНЁН в цикле 10 — ДОБАВОЧНЫЕ `coverPhotoUrl` и `coverThumbnailUrl`.
         *     `photos` здесь ВСЕГДА null: сотня салонов × 10 фото — это тысяча строк ради картинок,
         *     которых в каталоге не видно. Обложки считаются одним батчевым запросом на страницу.
         */
        get: operations["getCompanies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Можно ли записать в этот день при том фоллбеке, который сервер применил.
         *     Состояния «прошедший день» сервер не присылает намеренно — браузер знает свою
         *     локальную дату лучше.
         * @enum {string}
         */
        DayAvailabilityStatus: "Available" | "FullyBooked" | "DayOff";
        /**
         * @description НОВОЕ в цикле 10. Состояние ГРАФИКА мастера на дату — независимо от того, можно ли
         *     туда записать. Приходит ТОЛЬКО при staffMode = true; иначе всегда null.
         *       Working    — есть строка расписания, мастер работает;
         *       DayOff     — строка есть, день помечен нерабочим  -> подпись «выходной»;
         *       NoSchedule — строки расписания нет вовсе          -> подпись «нет графика».
         *     Для персонала это ИНФОРМАЦИЯ, а не запрет: день с DayOff/NoSchedule остаётся нажимаемым,
         *     а подпись обязана попасть в доступное имя кнопки дня (aria-label), а не только в вёрстку.
         * @enum {string}
         */
        DayScheduleState: "Working" | "DayOff" | "NoSchedule";
        DayAvailabilityDto: {
            /** Format: date */
            date: string;
            status: components["schemas"]["DayAvailabilityStatus"];
            /**
             * @description Начало последнего свободного слота дня; null, если свободных нет.
             * @example 20:30:00
             */
            lastFreeSlotStart: string | null;
            scheduleState: components["schemas"]["DayScheduleState"] | null;
        };
        AvailabilityDto: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            totalDurationMinutes: number;
            /** @example 30 */
            stepMinutes: number;
            /** @description Настройка компании. Персонала не касается. */
            horizonDays: number;
            /**
             * Format: date
             * @description Последняя дата, на которую может записаться КЛИЕНТ.
             */
            horizonLastDate: string;
            /**
             * @description НОВОЕ в цикле 10. Сервер проверил членство вызывающего в этой компании и применил
             *     режим персонала. ЕДИНСТВЕННЫЙ признак, по которому интерфейсу разрешено рисовать
             *     режим персонала. Роль в токене, состав стора и отправленный флаг manual таким
             *     признаком НЕ являются.
             */
            staffMode: boolean;
            days: components["schemas"]["DayAvailabilityDto"][];
        };
        MasterPublicDto: {
            userId: string;
            firstName: string;
            lastName: string;
            avatarUrl: string | null;
            bio: string | null;
            /**
             * @description НОВОЕ в цикле 10. Виден ли сотрудник в публичном выборе мастера.
             *     При анонимном/клиентском вызове всегда true (иначе он не попал бы в выдачу).
             */
            providesServices: boolean;
        };
        /**
         * @description Что произошло с записью. Список закрыт, значения append-only.
         * @enum {string}
         */
        BookingEventKind: "Created" | "Rescheduled" | "Cancelled" | "Completed" | "NoShow" | "PaymentMarked";
        /**
         * @description Кто совершил действие. `System` в этом цикле никем не ставится — член существует, потому что
         *     сущность обязана допускать системное событие, и потому что добавить его потом дороже.
         * @enum {string}
         */
        BookingActorKind: "Client" | "Guest" | "Staff" | "SuperAdmin" | "System";
        /** @description В объекте автора НЕТ и не будет телефонов и почты. */
        BookingEventActorDto: {
            kind: components["schemas"]["BookingActorKind"];
            /**
             * @description СНИМОК имени на момент события — переживает удаление сотрудника из компании и удаление
             *     аккаунта (тот же принцип, что у Booking.Price и BookingService.NameSnapshot).
             *     null только у System.
             */
            name: string | null;
            /**
             * @description Роль автора В ЭТОЙ КОМПАНИИ на момент события; null у остальных видов автора.
             * @enum {string|null}
             */
            role: "Master" | "CompanyOwner" | null;
            /**
             * @description Готовая русская строка «кто это сделал» — собирает СЕРВЕР
             *     («Записал Иван Петров (мастер)», «Записался клиент Анна Иванова», «Записался гость Пётр»,
             *     «Администратор платформы», «Система»). Вторую версию формулировок на фронте не собирать:
             *     они разойдутся (конвенция NotificationTexts / ChannelPresentation).
             */
            label: string;
        };
        BookingRescheduleDto: {
            /** Format: date */
            fromDate: string;
            fromStartTime: string;
            /** Format: date */
            toDate: string;
            toStartTime: string;
        };
        BookingEventDto: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["BookingEventKind"];
            /** Format: date-time */
            occurredAt: string;
            /** @description Готовый русский заголовок события, собирает сервер («Запись перенесена»). */
            title: string;
            actor: components["schemas"]["BookingEventActorDto"];
            /** @description Заполнен ТОЛЬКО у kind = Rescheduled, иначе null. */
            reschedule: components["schemas"]["BookingRescheduleDto"] | null;
            /** @description Заполнена ТОЛЬКО у kind = Cancelled и только если причина была указана. */
            cancellationReason: string | null;
        };
        BookingHistoryDto: {
            /** Format: uuid */
            bookingId: string;
            /**
             * @description Запись создана ДО внедрения журнала (у неё нет события Created). Backfill'а нет
             *     по решению П3.
             *       events пуст  + precedesJournal=true  -> блок истории НЕ показывать вовсе;
             *       events непуст + precedesJournal=true -> показать блок и ОДНУ строку пояснения,
             *         что журнал ведётся с определённого момента;
             *       precedesJournal=false                -> обычный блок.
             */
            precedesJournal: boolean;
            /** @description Хронология по возрастанию occurredAt. Как показывать (новое сверху или снизу) — решает интерфейс, но единообразно. */
            events: components["schemas"]["BookingEventDto"][];
        };
        /**
         * @description ДЕЛЬТА к существующему BookingDto: цикл 10 добавляет ровно одно поле. Остальные поля
         *     приходят как раньше и здесь намеренно не переописываются (additionalProperties: true) —
         *     вторая копия большого DTO разошлась бы с оригиналом.
         */
        BookingDtoHistoryDelta: {
            /** Format: uuid */
            id: string;
            /**
             * @description Сколько событий в журнале этой записи. Заполняется ТОЛЬКО на персональских эндпоинтах
             *     (GET /bookings/master, GET /bookings/{id} для персонала). На клиентских
             *     (GET /bookings/client, ответ POST /bookings) — ВСЕГДА null: это не фильтрация на фронте,
             *     а незаполненное сервером поле (решение П8).
             *     null означает «сервер не считал», а не «событий нет».
             *     Интерфейс рисует блок истории только при historyEventCount > 0.
             */
            historyEventCount: number | null;
        } & {
            [key: string]: unknown;
        };
        CompanyPhotoDto: {
            /** Format: uuid */
            id: string;
            /**
             * @description Полноразмерная (до 1600 px), публичный класс хранения, отдаётся анонимно.
             * @example /uploads/companies/9f1c2b7e-0000-4000-8000-000000000001.jpg
             */
            url: string;
            /**
             * @description Миниатюра (до 480 px). Списки и плитка показывают ЕЁ, полноразмерная — по клику.
             * @example /uploads/companies/3a7b1d40-0000-4000-8000-000000000002.jpg
             */
            thumbnailUrl: string;
            width: number;
            height: number;
            /** @description 0-based порядок показа. 0 — обложка. */
            position: number;
            /** @description Производное от position == 0, отдаётся для удобства интерфейса. */
            isCover: boolean;
        };
        ReorderCompanyPhotosDto: {
            /**
             * @description ПОЛНАЯ перестановка текущих фотографий компании: столько же элементов, те же
             *     идентификаторы, без повторов. Первый становится обложкой.
             */
            photoIds: string[];
        };
        /**
         * @description ДЕЛЬТА к существующему CompanyDto: цикл 10 добавляет три поля. Остальные приходят как
         *     раньше и здесь не переописываются.
         */
        CompanyDtoPhotoDelta: {
            /** Format: uuid */
            id: string;
            slug: string;
            /** @description Полноразмерная обложка (фотография с position = 0); null, если фотографий нет. */
            coverPhotoUrl: string | null;
            /** @description Миниатюра обложки. Каталог показывает именно её. */
            coverThumbnailUrl: string | null;
            /**
             * @description Весь список в порядке показа. Заполняется ТОЛЬКО на GET /companies/{slug}
             *     (публичная страница получает галерею без второго запроса).
             *     На остальных эндпоинтах — null. Важно: null = «на этом эндпоинте список не отдаётся»,
             *     [] = «фотографий нет».
             */
            photos: components["schemas"]["CompanyPhotoDto"][] | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Голая строка с причиной (text/plain), не JSON-объект */
        BadRequestText: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Голая строка с причиной (text/plain) */
        NotFoundText: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Пустое тело. Используется и когда объекта нет, и когда вызывающему не положено знать о его существовании. */
        NotFoundEmpty: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Пустое тело */
        UnauthorizedEmpty: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Пустое тело */
        ForbiddenEmpty: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Превышен лимит запросов (именованная политика) */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        CompanyIdQuery: string;
        MasterIdQuery: string;
        /** @description Одна услуга. Нужен либо он, либо serviceIds; при обоих serviceIds[0] обязан совпадать с ним. */
        ServiceIdQuery: string;
        /**
         * @description Состав визита, 1..5 без повторов. Повторяется на каждый идентификатор
         *     (serviceIds=a&serviceIds=b), НЕ в форме serviceIds[]=a.
         */
        ServiceIdsQuery: string[];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAvailability: {
        parameters: {
            query: {
                companyId: components["parameters"]["CompanyIdQuery"];
                masterId: components["parameters"]["MasterIdQuery"];
                /** @description Одна услуга. Нужен либо он, либо serviceIds; при обоих serviceIds[0] обязан совпадать с ним. */
                serviceId?: components["parameters"]["ServiceIdQuery"];
                /**
                 * @description Состав визита, 1..5 без повторов. Повторяется на каждый идентификатор
                 *     (serviceIds=a&serviceIds=b), НЕ в форме serviceIds[]=a.
                 */
                serviceIds?: components["parameters"]["ServiceIdsQuery"];
                /** @description Начало диапазона. Не раньше «сегодня−1». */
                from: string;
                /** @description Конец диапазона. Не раньше `from`; диапазон не более 31 дня. */
                to: string;
                /** @description Просьба включить режим персонала. Учитывается только для персонала этой компании и SuperAdmin. */
                manual?: boolean;
                /**
                 * @description НОВЫЙ в цикле 10. Просьба показать сутки целиком (игнорируя график и перерывы).
                 *     Действует ТОЛЬКО вместе с `manual=true` и ТОЛЬКО для персонала этой компании.
                 *     `extendedHours=true` без `manual=true` не даёт ничего никому.
                 */
                extendedHours?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Состояние дней диапазона */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityDto"];
                };
            };
            400: components["responses"]["BadRequestText"];
            404: components["responses"]["NotFoundText"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getBookingHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Хронология событий (по возрастанию occurredAt) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingHistoryDto"];
                };
            };
            401: components["responses"]["UnauthorizedEmpty"];
            404: components["responses"]["NotFoundEmpty"];
        };
    };
    getBookingById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Запись */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDtoHistoryDelta"];
                };
            };
            401: components["responses"]["UnauthorizedEmpty"];
            403: components["responses"]["ForbiddenEmpty"];
            404: components["responses"]["NotFoundEmpty"];
        };
    };
    getMasterBookings: {
        parameters: {
            query?: {
                date?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список записей */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDtoHistoryDelta"][];
                };
            };
            401: components["responses"]["UnauthorizedEmpty"];
            403: components["responses"]["ForbiddenEmpty"];
        };
    };
    getCompanyMasters: {
        parameters: {
            query?: {
                /** @description Пустая строка = «без фильтра»; не-uuid = 400. */
                serviceId?: string;
                /** @description НОВЫЙ. Включить сотрудников с providesServices = false. Только для персонала этой компании. */
                includeHidden?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Мастера */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasterPublicDto"][];
                };
            };
            400: components["responses"]["BadRequestText"];
            404: components["responses"]["NotFoundEmpty"];
        };
    };
    getCompanyPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список фотографий в порядке показа */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyPhotoDto"][];
                };
            };
            404: components["responses"]["NotFoundEmpty"];
        };
    };
    uploadCompanyPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description JPEG / PNG / WEBP, не больше 5 МБ.
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Такая фотография уже была загружена — возвращается существующая */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyPhotoDto"];
                };
            };
            /** @description Фотография загружена */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyPhotoDto"];
                };
            };
            /**
             * @description Голая строка. Возможные тексты:
             *       «В галерее салона может быть не больше 10 фотографий» (единственный новый, по-русски);
             *       File is required; Image is too large — the limit is 5 MB;
             *       Unsupported image type — use JPEG, PNG or WEBP;
             *       Image dimensions are too large — try a smaller image.;
             *       File is not a valid image; Server storage is full — try again later.
             *     Английские тексты общие для всех точек загрузки продукта и переводятся на фронте
             *     (utils/uploadError.ts) — второго словаря ошибок загрузки не заводим.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["UnauthorizedEmpty"];
            403: components["responses"]["ForbiddenEmpty"];
            404: components["responses"]["NotFoundEmpty"];
            /** @description Тело больше RequestSizeLimit (5 МБ) */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    deleteCompanyPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                photoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалено */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedEmpty"];
            403: components["responses"]["ForbiddenEmpty"];
            404: components["responses"]["NotFoundEmpty"];
        };
    };
    reorderCompanyPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderCompanyPhotosDto"];
            };
        };
        responses: {
            /** @description Новый порядок */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyPhotoDto"][];
                };
            };
            /** @description Голая строка: «Список должен содержать все фотографии салона ровно по одному разу» */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["UnauthorizedEmpty"];
            403: components["responses"]["ForbiddenEmpty"];
            404: components["responses"]["NotFoundEmpty"];
        };
    };
    getCompanyBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Компания */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDtoPhotoDelta"];
                };
            };
            404: components["responses"]["NotFoundEmpty"];
        };
    };
    getCompanies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список компаний */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDtoPhotoDelta"][];
                };
            };
        };
    };
}
