/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/pricing/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Публичная сетка тарифов «Заказов» (анонимно, из кеша 60 с)
         * @description Без авторизации, без rate limit, без переключателя публикации. Тело кешируется на сервере 60 с; правка тарифа в
         *     админке сбрасывает кеш сразу. GET /api/pricing этим маршрутом не затрагивается.
         */
        get: operations["pricingGetOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OrdersPublicPricingDto: {
            /**
             * @description Совпадает со значением внутри ETag.
             * @example 3f9a0c1d2e4b5a69
             */
            version: string;
            /** @enum {string} */
            currency: "RUB";
            /** @description По sortOrder, затем по pricePerMonth. Только линейка «Заказы», только IsActive && IsPublic, без служебного «Демо». */
            plans: components["schemas"]["OrdersPublicPlanDto"][];
            /** @example Подключение тарифа выполняет администратор платформы — оставьте заявку в кабинете, и мы свяжемся с вами. */
            notice: string;
            /** @description Текст юриста под сеткой (PlatformSettings pricing.orders.legal-notice). null, пока не задан. */
            legalNotice: string | null;
        };
        OrdersPublicPlanDto: {
            /** Format: uuid */
            id: string;
            /** @example Лавка */
            name: string;
            description: string | null;
            /**
             * @description Рублей в месяц. 0 — бесплатный тариф.
             * @example 690
             */
            pricePerMonth: number;
            highlights: string[];
            /** @description MaxCompanies тарифа — магазинов на аккаунт. null — без ограничения. */
            includedShops: number | null;
            /** @description MaxEmployees тарифа — участников вместе с владельцем. null — без ограничения. */
            includedMembers: number | null;
            /**
             * @description min(MaxProductsPerShop ?? потолок, потолок), потолок = Orders:MaxProductsPerShop (1000). Никогда не null.
             * @example 300
             */
            includedProductsPerShop: number;
            /**
             * @description MaxOrdersPerMonth тарифа — заказов в календарный месяц на аккаунт. null — без ограничения.
             * @example 1500
             */
            includedOrdersPerMonth: number | null;
            sortOrder: number;
            /** @description Системный бесплатный тариф линейки (IsSystemFree). */
            isFree: boolean;
        };
    };
    responses: {
        /** @description Сетки нет — в линейке «Заказы» нет активного публичного тарифа. Пустое тело. Ожидаемое состояние, не ошибка. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description If-None-Match совпал с текущим ETag. Пустое тело. */
        NotModified: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Слабый ETag вида W/"<16 hex>"; то же значение без W/ и кавычек — в поле version. */
        ETag: string;
        /** @description Всегда «public, max-age=60». */
        CacheControl: "public, max-age=60";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    pricingGetOrders: {
        parameters: {
            query?: never;
            header?: {
                /** @description ETag из прошлого ответа; при совпадении — 304. */
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сетка опубликована (есть хотя бы один активный публичный тариф линейки «Заказы»). */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "version": "3f9a0c1d2e4b5a69",
                     *       "currency": "RUB",
                     *       "notice": "Подключение тарифа выполняет администратор платформы — оставьте заявку в кабинете, и мы свяжемся с вами.",
                     *       "legalNotice": null,
                     *       "plans": [
                     *         {
                     *           "id": "0c24f0e5-6a3d-4a5e-9b1f-2d4c7e8a9b01",
                     *           "name": "Бесплатный",
                     *           "description": "Чтобы начать: один магазин, приём заказов по ссылке, QR-коду и из каталога.",
                     *           "pricePerMonth": 0,
                     *           "highlights": [
                     *             "Экран заказов со звуком нового заказа",
                     *             "Время получения: как можно скорее или к часу",
                     *             "Показ в каталоге goods"
                     *           ],
                     *           "includedShops": 1,
                     *           "includedMembers": 2,
                     *           "includedProductsPerShop": 50,
                     *           "includedOrdersPerMonth": 150,
                     *           "sortOrder": 10,
                     *           "isFree": true
                     *         },
                     *         {
                     *           "id": "5a1e0c38-0000-4000-8000-000000000020",
                     *           "name": "Лавка",
                     *           "description": "Для пекарни, кофейни или небольшого магазина с постоянным потоком заказов.",
                     *           "pricePerMonth": 690,
                     *           "highlights": [
                     *             "Всё, что в бесплатном",
                     *             "Предзаказ на дату и меню на день",
                     *             "Весовые товары с точной суммой при выдаче"
                     *           ],
                     *           "includedShops": 1,
                     *           "includedMembers": 5,
                     *           "includedProductsPerShop": 300,
                     *           "includedOrdersPerMonth": 1500,
                     *           "sortOrder": 20,
                     *           "isFree": false
                     *         },
                     *         {
                     *           "id": "5a1e0c38-0000-4000-8000-000000000030",
                     *           "name": "Магазин",
                     *           "description": "Для магазина с несколькими точками: до 3 магазинов на одной подписке.",
                     *           "pricePerMonth": 1490,
                     *           "highlights": [
                     *             "Всё, что в «Лавке»",
                     *             "До 3 магазинов на одной подписке",
                     *             "Отчёты: история заказов, сводка, лист сборки"
                     *           ],
                     *           "includedShops": 3,
                     *           "includedMembers": 15,
                     *           "includedProductsPerShop": 1000,
                     *           "includedOrdersPerMonth": 5000,
                     *           "sortOrder": 30,
                     *           "isFree": false
                     *         },
                     *         {
                     *           "id": "5a1e0c38-0000-4000-8000-000000000040",
                     *           "name": "Сеть магазинов",
                     *           "description": "Для сети от 4 магазинов. Стоимость от 2 990 ₽ в месяц, зависит от числа магазинов.",
                     *           "pricePerMonth": 2990,
                     *           "highlights": [
                     *             "Всё, что в «Магазине»",
                     *             "Магазины и участники без ограничения",
                     *             "Итоговая цена — после заявки, по числу магазинов"
                     *           ],
                     *           "includedShops": null,
                     *           "includedMembers": null,
                     *           "includedProductsPerShop": 1000,
                     *           "includedOrdersPerMonth": null,
                     *           "sortOrder": 40,
                     *           "isFree": false
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["OrdersPublicPricingDto"];
                };
            };
            304: components["responses"]["NotModified"];
            404: components["responses"]["NotFound"];
        };
    };
}
