/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Отмена визита (форма запроса не меняется, добавляется 409)
         * @description API_CONTRACT_CYCLE17.md §322.
         *
         *     Полномочие вычисляет сервер из базы, в этом порядке:
         *       1) персонал (назначенный мастер, владелец компании, суперадмин) — окно НЕ применяется;
         *       2) клиент-владелец записи (booking.clientId == вызывающий) — окно применяется;
         *       3) все прочие — 403 с пустым телом (семантика этой ручки НЕ менялась: здесь 403, а не 404,
         *          в отличие от PATCH /bookings/{id}/reschedule — осознанная асимметрия, долг C17-2).
         *
         *     Правило окна для клиента-владельца:
         *       minHours      = Company.clientRescheduleMinHours, приведённое к [0..168], иначе 2
         *       visitStartUtc = начало визита в часовом поясе компании, приведённое к UTC
         *       отказ (409),  если nowUtc > visitStartUtc − minHours часов
         *
         *     Уже начавшийся или прошедший визит клиент отменить не может (персонал — может, как и раньше).
         *     Миграции данных нет: правило вычисляется в момент вызова.
         */
        patch: operations["cancelBooking"];
        trace?: never;
    };
    "/api/bookings/client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Визиты клиента (форма прежняя, цикл 17 добавляет одно вычисляемое поле)
         * @description API_CONTRACT_CYCLE17.md §323. Единственное место, где считается clientCancelAllowed.
         *     Ноль новых запросов к БД: Company уже включена в выборку, окно и время начала визита в UTC
         *     уже вычисляются здесь же для clientRescheduleAllowed (цикл 15).
         */
        get: operations["getClientBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/subscription/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Заявка на смену тарифа/опций (ответ получает предупреждение о необратимости)
         * @description API_CONTRACT_CYCLE17.md §325.1. Запрос не меняется. В ответе появляется необязательное поле
         *     irreversibilityNotice — непустое только когда:
         *       * у аккаунта есть активная подписка на тариф;
         *       * этот текущий тариф снят с продажи (isActive: true, isPublic: false);
         *       * заявка просит СМЕНУ тарифа (planId передан и отличается от текущего).
         *     Текст пишет legal-counsel (пп. 6.13.15–6.13.16 03-terms-owner.html, П2.8.6 13-payment-terms.html).
         */
        post: operations["submitSubscriptionRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Экран «Ваша подписка» (форма не меняется, меняется текст напоминания)
         * @description API_CONTRACT_CYCLE17.md §325.2. Форма ответа прежняя. Цикл 17 меняет СОДЕРЖИМОЕ warning.text
         *     при warning.kind == "Expiring": если текущий тариф снят с продажи (isPublic: false), к строке
         *     добавляется предупреждение о необратимости (формулировка — legal-counsel). При публичном
         *     тарифе строка обязана совпадать с сегодняшней ПОСИМВОЛЬНО. Ветка kind == "Expired" не меняется.
         *     Поле pendingRequest.irreversibilityNotice — то же, что в §325.1.
         */
        get: operations["getOwnerSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Форма прежняя (см. контракты циклов 6/10/15 и API_DOCUMENTATION.md). Здесь перечислены
         *     только поля, значимые для цикла 17. Новое в цикле 17 — ровно одно: clientCancelAllowed.
         */
        BookingDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            companyId: string;
            /** Format: date */
            date: string;
            /** @example 14:00:00 */
            startTime: string;
            /** @enum {string} */
            status: "Pending" | "Confirmed" | "Cancelled" | "Completed" | "NoShow";
            /**
             * @description ЦИКЛ 15, не меняется. Считается только на GET /api/bookings/client.
             *     Требует статуса Pending/Confirmed, company.allowSelfBooking, тарифного разрешения
             *     онлайн-записи И окна переноса.
             */
            clientRescheduleAllowed?: boolean | null;
            /**
             * Format: int32
             * @description ЦИКЛ 15, не меняется. Окно компании в часах. С цикла 17 это же значение управляет окном
             *     ОТМЕНЫ. Фронт обязан читать N отсюда и нигде не хранить своей константы.
             */
            clientRescheduleMinHours?: number | null;
            /**
             * Format: int32
             * @description ЦИКЛ 15, не меняется.
             */
            companyBookingHorizonDays?: number | null;
            /**
             * @description ЦИКЛ 17, НОВОЕ. Считается ТОЛЬКО на GET /api/bookings/client; на
             *     GET /api/bookings/master, GET /api/bookings/{id} и в ответе POST /api/bookings — всегда null
             *     («сервер не считал это для данного вызывающего», не «нельзя»).
             *
             *     true  <=> статус Pending/Confirmed И nowUtc <= visitStartUtc − clientRescheduleMinHours.
             *
             *     НЕ равно clientRescheduleAllowed: отмена не требует ни company.allowSelfBooking, ни
             *     тарифного разрешения онлайн-записи. Подсказка для интерфейса, а не выданное право —
             *     сервер перепроверяет правило на PATCH /api/bookings/{id}/cancel.
             */
            clientCancelAllowed?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        SubscriptionRequestInput: {
            /** Format: uuid */
            planId?: string | null;
            /**
             * @description Обязательное поле со стороны ASP.NET model-binding (C# DTO объявляет Options непустым
             *     non-nullable List без значения по умолчанию) — отсутствие поля отклоняется общим 400
             *     ДО контроллера. Пустой массив [] допустим, отсутствие поля — нет.
             */
            options: {
                /** Format: uuid */
                optionId: string;
                /** Format: int32 */
                quantity: number;
            }[];
            comment?: string | null;
        };
        /**
         * @description Форма прежняя (контракт цикла 7). Новое в цикле 17 — ровно одно поле: irreversibilityNotice.
         *     ⚠️ Это же поле добавляется в contracts/cycle7/openapi.yaml, потому что типы экрана биллинга
         *     фронт берёт из types/api-cycle7.generated.ts.
         */
        SubscriptionRequestDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "Pending";
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            desiredPlanId?: string | null;
            desiredPlanName?: string | null;
            /** Format: double */
            estimatedMonthlyPrice: number;
            items: {
                /** Format: uuid */
                optionId?: string;
                name?: string;
                /** Format: int32 */
                quantity?: number;
            }[];
            comment?: string | null;
            /**
             * @description ЦИКЛ 17, НОВОЕ. Готовая строка простого текста БЕЗ разметки, составленная сервером по
             *     формулировке legal-counsel. Непусто только при смене СНЯТОГО С ПРОДАЖИ тарифа
             *     (isActive: true, isPublic: false) на другой; во всех остальных случаях null.
             *     Фронт показывает её и в ответе на отправку заявки, и при последующих открытиях экрана
             *     (поле приходит и внутри GET /api/billing/subscription -> pendingRequest).
             */
            irreversibilityNotice?: string | null;
        } & {
            [key: string]: unknown;
        };
        SubscriptionWarningDto: {
            /** @enum {string} */
            kind: "Expiring" | "Expired";
            /**
             * @description ЦИКЛ 17 меняет СОДЕРЖИМОЕ (не форму) при kind == "Expiring":
             *       * тариф публичный  -> строка посимвольно как до цикла:
             *         «Подписка истекает через {N} дн. — продлите её, чтобы не потерять возможности тарифа.»
             *       * тариф снят с продажи (isPublic: false) -> та же строка ПЛЮС предупреждение
             *         «вернуться на этот тариф будет нельзя» (формулировка — legal-counsel, п. 6.8.5).
             *     kind == "Expired" не меняется вовсе.
             */
            text: string;
            affected: string[];
        } & {
            [key: string]: unknown;
        };
        /** @description Форма прежняя (контракт цикла 7). Здесь перечислены только поля, значимые для цикла 17. */
        OwnerSubscriptionDto: {
            /** @example RUB */
            currency: string;
            /** @enum {string} */
            status: "Free" | "Active" | "Expired";
            statusText: string;
            /** Format: date-time */
            paidUntil?: string | null;
            /** Format: int32 */
            expiresInDays?: number | null;
            /** @description Считается по plan.notifyDaysBefore — механизм цикла 7, цикл 17 его не меняет. */
            isExpiringSoon?: boolean;
            warning?: components["schemas"]["SubscriptionWarningDto"] | null;
            pendingRequest?: components["schemas"]["SubscriptionRequestDto"] | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** @description Причина отмены (её увидит салон) либо null. Максимум 300 символов. */
        requestBody?: {
            content: {
                "application/json": string | null;
            };
        };
        responses: {
            /** @description Визит отменён */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Причина длиннее 300 символов (валидация ввода, поведение не менялось) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example Cancellation reason must be 300 characters or fewer. */
                    "text/plain": string;
                };
            };
            /** @description Не аутентифицирован (тело пустое) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Вызывающий не владелец записи и не персонал компании (тело пустое) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Записи с таким id нет (тело пустое) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description ЦИКЛ 17, НОВОЕ. Клиент-владелец пытается отменить визит внутри окна компании
             *     (включая уже начавшийся или прошедший визит). Статус записи НЕ изменён.
             *     Тело — готовая русская строка с подставленным фактическим значением окна;
             *     фронт показывает её дословно.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example Отменить запись можно не позже чем за 24 ч до визита. Чтобы отменить, свяжитесь с салоном. */
                    "text/plain": string;
                };
            };
            /** @description Запрос без `Content-Type: application/json` (или с чужим типом). Отвечает не прикладной код, а привязка модели ASP.NET Core — Kestrel обрывает запрос до контроллера, тело фактически ПУСТОЕ (`Content-Length: 0`, заголовок `Content-Type` в ответе отсутствует вовсе — проверено `curl` напрямую, это не ProblemDetails). Поведение сквозное для всего API и существовало всегда; здесь оно записано, чтобы автосверка не считала его нарушением. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getClientBookings: {
        parameters: {
            query?: {
                /** @description upcoming | Pending | Confirmed | Cancelled | Completed | NoShow. Пустая строка (`?status=`) значит то же, что отсутствие параметра, — фильтр не применяется (`BookingFilters.TryParseClientStatus`, ветка `string.IsNullOrEmpty`). Правило существовало всегда, но в схеме описано не было, из-за чего автосверка считала штатный ответ 200 нарушением контракта. Числовые значения перечисления (`?status=3`) тоже принимаются — это давняя обратная совместимость `BookingFilters.TryParseClientStatus`. В enum они не вынесены намеренно: перечисление описывает рекомендованную форму, а не полный набор принимаемых строк. Неопределённые ординалы (`99`, `-1`) отклоняются с 400. */
                status?: "" | "upcoming" | "Pending" | "Confirmed" | "Cancelled" | "Completed" | "NoShow";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список визитов клиента */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDto"][];
                };
            };
            /** @description Неизвестный фильтр статуса */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Не аутентифицирован (тело пустое) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitSubscriptionRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionRequestInput"];
            };
        };
        responses: {
            /** @description Заявка сохранена (повторная отправка ПЕРЕЗАПИСЫВАЕТ предыдущую — поведение цикла 7) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionRequestDto"];
                };
            };
            /** @description Комментарий длиннее 500 символов, неизвестная опция/тариф, количество < 1 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Не аутентифицирован (тело пустое) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description У вызывающего нет биллинг-аккаунта (тело пустое) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запрос без `Content-Type: application/json` (или с чужим типом). Тот же сквозной эффект привязки модели ASP.NET Core, что и у PATCH /api/bookings/{id}/cancel (см. там) — тело фактически ПУСТОЕ (`Content-Length: 0`, `Content-Type` в ответе отсутствует, не ProblemDetails — проверено `curl` напрямую). Записан здесь по той же причине: `requestBody` у этой ручки обязателен (`required: true`), значит привязка модели проверяет `Content-Type` до прикладного кода и на этом пути тоже. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOwnerSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Подписка владельца */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerSubscriptionDto"];
                };
            };
            /** @description Не аутентифицирован (тело пустое) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description У вызывающего нет биллинг-аккаунта (тело пустое) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
