/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Каталог салонов (все города) — витринные компании включены, с пометкой isShowcase */
        get: operations["companiesGetAll"];
        put?: never;
        /** Создать салон — цикл 28 резервирует слаги с префиксом "primer-" */
        post: operations["companiesCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Каталог салонов по городу с поиском и страницами — витринные компании включены */
        get: operations["companiesGetPublic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Компании владельца (кабинет) — CompanyDto с пометкой витрины */
        get: operations["companiesGetMy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Публичная страница салона — isShowcase включает бейдж «Пример», строку ShowcaseNotice и noindex */
        get: operations["companiesGetBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить сотрудника — цикл 28 запрещает смешивать витрину и настоящие учётки */
        post: operations["companyMembersAdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Онлайн-запись — закрытая витрина отвечает 409 ShowcaseBookingClosed (JSON)
         * @description Порядок: 404 компания → 409 магазин (text) → 403 allowSelfBooking → 409 ShowcaseBookingClosed (JSON,
         *     если isShowcase && !showcaseBookingOpen и вызывающий не персонал) → капча → … (прежний порядок).
         */
        post: operations["bookingsCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** «Мои визиты» клиента — BookingDto с companyIsShowcase */
        get: operations["bookingsGetClient"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка записи — BookingDto с companyIsShowcase */
        get: operations["bookingsGetById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход по телефону и паролю — витринная учётка всегда 401 (форма не меняется) */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сводка — прежние счётчики без витрины, плюс счётчики витрины */
        get: operations["adminGetStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Пользователи — фильтр showcase и поле isShowcase */
        get: operations["adminGetUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Компании — фильтр showcase, поля isShowcase и showcaseBookingOpen */
        get: operations["adminGetCompanies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/billing-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Биллинг-аккаунты — фильтр showcase и поле isShowcase */
        get: operations["adminGetBillingAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/billing-accounts/{accountId}/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Назначить тариф — служебный тариф витрины только витринному аккаунту */
        put: operations["adminAssignSubscription"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/companies/{id}/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Сменить ответственного — запрет смешивания; демо-роли — 403 DemoRestricted */
        put: operations["adminUpdateCompanyOwner"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/companies/{companyId}/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Перенести компанию в другой аккаунт — запрет смешивания; демо-роли — 403 DemoRestricted */
        post: operations["adminTransferCompany"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Статус демо-режима — плашка, кнопки ролей, «идёт сброс»; вне демо 404 */
        get: operations["demoGetStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход под готовой демо-ролью без пароля; вне демо 404 */
        post: operations["demoLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Смена пароля — демо-роли получают 403 DemoRestricted */
        post: operations["profileChangePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/change-phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Смена телефона — демо-роли получают 403 DemoRestricted */
        post: operations["profileChangePhone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/delete-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Удаление аккаунта — демо-роли получают 403 DemoRestricted */
        post: operations["profileDeleteAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/subscription/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Заявка на тариф — демо-роли получают 403 DemoRestricted */
        post: operations["billingSubmitSubscriptionRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/trial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Активация пробного периода — демо-роли получают 403 DemoRestricted */
        post: operations["billingActivateTrial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CompanyPhotoDto: {
            /** Format: uuid */
            id: string;
            url: string;
            thumbnailUrl: string;
            width: number;
            height: number;
            position: number;
            isCover: boolean;
        };
        /**
         * @description Полная форма CompanyDto после цикла 28. Новые поля — isShowcase и showcaseBookingOpen (в конце).
         *     У витринной компании phone, email, yandexMapsUrl, twoGisUrl — null; slug начинается с "primer-".
         */
        CompanyDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string | null;
            logoUrl?: string | null;
            address?: string | null;
            phone?: string | null;
            email?: string | null;
            allowSelfBooking: boolean;
            requirePrepayment: boolean;
            onlineBookingEnabled: boolean;
            allowAnalytics: boolean;
            allowMailing: boolean;
            showInPublicListing: boolean;
            publicListingEnabled: boolean;
            prepaymentEnabled: boolean;
            planAllowsOnlineBooking: boolean;
            planAllowsOnlinePayment: boolean;
            planAllowsPublicListing: boolean;
            /**
             * @deprecated
             * @description Устарело с цикла 7 — используйте accountSeatsUsed/accountSeatsLimit/canAddEmployee.
             */
            maxEmployees?: number | null;
            employeeCount: number;
            accountSeatsUsed?: number | null;
            accountSeatsLimit?: number | null;
            canAddEmployee?: boolean | null;
            averageRating?: number | null;
            reviewCount: number;
            cityId?: number | null;
            cityName?: string | null;
            cityRegion?: string | null;
            timeZoneId: string;
            timeZoneIsManual: boolean;
            utcOffsetMinutes: number;
            bookingHorizonDays: number;
            coverPhotoUrl?: string | null;
            coverThumbnailUrl?: string | null;
            /** @description Заполнен только в GET /api/companies/{slug}; в списках — null. */
            photos?: components["schemas"]["CompanyPhotoDto"][] | null;
            yandexMapsUrl?: string | null;
            twoGisUrl?: string | null;
            clientRescheduleMinHours: number;
            /** @enum {string} */
            kind: "Services" | "Orders";
            publicUrl: string;
            /** @description Цикл 28. Компания создана генератором витрины. У настоящих — всегда false. */
            isShowcase: boolean;
            /**
             * @description Цикл 28. Витринная компания принимает онлайн-запись. У настоящих — всегда false.
             *     isShowcase && !showcaseBookingOpen → POST /api/bookings отвечает 409 ShowcaseBookingClosed.
             */
            showcaseBookingOpen: boolean;
        };
        PagedCompanyDto: {
            items: components["schemas"]["CompanyDto"][];
            page: number;
            pageSize: number;
            total: number;
            hasNext: boolean;
        };
        OwnerTermsDto: {
            version?: string | null;
        };
        /** @description Форма не меняется. Цикл 28 добавляет 409 для слага с префиксом "primer-". */
        CreateCompanyDto: {
            name: string;
            slug: string;
            description?: string | null;
            address?: string | null;
            phone?: string | null;
            email?: string | null;
            cityId?: number | null;
            timeZoneId?: string | null;
            allowSelfBooking?: boolean;
            showInPublicListing?: boolean;
            ownerTerms?: components["schemas"]["OwnerTermsDto"];
        } & {
            [key: string]: unknown;
        };
        CreateCompanyResponseDto: {
            company: components["schemas"]["CompanyDto"];
            token: string;
        };
        /** @description Форма не меняется (циклы 3, 5, 6). Описаны обязательные и гостевые поля. */
        CreateBookingDto: {
            /** Format: uuid */
            companyId: string;
            /** Format: uuid */
            serviceId: string;
            masterId: string;
            /** Format: date */
            date: string;
            /** @example 14:30:00 */
            startTime: string;
            notes?: string | null;
            guestName?: string | null;
            guestPhone?: string | null;
            guestEmail?: string | null;
            captchaToken?: string | null;
            serviceIds?: string[] | null;
        } & {
            [key: string]: unknown;
        };
        /** @description Цикл 28 — отказ записи в закрытую витринную компанию (409 application/json). */
        ShowcaseRefusalDto: {
            /** @enum {string} */
            code: "ShowcaseBookingClosed";
            /**
             * @description Запасной текст сервера. Фронт предпочитает uiText ShowcaseBookingClosed, если он есть.
             * @example Это пример страницы салона: компания вымышленная, запись к ней не принимается.
             */
            message: string;
        };
        /**
         * @description ЧАСТИЧНОЕ описание: цикл 28 добавляет только companyIsShowcase. Остальные поля BookingDto не меняются
         *     (циклы 3–20) и здесь не перечислены полностью — отсюда additionalProperties: true.
         */
        BookingDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            companyId: string;
            companyName: string;
            companySlug: string;
            /** Format: date */
            date: string;
            /** @example 14:30:00 */
            startTime: string;
            /** @example 15:30:00 */
            endTime: string;
            /** @enum {string} */
            status: "Pending" | "Confirmed" | "Cancelled" | "Completed" | "NoShow";
            /** @description Цикл 28. Запись в витринной компании — фронт показывает строку ShowcaseNotice в карточке записи. */
            companyIsShowcase: boolean;
        } & {
            [key: string]: unknown;
        };
        AddMemberDto: {
            phone: string;
            firstName: string;
            lastName: string;
            role: string;
            bio?: string | null;
            email?: string | null;
        } & {
            [key: string]: unknown;
        };
        AdminUserDto: {
            id: string;
            phone: string;
            email?: string | null;
            firstName: string;
            lastName: string;
            avatarUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
            roles: string[];
            ownedCompanyCount: number;
            /** Format: uuid */
            planConfigId?: string | null;
            planName: string;
            /** Format: date-time */
            paidUntil?: string | null;
            subscriptionActive: boolean;
            /** @description Цикл 28. Учётка создана генератором витрины (бейдж «Витрина»). */
            isShowcase: boolean;
        };
        PagedAdminUserDto: {
            items: components["schemas"]["AdminUserDto"][];
            page: number;
            pageSize: number;
            total: number;
            hasNext: boolean;
        };
        AdminCompanyDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            email?: string | null;
            phone?: string | null;
            isActive: boolean;
            allowSelfBooking: boolean;
            /** Format: date-time */
            createdAt: string;
            memberCount: number;
            bookingCount: number;
            ownerUserId: string;
            ownerEmail: string;
            /** Format: uuid */
            planConfigId?: string | null;
            planName: string;
            /** Format: date-time */
            paidUntil?: string | null;
            subscriptionActive: boolean;
            /** @enum {string} */
            kind: "Services" | "Orders";
            publicUrl: string;
            /** @description Цикл 28. Витринная компания (бейдж «Витрина»). */
            isShowcase: boolean;
            /** @description Цикл 28. Витринная компания принимает запись. */
            showcaseBookingOpen: boolean;
        };
        PagedAdminCompanyDto: {
            items: components["schemas"]["AdminCompanyDto"][];
            page: number;
            pageSize: number;
            total: number;
            hasNext: boolean;
        };
        /** @description ЧАСТИЧНОЕ описание: элемент списка аккаунтов циклов 7/18/24 не меняется, кроме нового поля isShowcase. */
        AdminBillingAccountItem: {
            /** Format: uuid */
            id: string;
            /** @description Цикл 28. Биллинг-аккаунт витрины. */
            isShowcase: boolean;
        } & {
            [key: string]: unknown;
        };
        PagedAdminBillingAccounts: {
            items: components["schemas"]["AdminBillingAccountItem"][];
            page: number;
            pageSize: number;
            totalCount: number;
        };
        /** @description Цикл 28: прежние счётчики считаются БЕЗ витрины; три новых поля — отдельно витрина. */
        AdminStatsDto: {
            totalCompanies: number;
            totalUsers: number;
            totalBookings: number;
            completedBookings: number;
            totalRevenue: number;
            overdueSubjectRequests: number;
            showcaseCompanies: number;
            showcaseUsers: number;
            showcaseBookings: number;
        };
        UpdateCompanyOwnerDto: {
            newOwnerUserId: string;
        };
        CompanyTransferInput: {
            /** Format: uuid */
            targetBillingAccountId: string;
            newOwnerUserId?: string | null;
            confirmSeatOverflow?: boolean;
            comment?: string | null;
            confirmRightsTransfer?: boolean;
        };
        /** @description Форма не меняется (циклы 7, 20, 24). Цикл 28 добавляет 409 для тарифа «Витрина (служебный)». */
        AssignSubscriptionInput: {
            /** Format: uuid */
            planId?: string | null;
            isActive: boolean;
            /** Format: date */
            paidUntil?: string | null;
        } & {
            [key: string]: unknown;
        };
        LoginDto: {
            phone: string;
            password: string;
        };
        AuthResponseDto: {
            token: string;
            userId: string;
            phone: string;
            email?: string | null;
            firstName: string;
            lastName: string;
            roles: string[];
            phoneVerified: boolean;
        };
        /** @enum {string} */
        DemoRole: "owner" | "master" | "client";
        DemoRoleDto: {
            role: components["schemas"]["DemoRole"];
            /** @example Войти как владелец салона */
            label: string;
        };
        DemoStatusDto: {
            /** @description Всегда true (вне демо маршрут отвечает 404). */
            demoMode: boolean;
            /** @description Идёт сброс — фронт показывает «Демо обновляется, зайдите через минуту». */
            resetting: boolean;
            /** @example 04:00 */
            resetLocalTime: string;
            /** @example Europe/Moscow */
            timeZoneId: string;
            /** Format: date-time */
            lastResetAtUtc?: string | null;
            roles: components["schemas"]["DemoRoleDto"][];
        };
        DemoLoginRequest: {
            role: components["schemas"]["DemoRole"];
        };
        TrialActivationInput: {
            termsVersion?: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Осознанный отказ — голая строка по-русски. */
        PlainTextError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description 409 — голая строка по-русски. */
        PlainTextConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Тариф не разрешает действие — голая строка. */
        PaymentRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Лимит частоты — голая строка. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Нет или недействителен токен (или неверные учётные данные). Тело пустое либо голая строка. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Нет прав. Тело пустое. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Не найдено. Тело пустое. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Выполнено, тела нет. */
        NoContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Требуется принять новую редакцию правовых документов. */
        LegalGate: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Правовые документы временно недоступны (голая строка). */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Только демо-режим: идёт сброс. Тело — «Демо обновляется, зайдите через минуту». */
        DemoResetting: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                "X-Demo-Resetting": components["headers"]["DemoResettingFlag"];
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /**
         * @description Демо-режим, токен демо-роли (claim sb_demo = 1): действие недоступно. ЕДИНСТВЕННЫЙ 403 с телом в проекте.
         *     Тело — «В демо-версии это действие недоступно.» Без демо-режима этот ответ невозможен (403 прежний, пустой).
         */
        DemoRestricted: {
            headers: {
                "X-Demo-Restricted": components["headers"]["DemoRestrictedFlag"];
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Успех. Форма не меняется в цикле 28 (описана в контрактах прежних циклов). */
        AnyJson: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": unknown;
            };
        };
    };
    parameters: {
        /** @description Id компании. */
        CompanyId: string;
        /** @description Id компании. */
        CompanyIdAlt: string;
        /** @description Id биллинг-аккаунта. */
        AccountId: string;
        Slug: string;
        Search: string;
        /** @description Номер страницы с 1. Невалидное значение нормализуется, а не отвергается. */
        Page: string;
        /** @description Размер страницы, клампится к [1, 100]. */
        PageSize: string;
        AdminPage: number;
        AdminPageSize: number;
        /**
         * @description Цикл 28. all (по умолчанию) — все строки; only — только витрина; exclude — без витрины.
         *     Любое другое значение — 400 text/plain «showcase должен быть одним из: all, only, exclude.»
         */
        ShowcaseFilter: "all" | "only" | "exclude";
    };
    requestBodies: never;
    headers: {
        /** @description Через сколько секунд повторить. */
        RetryAfter: number;
        /** @description Идёт сброс демо — фронт показывает экран «Демо обновляется». */
        DemoResettingFlag: "1";
        /** @description Отказ демо-роли — фронт показывает тело ответа. */
        DemoRestrictedFlag: "1";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    companiesGetAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список салонов каталога. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDto"][];
                };
            };
        };
    };
    companiesCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCompanyDto"];
            };
        };
        responses: {
            /** @description Создано (исторический код). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCompanyResponseDto"];
                };
            };
            /** @description Создано. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCompanyResponseDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            /**
             * @description «Slug already taken» (прежний) или, с цикла 28, «Адрес, начинающийся с «primer-», зарезервирован.
             *     Выберите другой.», или «Соглашение было обновлено ещё раз…» (прежний).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            451: components["responses"]["LegalGate"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    companiesGetPublic: {
        parameters: {
            query?: {
                cityId?: number;
                search?: components["parameters"]["Search"];
                /** @description Номер страницы с 1. Невалидное значение нормализуется, а не отвергается. */
                page?: components["parameters"]["Page"];
                /** @description Размер страницы, клампится к [1, 100]. */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница каталога. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedCompanyDto"];
                };
            };
            503: components["responses"]["DemoResetting"];
        };
    };
    companiesGetMy: {
        parameters: {
            query?: {
                kind?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Компании, где вызывающий — владелец. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDto"][];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["DemoResetting"];
        };
    };
    companiesGetBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Салон с галереей (photos заполнен). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDto"];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["DemoResetting"];
        };
    };
    companyMembersAdd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id компании. */
                id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberDto"];
            };
        };
        responses: {
            200: components["responses"]["AnyJson"];
            201: components["responses"]["AnyJson"];
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Прежние 409 маршрута либо, с цикла 28, «Витринную компанию и настоящие учётные записи смешивать нельзя.» */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            451: components["responses"]["LegalGate"];
        };
    };
    bookingsCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingDto"];
            };
        };
        responses: {
            /** @description Запись создана. В открытой витрине companyIsShowcase = true, исходящих сообщений нет. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            /** @description Компания или услуга не найдены (голая строка, исторически). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /**
             * @description text/plain — прежние отказы («Time slot is no longer available», магазин, правовые версии).
             *     application/json ShowcaseRefusalDto — цикл 28, запись в закрытую витрину.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                    "application/json": components["schemas"]["ShowcaseRefusalDto"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            451: components["responses"]["LegalGate"];
            /** @description Правовые документы недоступны или (демо) идёт сброс — голая строка. */
            503: {
                headers: {
                    "X-Demo-Resetting": components["headers"]["DemoResettingFlag"];
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    bookingsGetClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Записи клиента. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDto"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            451: components["responses"]["LegalGate"];
            503: components["responses"]["DemoResetting"];
        };
    };
    bookingsGetById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Запись. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            451: components["responses"]["LegalGate"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Токен. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    adminGetStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сводка. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminGetUsers: {
        parameters: {
            query?: {
                search?: components["parameters"]["Search"];
                page?: components["parameters"]["AdminPage"];
                pageSize?: components["parameters"]["AdminPageSize"];
                /**
                 * @description Цикл 28. all (по умолчанию) — все строки; only — только витрина; exclude — без витрины.
                 *     Любое другое значение — 400 text/plain «showcase должен быть одним из: all, only, exclude.»
                 */
                showcase?: components["parameters"]["ShowcaseFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница пользователей. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedAdminUserDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminGetCompanies: {
        parameters: {
            query?: {
                search?: components["parameters"]["Search"];
                page?: components["parameters"]["AdminPage"];
                pageSize?: components["parameters"]["AdminPageSize"];
                kind?: string;
                /**
                 * @description Цикл 28. all (по умолчанию) — все строки; only — только витрина; exclude — без витрины.
                 *     Любое другое значение — 400 text/plain «showcase должен быть одним из: all, only, exclude.»
                 */
                showcase?: components["parameters"]["ShowcaseFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница компаний. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedAdminCompanyDto"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminGetBillingAccounts: {
        parameters: {
            query?: {
                search?: components["parameters"]["Search"];
                status?: string;
                trial?: "never" | "active" | "used";
                page?: components["parameters"]["AdminPage"];
                pageSize?: components["parameters"]["AdminPageSize"];
                /**
                 * @description Цикл 28. all (по умолчанию) — все строки; only — только витрина; exclude — без витрины.
                 *     Любое другое значение — 400 text/plain «showcase должен быть одним из: all, only, exclude.»
                 */
                showcase?: components["parameters"]["ShowcaseFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница аккаунтов. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedAdminBillingAccounts"];
                };
            };
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminAssignSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id биллинг-аккаунта. */
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignSubscriptionInput"];
            };
        };
        responses: {
            200: components["responses"]["AnyJson"];
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /**
             * @description Прежние 409 (переполнение лимитов, заявка) либо, с цикла 28, «Служебный тариф витрины нельзя назначить
             *     настоящему аккаунту.» Прежние 409 этого маршрута могут быть JSON — форма не меняется.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    adminUpdateCompanyOwner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id компании. */
                id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCompanyOwnerDto"];
            };
        };
        responses: {
            204: components["responses"]["NoContent"];
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["DemoRestricted"];
            404: components["responses"]["NotFound"];
            /**
             * @description Прежний 409 (не связан с аккаунтом) либо, с цикла 28, «Витринную компанию и настоящие учётные записи
             *     смешивать нельзя.»
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    adminTransferCompany: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id компании. */
                companyId: components["parameters"]["CompanyIdAlt"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyTransferInput"];
            };
        };
        responses: {
            200: components["responses"]["AnyJson"];
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["DemoRestricted"];
            404: components["responses"]["NotFound"];
            /**
             * @description Прежние 409 переноса либо, с цикла 28, «Витринную компанию нельзя перенести в настоящий аккаунт, а
             *     настоящую — в витринный.» Прежние 409 этого маршрута могут быть JSON — форма не меняется.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    demoGetStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Экземпляр в демо-режиме. Во время сброса — 200 с resetting = true (не 503). */
            200: {
                headers: {
                    /** @description В демо-режиме — на всех ответах. */
                    "X-Robots-Tag"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoStatusDto"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    demoLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoLoginRequest"];
            };
        };
        responses: {
            /** @description Токен демо-роли (claim sb_demo = 1). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description «Неизвестная демо-роль.» */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            404: components["responses"]["NotFound"];
            /** @description «Демо-данные ещё не созданы. Зайдите чуть позже.» */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["DemoResetting"];
        };
    };
    profileChangePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: components["responses"]["AnyJson"];
            204: components["responses"]["NoContent"];
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["DemoRestricted"];
        };
    };
    profileChangePhone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: components["responses"]["AnyJson"];
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["DemoRestricted"];
            409: components["responses"]["PlainTextConflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    profileDeleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: components["responses"]["AnyJson"];
            204: components["responses"]["NoContent"];
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["DemoRestricted"];
            409: components["responses"]["PlainTextConflict"];
        };
    };
    billingSubmitSubscriptionRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: components["responses"]["AnyJson"];
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["DemoRestricted"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["PlainTextConflict"];
        };
    };
    billingActivateTrial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrialActivationInput"];
            };
        };
        responses: {
            200: components["responses"]["AnyJson"];
            400: components["responses"]["PlainTextError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["DemoRestricted"];
            404: components["responses"]["NotFound"];
            /** @description Отказ выдачи пробного (JSON цикла 18, форма не меняется). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
}
