import type { components } from '@/types/api-cycle23.generated'

/**
 * goods types are read straight off the generated cycle-23 schema (ARCHITECTURE_CYCLE23.md §399.2) —
 * never retyped by hand, so an append-only enum member surfaces as a type error where a switch needs it.
 */
type S = components['schemas']

export type CompanyKind = S['CompanyKind']
export type ShopRole = S['ShopRole']
export type ShopCustomerMode = S['ShopCustomerMode']
export type OrderAcceptanceMode = S['OrderAcceptanceMode']
export type ProductUnit = S['ProductUnit']
export type OrderStatus = S['OrderStatus']
export type OrderAction = S['OrderAction']
export type OrderEventKind = S['OrderEventKind']
export type OrderActorKind = S['OrderActorKind']
export type OrderProblemReason = S['OrderProblemReason']
export type OrderRefusalCode = S['OrderRefusalCode']
export type OrderConflictCode = S['OrderConflictCode']
export type CatalogConflictCode = S['CatalogConflictCode']

export type CatalogConflictDto = S['CatalogConflictDto']
export type CompanyKindsSummaryDto = S['CompanyKindsSummaryDto']
export type CreateShopInput = S['CreateShopInput']
export type CreateShopResponse = S['CreateShopResponse']
export type SlugCheckDto = S['SlugCheckDto']
export type ShopListItemDto = S['ShopListItemDto']
export type ShopSettingsDto = S['ShopSettingsDto']
export type ShopSettingsInput = S['ShopSettingsInput']
export type SellerInfoInput = S['SellerInfoInput']
export type SellerInfoDto = S['SellerInfoDto']
export type PublicSellerInfoDto = S['PublicSellerInfoDto']
export type ShopManageDto = S['ShopManageDto']
export type CategoryDto = S['CategoryDto']
export type CategoryInput = S['CategoryInput']
export type ProductDto = S['ProductDto']
export type ProductInput = S['ProductInput']
export type ProductOrderInput = S['ProductOrderInput']
export type StorefrontDto = S['StorefrontDto']
export type StorefrontCategoryDto = S['StorefrontCategoryDto']
export type StorefrontProductDto = S['StorefrontProductDto']
export type QuoteInput = S['QuoteInput']
export type QuoteDto = S['QuoteDto']
export type QuoteLineDto = S['QuoteLineDto']
export type OrderProblemDto = S['OrderProblemDto']
export type OrderLineInput = S['OrderLineInput']
export type CreateOrderInput = S['CreateOrderInput']
export type CreateOrderResponse = S['CreateOrderResponse']
export type OrderRefusalDto = S['OrderRefusalDto']
export type OrderConflictDto = S['OrderConflictDto']
export type PublicOrderDto = S['PublicOrderDto']
export type PublicOrderItemDto = S['PublicOrderItemDto']
export type MyOrderSummaryDto = S['MyOrderSummaryDto']
export type StaffOrderDto = S['StaffOrderDto']
export type StaffOrderCardDto = S['StaffOrderCardDto']
export type StaffOrderItemDto = S['StaffOrderItemDto']
export type OrderEventDto = S['OrderEventDto']
export type OrderBoardDto = S['OrderBoardDto']
export type IssueQuoteDto = S['IssueQuoteDto']
export type ActualQuantityInput = S['ActualQuantityInput']
export type EditOrderInput = S['EditOrderInput']
export type EditOrderLineInput = S['EditOrderLineInput']
