import type { components } from '@/types/api-cycle23.generated'
import type { components as C24 } from '@/types/api-cycle24.generated'
import type { components as C25 } from '@/types/api-cycle25.generated'
import type { components as C26 } from '@/types/api-cycle26.generated'

/**
 * goods types are read straight off the generated cycle-23 schema (ARCHITECTURE_CYCLE23.md §399.2) —
 * never retyped by hand, so an append-only enum member surfaces as a type error where a switch needs it.
 */
type S = components['schemas']
/** Cycle 24 (ARCHITECTURE_CYCLE24.md §462.1): DTOs the cycle changed come from the cycle-24 schema; the rest stay on cycle 23. */
type N = C24['schemas']
/** Cycle 25 (ARCHITECTURE_CYCLE25.md §509.1): DTOs of the cycle and the ones it changed come from the cycle-25 schema. */
type M = C25['schemas']
/** Cycle 26 (ARCHITECTURE_CYCLE26.md §545): StorefrontDto (+email, +photos), ShopManageDto (+city time-zone fields). */
type L = C26['schemas']

export type CompanyKind = N['CompanyKind']
export type ShopRole = N['ShopRole']
export type ShopCustomerMode = N['ShopCustomerMode']
export type OrderAcceptanceMode = N['OrderAcceptanceMode']
export type ProductUnit = N['ProductUnit']
export type OrderStatus = N['OrderStatus']
export type OrderAction = N['OrderAction']
export type OrderEventKind = N['OrderEventKind']
export type OrderActorKind = N['OrderActorKind']
export type OrderProblemReason = N['OrderProblemReason']
export type OrderRefusalCode = N['OrderRefusalCode']
export type OrderConflictCode = N['OrderConflictCode']
export type CatalogConflictCode = M['CatalogConflictCode']

/** Cycle-24 shape (keeps `conflictingOrders`) with the cycle-25 code list (+ `CatalogListingNotAllowedByPlan`). */
export type CatalogConflictDto = Omit<N['CatalogConflictDto'], 'code'> & { code: M['CatalogConflictCode'] }
export type CompanyKindsSummaryDto = S['CompanyKindsSummaryDto']
export type CreateShopInput = S['CreateShopInput']
export type CreateShopResponse = S['CreateShopResponse']
export type SlugCheckDto = S['SlugCheckDto']
export type ShopListItemDto = S['ShopListItemDto']
export type ShopSettingsDto = N['ShopSettingsDto']
export type ShopSettingsInput = S['ShopSettingsInput']
export type SellerInfoInput = S['SellerInfoInput']
export type SellerInfoDto = N['SellerInfoDto']
export type PublicSellerInfoDto = N['PublicSellerInfoDto']
export type ShopManageDto = L['ShopManageDto']
export type CompanyPhotoDto = L['CompanyPhotoDto']
export type CategoryDto = S['CategoryDto']
export type CategoryInput = S['CategoryInput']
export type ProductDto = N['ProductDto']
export type ProductInput = N['ProductInput']
export type ProductOrderInput = S['ProductOrderInput']
export type StorefrontDto = L['StorefrontDto']
export type StorefrontCategoryDto = N['StorefrontCategoryDto']
export type StorefrontProductDto = N['StorefrontProductDto']
export type QuoteInput = N['QuoteInput']
export type QuoteDto = N['QuoteDto']
export type QuoteLineDto = N['QuoteLineDto']
export type OrderProblemDto = N['OrderProblemDto']
export type OrderLineInput = N['OrderLineInput']
export type CreateOrderInput = N['CreateOrderInput']
export type CreateOrderResponse = N['CreateOrderResponse']
export type OrderRefusalDto = N['OrderRefusalDto']
export type OrderConflictDto = N['OrderConflictDto']
export type PublicOrderDto = N['PublicOrderDto']
export type PublicOrderItemDto = N['PublicOrderItemDto']
export type MyOrderSummaryDto = N['MyOrderSummaryDto']
export type StaffOrderDto = N['StaffOrderDto']
export type StaffOrderCardDto = N['StaffOrderCardDto']
export type StaffOrderItemDto = N['StaffOrderItemDto']
export type OrderEventDto = N['OrderEventDto']
export type OrderBoardDto = N['OrderBoardDto']
export type IssueQuoteDto = S['IssueQuoteDto']
export type ActualQuantityInput = S['ActualQuantityInput']
export type EditOrderInput = S['EditOrderInput']
export type EditOrderLineInput = S['EditOrderLineInput']
export type OrderTimelineStep = N['OrderTimelineStepDto']
export type OrderChangeLine = N['OrderChangeLineDto']
export type OrderShopChange = N['OrderShopChangeDto']
export type OrderBoard = N['OrderBoardDto']

// ── Cycle 24 (API_CONTRACT_CYCLE24.md) — new schemas and enums.
export type PickupKind = N['PickupKind']
export type ShopAcceptanceMode = N['ShopAcceptanceMode']
export type PauseDuration = N['PauseDuration']
export type SoldOutScope = N['SoldOutScope']
export type ShopNotAcceptingCode = N['ShopNotAcceptingCode']
export type OrderLimitWarningLevel = N['OrderLimitWarningLevel']
export type StorefrontUnavailableReason = N['StorefrontUnavailableReason']
export type DayOfWeek = N['DayOfWeek']
export type NotificationTransport = N['NotificationTransport']
export type NotificationDeliveryMode = N['NotificationDeliveryMode']

export type WorkingHoursDto = N['WorkingHoursDto']
export type WorkingHoursInput = N['WorkingHoursInput']
export type WorkingDayDto = N['WorkingDayDto']
export type TimeIntervalDto = N['TimeIntervalDto']
export type TimeIntervalInput = N['TimeIntervalInput']
export type SpecialDayDto = N['SpecialDayDto']
export type SpecialDayInput = N['SpecialDayInput']
export type PickupSettingsDto = N['PickupSettingsDto']
export type PickupSettingsInput = N['PickupSettingsInput']
export type AcceptanceInput = N['AcceptanceInput']
export type ShopAcceptanceDto = N['ShopAcceptanceDto']
export type ShopOpenStateDto = N['ShopOpenStateDto']
export type ShopOrderingStatusDto = N['ShopOrderingStatusDto']
export type OrderLimitDto = N['OrderLimitDto']
export type SetupChecklistItemDto = N['SetupChecklistItemDto']
export type AsapOptionDto = N['AsapOptionDto']
export type PickupOptionsDto = N['PickupOptionsDto']
export type PickupDateDto = N['PickupDateDto']
export type PickupSlotDto = N['PickupSlotDto']
export type PickupSlotsDto = N['PickupSlotsDto']
export type PickupSelectionInput = N['PickupSelectionInput']
export type OrderPickupDto = N['OrderPickupDto']
export type PickupProblemDto = N['PickupProblemDto']
export type SoldOutDto = N['SoldOutDto']
export type SoldOutInput = N['SoldOutInput']
export type CategoryWeekdaysInput = N['CategoryWeekdaysInput']
export type DailyMenuCalendarDto = N['DailyMenuCalendarDto']
export type DailyMenuDayDto = N['DailyMenuDayDto']
export type DailyMenuDto = N['DailyMenuDto']
export type DailyMenuProductDto = N['DailyMenuProductDto']
export type DailyMenuInput = N['DailyMenuInput']
export type ShopNotificationSettingsDto = M['ShopNotificationSettingsDto']
export type ShopNotificationSettingsInput = M['ShopNotificationSettingsInput']
export type ShopChannelStatusDto = N['ShopChannelStatusDto']
export type ScheduleConflictOrderDto = N['ScheduleConflictOrderDto']
export type PreorderGroupDto = N['PreorderGroupDto']
export type ChangePickupInput = N['ChangePickupInput']
export type OrderPushSubscribeInput = N['OrderPushSubscribeInput']
export type OrderPushStateDto = N['OrderPushStateDto']
export type OrderMessengerStatusDto = N['OrderMessengerStatusDto']
export type OrdersUsageDto = N['OrdersUsageDto']
export type AvailablePlanDto = N['AvailablePlanDto']
export type PushConfigDto = N['PushConfigDtoCycle24']
export type PushSubscriptionDto = N['PushSubscriptionDto']
export type AssignChannelCompanyInput = N['AssignChannelCompanyInput']
export type OrderWebPushInfoDto = N['OrderWebPushInfoDto']
export type OrderCustomerNotificationsDto = N['OrderCustomerNotificationsDto']

// ── Cycle 25 (API_CONTRACT_CYCLE25.md) — history, summary, pick list, buyer card, catalog, MAX for staff.
export type ReportPeriodPreset = M['ReportPeriodPreset']
export type OrderHistorySort = M['OrderHistorySort']
export type SummaryTopSort = M['SummaryTopSort']
export type StaffMaxStatus = M['StaffMaxStatus']
export type CatalogAcceptance = M['CatalogAcceptance']
export type CatalogListingCheckCode = M['CatalogListingCheckCode']

export type ReportPeriodDto = M['ReportPeriodDto']
export type StaffMaxStatusDto = M['StaffMaxStatusDto']
export type StaffMaxLinkSessionDto = M['StaffMaxLinkSessionDto']
export type OrderHistoryQuery = M['OrderHistoryQuery']
export type OrderHistoryRowDto = M['OrderHistoryRowDto']
export type OrderHistoryPageDto = M['OrderHistoryPageDto']
export type ShopSummaryDto = M['ShopSummaryDto']
export type SummaryShareDto = M['SummaryShareDto']
export type SummaryTopItemDto = M['SummaryTopItemDto']
export type SummaryDayDto = M['SummaryDayDto']
export type SummaryComparisonDto = M['SummaryComparisonDto']
export type PickListDto = M['PickListDto']
export type PickListSlotOptionDto = M['PickListSlotOptionDto']
export type PickListProductDto = M['PickListProductDto']
export type PickListOrderDto = M['PickListOrderDto']
export type PickListTimeGroupDto = M['PickListTimeGroupDto']
export type ShopCustomerCardDto = M['ShopCustomerCardDto']
export type ShopCustomerNoteDto = M['ShopCustomerNoteDto']
export type ShopCustomerNoteStateDto = M['ShopCustomerNoteStateDto']
export type GoodsCatalogPageDto = M['GoodsCatalogPageDto']
export type GoodsCatalogShopDto = M['GoodsCatalogShopDto']
export type CatalogCityDto = M['CatalogCityDto']
export type CatalogListingDto = M['CatalogListingDto']
